### ISSUE TITLE
commit 0959c19ff5a1cf5d2b5420da29dbcbd68ebcf7c6 causes issue on the default front page

### ISSUE THREAD

**Issue by shunlir** [OpenGrok/OpenGrok#1001]
Hi @djgilcrease 
After applied this change, &lt;div id="qtbl"&gt; and &lt;div id="ptbl"&gt; are lapped over &lt;div id="results"&gt;, causing the text can't be seen.
Issue:
![image](https://cloud.githubusercontent.com/assets/14887081/10244669/72b30588-6933-11e5-9718-6982731c20e9.png)
Normal:
![image](https://cloud.githubusercontent.com/assets/14887081/10244712/cd1e96ae-6933-11e5-8ed9-b87e9f1a4eb8.png)

can you please look at this issue? I tested with firefox 43 developer edition and Chrome 45, both have issue.

**Comment by tarzanek** [comment]
I reverted that patch for now ...
