### ISSUE TITLE
Issue for Golang support

### ISSUE THREAD

**Issue by shunlir** [OpenGrok/OpenGrok#1002]
Hi @patricklundquist @tarzanek 
Thanks for your great job. I know OpenGrok added Universal ctags support at the end of Jul. 2015, and added support for Golang just now.
@patricklundquist, can you please add user-defined Golang mapping command options only when running Exuberant Ctags? Since Exuberant Ctags doesn't support Golang internally, however Universal ctags(https://github.com/universal-ctags/ctags) provides more powerful built-in support for Golang, if Universal ctags is used, the user-defined Golang mapping will take a higher priority, this is not desired.
The command line options you added for Golang mapping:
![111](https://cloud.githubusercontent.com/assets/14887081/10245640/01be2f5c-693c-11e5-8cbb-9dc0969ca487.png)
This is what Universal Ctags provides for Golang:
![image](https://cloud.githubusercontent.com/assets/14887081/10245676/4cc888f8-693c-11e5-901d-4d8f8a2a9677.png)

Maybe, this commit can help you to check the running Universal/Exuberant ctags: https://github.com/OpenGrok/OpenGrok/commit/3ea68c10d5745d361c86c32b59fe10e13157c251

**Comment by patricklundquist** [comment]
Thanks Shunlir, I didn't know about the Universal ctags support. I'll look into this.

**Comment by tarzanek** [comment]
Opengrok can detect universal ctags I added some basic check.
So this is doable  and makes sense, thnx for heads up

**Comment by tarzanek** [comment]
this was fixed with #1005 , closing
