### ISSUE TITLE
Search error without ""

### ISSUE THREAD

**Issue by AsCatgz** [OpenGrok/OpenGrok#1011]
Hello.
I installed openGrok opengrok-0.12.1.5. Now I encounter this issue:
1. In the web, when I search ro.product.locale.language, 
***** I must enter "ro.product.locale.language" in Full Search, the web show "Searched full:"ro . product . locale . language" (Results 1 - 21 of 21) sorted by relevance". 
***** If just input ro.product.locale.language (without the " "), it return many result but not correct， the web show "Searched +full:ro +full:. +full:product +full:. +full:locale +full:. +full:language (Results 1 - 25 of 227) sorted by relevance".

I see the site http://androidxref.com/5.1.1_r6/ no need "", but work well.

2. In the cli, I use the org.opensolaris.opengrok.search.Search to search to search and use option -f ro.product.locale.language, whose result is similar with the result of web without "". And seems no way to resolve it.

So, I want to know how I can make our project work well without "". 

Thanks.
Best Regards.

**Comment by tarzanek** [comment]
this is how the query parser works
so one would need to improve query parser to stop parsing "." as filename.ext separator ...
also note that whole index divides tokens by "."
so ro.product.locale.language are 4 tokens
this is how lucene works, but yes, it can be improved (and with lucene 4.x and 5.x we have the power to do it, I'd love the index to index more words + be case sensitive on demand)

**Comment by tarzanek** [comment]
in shell I'd test it like this:
-f  \"ro.product.locale.language\" 

hth
L

**Comment by AsCatgz** [comment]
I tested -f \"ro.product.locale.language\" . It works well ! 
Thanks
BestRegards
