### ISSUE TITLE
How to reuse the index data below {DATA_ROOT} after updating source.war?

### ISSUE THREAD

**Issue by faywong** [OpenGrok/OpenGrok#1027]
I have a large code base in {SRC_ROOT}, it spends more than two days to index all the source code from scratch.
Yesterday i updated the content of source.war(cherry-picked this [commit](https://github.com/OpenGrok/OpenGrok/commit/612f0bcebbddf3209bf5c7b8d6ff880c1e6660ce)]), then the portal page at "/source" can't list any projects.

And i verified that if i run a OpenGrok index，then the project is listed in the portal page at "/source".

So how can i reuse the old index in {DATA_ROOT} after updating source.war?

**Comment by tarzanek** [comment]
it's all about /var/opengrok/etc/configuration.xml
it needs to point to your DATA_ROOT/etc/configuration.xml
(symlink would do too)
and then restart webapp container

alt. check what I merged today https://github.com/OpenGrok/OpenGrok/pull/1026

hth
L

**Comment by faywong** [comment]
Got it. Thanks.
