### ISSUE TITLE
index task blocks when encountering ^M

### ISSUE THREAD

**Issue by faywong** [OpenGrok/OpenGrok#1028]
It seems that the index task always been blocked at 5% process when indexing a large code base.

the verbose log is like this:
 "
......
17:30:42 INFO: Progress: 957 (5.065%)
17:30:42 INFO: Add: /cp_integrate_release_469674/android-phone-aliuser/aliuser/biz/src/com/ali/user/mobile/service/impl/UserRegisterServiceImpl.java (JavaAnalyzer)
17:30:42 INFO: Progress: 958 (5.07%)
17:30:42 INFO: Add: /cp_integrate_release_469674/android-phone-aliuser/aliuser/biz/src/com/ali/user/mobile/util/Base64.java (JavaAnalyzer) {block at here}
"

If i killed the index task and rerun it, it will block at the same file('Base64.java') as well.

And i found that it will blocks when a file contains ^M(carriage return)(the OS of my workstation is Linux).

If i use perl to replace all the ^M with \n，then the index task finishes.

**Comment by tarzanek** [comment]
This seems like a bug - does it block in ctags or in grok?
Can you share that file?

**Comment by faywong** [comment]
>>This seems like a bug - does it block in ctags or in grok
I am not sure.

>>Can you share that file?
[Bad.txt](https://github.com/OpenGrok/OpenGrok/files/41516/Bad.txt)

Please rename it to Bad.java

**Comment by tarzanek** [comment]
@faywong I might have fixed this, it was a regression of scopes
fix was in 2332ece84d127ebb7fb32cdc296444622cff1dab

**Comment by tarzanek** [comment]
@faywong can you retry with recent build
sorry it took so long to fix :(

**Comment by tarzanek** [comment]
marking this as stopper as I need to convert this into a junit test

**Comment by faywong** [comment]
@tarzanek OK. Thanks for your effort. I will feedback to this issue after i retried it.
