### ISSUE TITLE
Must hit back twice to go back after following link to file

### ISSUE THREAD

**Issue by kahatlen** [OpenGrok/OpenGrok#1053]
I see this in Firefox 44. Could not reproduce on Chrome 48.

If I click a file name, either in the list of search result or from the xref directory listing, I need to hit "back" twice to get back to the search result or directory listing.

After I click the file name, the address bar in Firefox shows something like "http://localhost:8080/source/xref/test.txt#". Notice the trailing "#". The first time I click "back", the "#" disappears from the address bar, but I'm still viewing the file. The address bar says "http://localhost:8080/source/xref/test.txt". I need to hit "back" yet another time in order to get back to where I came from.

git bisect says:

> 2e3cf399f97f30eab07248830e49d29fcb3e7f27 is the first bad commit
> commit 2e3cf399f97f30eab07248830e49d29fcb3e7f27
> Author: Lubos Kosco <tarzanek@gmail.com>
> Date:   Wed Dec 16 18:22:26 2015 +0100
> 
>     fix XSS problem reported by Alex Concha
> 
> :040000 040000 c0c425cd42e158eb828c7b4741eeaf615f079571 d1c7b158c50e18d3d711d9e2a579117489745c4c M	src
> :040000 040000 5be73e756ccff5b2f91367dfc43f34981527ab30 0dc1da00afe85174f1ae5686382477ccde4a25b9 M	web

**Comment by tarzanek** [comment]
;) noticed this yesterday too
Thnx for root cause, will fix

**Comment by kahatlen** [comment]
Excellent! I haven't looked into what part of the fix that caused this. One question about the original fix, though: What's the difference between Util.escapeXml() and Util.formQuoteEscape()? Would it be sufficient to have only one of them?

**Comment by tulinkry** [comment]
I noticed that changing line https://github.com/OpenGrok/OpenGrok/blob/master/web/utils.js#L845 (```domReadyMast()```)
to this:       
```
if (h != null && h != "null" && h != "")  {
```
eliminates the problem for me (Mozilla). Which means a test for an empty string.

**Comment by tarzanek** [comment]
@tulinkry can you open a pull req pls ?

**Comment by kahatlen** [comment]
That seems to fix it for me too. Thanks!
