### ISSUE TITLE
Unexpected behaviour of OpenGrokProject cookie

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1064]
I discovered an unusual behavior of that cookie. A way to reproduce is:

While having three projects (android, old, git):
 - select two projects in multiselect box, press search and cookie becomes OpenGrokProject="android,git"
 - open the third one 'old' by an xref link and cookie becomes OpenGrokProject="old/git,old/android"
 - upon opening any other project (even the original two) with an xref link the cookie grows like OpenGrokProject="git/git/git/git/old/android,old/git" and so on.

Projects in form of old/git... are not recognized correctly for auto select and other features (because it expects comma separator). And also by a coincidence the cookie can grow to its maximum size.

This buggy behaviour seems to be caused by this [list.jsp#94](https://github.com/OpenGrok/OpenGrok/blob/master/web/list.jsp#L94) line where the slash '/' should be replaced with comma ',' because in [PageConfig](https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/web/PageConfig.java#L678) the cookie is constructed similar way using comma as a glue.

**Comment by ockernuts** [comment]
When running on Tomcat 9, I had a similar problem with cookie content. Apparently a comma is then also not allowed as a cookie content (tomcat throwing IllegalArgumentException because a token 44 is see) . I reverted to Tomcat 8 and this works.
