### ISSUE TITLE
Index database(s) not found.

### ISSUE THREAD

**Issue by kaikiat8080** [OpenGrok/OpenGrok#1071]
Hi everyone,
Our Opengrok repository in our local server is suddenly showing this message "Index database(s) not found" when we try to search for anything.
Browsing the repository is fine though.

Could someone provide me a step to step guide with commands on how to resolve this?
Thank you in advance because I do not have much experience with Opengrok administration.

Thanks..

**Comment by tarzanek** [comment]
your configuration of webapp doesn't point to proper indexes, or indexes are gone
verify if indexes exist and verify in web.xml if the data root points to proper directory
https://github.com/OpenGrok/OpenGrok/blob/master/README.txt#L367
all this gets configured automagically when indexer is done, it will send new config to webapp, that might be also broken in your setup
hth
L

**Comment by kaikiat8080** [comment]
Hi,
I ran the ./OpenGrok index command to try to recreate the index and upon completion,but I still got the same error.
Any other pointer?

Sorry, as I am really clueless about the Opengrok setup, could someone help me out by pointing to me to steps I need to do?
Thanks..

**Comment by tarzanek** [comment]
well, read the readme step by step, try to understand it, alt. there are lots of blogs about how this works. Shortly:
OpenGrok deploy  - should setup properly the webapp and make sure it will listen for config - it's your duty to solve permissions of webapp container to the index or to the SCMs
OpenGrok index - this will start indexing and once done it will send the config to webapp (if it is on the same machine and properly listens to configs)
OpenGrok can have various options, if you don't use standard dirs ( check https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok#L5 )
Also make sure you use proper supported apps - java from Oracle, one of supported OSes, supported container (tomcat, glassfish) - it might work on others, but you're on your own there ...

**Comment by tarzanek** [comment]
check requirements: https://opengrok.github.io/OpenGrok/
and for dev build check requirements in https://github.com/OpenGrok/OpenGrok/blob/master/README.txt#L6 - your should start here definitely ...

**Comment by kaikiat8080** [comment]
Thanks again.
It was still working fine a couple of weeks ago, only to this error out of the sudden.
Any potential issue that you could think of?

Thanks..

**Comment by tarzanek** [comment]
I lack info about your env, so it's hard to see any change for me ;)
And I don't talk to crystal balls :-P

**Comment by kaikiat8080** [comment]
OK, anything that I could provide you so that you could help me?
I know this is a bit too much to ask, but just need some help here.

Many thanks..

**Comment by vladak** [comment]
Firstly, there is no "sudden" malfunction. Something had to change.

Start with the usual stuff:
  - operating system details
  - OpenGrok version, how it was installed (either from package or built from source)
  - where on the filesystem is your source code located

**Comment by vladak** [comment]
No reply for 2+ weeks, closing for now.
