### ISSUE TITLE
collapsible revision messages on history page

### ISSUE THREAD

**Issue by vbro** [OpenGrok/OpenGrok#1076]
For long revision messages on the history page, allow the revision message to be collapsible with a "show more/show less" javascript link.
This allows for a more concise page and makes the "compare" radio buttons easily accessible for revisions with long messages.

**Comment by tarzanek** [comment]
reopening, can you please address the comments from Knut in #1077  please?

**Comment by tulinkry** [comment]
The comment about updating both styles has been already solved in #1080

**Comment by vladak** [comment]
the other remaining comment from @kahatlen was filed as #1482 , thus closing.
