### ISSUE TITLE
could not append options when using "bin/OpenGrok index"

### ISSUE THREAD

**Issue by mosyang** [OpenGrok/OpenGrok#1086]
I am following below steps to change name of the web application from source to new_name.
https://github.com/OpenGrok/OpenGrok/wiki/How-to-install-OpenGrok#optional-need-to-change-web-application-properties-or-name
When I run `OPENGROK_INSTANCE_BASE=/data/new_name OpenGrok index -w new_name`
It always return "Usage" information because bin/OpenGrok script exit if parameters number >=2

Similar issue: http://stackoverflow.com/questions/35273644/opengrok-http-status-404-source-s-when-trying-to-open-cpp-file-via-an-xref

**Comment by tarzanek** [comment]
:-D
index doesn't take any other option
-w must go inside the script
we don't have a "-w" exposed by script
but the jar does accept -w ...
there is a OPENGROK_WEBAPP_CONTEXT
so what you want to do is:
`$ OPENGROK_WEBAPP_CONTEXT=new_name OPENGROK_INSTANCE_BASE=/data/new_name OpenGrok index`

**Comment by tarzanek** [comment]
I will close this issue, if I didn't answer your Q, reopen please.

**Comment by mosyang** [comment]
Hi Tarzanek:
Great thanks for your support!!
