### ISSUE TITLE
Rebuild Index

### ISSUE THREAD

**Issue by devangsmodi** [OpenGrok/OpenGrok#1089]
Hi Team,

I setup OpenGrok for my code and its working fine. 

Now lets say - I did modified sources / added new file or Removed few files from CC. 
So my question is - when index will be regenerated ? Do I need to regenerate it explicitly or OpenGrok will take care of it - if yes then how OpenGrok will get to know that I modified source ?

Thanks & Regards,
Devang Modi.

**Comment by vladak** [comment]
Indexing is always explicit - i.e. you have to run it yourself.

**Comment by devangsmodi** [comment]
Hi Vladak,

Thanks for reply. How can I run explicit ? 
I am using windows based grokit - While setup I saw only two options (available in help)
--path 
--action

Please let me know any other options. 

Thanks & Regards,
Devang Modi.

**Comment by tarzanek** [comment]
grokit is not supported by us
ideally try to run OpenGrok on some linux/solaris system, we don't support Windows, though this might change with the Ubuntu integration into Windows 10 ...

**Comment by tarzanek** [comment]
and what Vlad meant is that if you run indexing again with same options, it will do automagically an incremental index, so it's as easy as running indexing again(and keeping old data dir)
