### ISSUE TITLE
redesign scopes to create its field during xrefs instead of another read

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1090]
Scopes currently added one more read to indexing.
I think when we'd redesign xref apis we can do scopes during xref generation, so we'd save one more read
This issues is a placeholder for discussion around this redesign.
@mrate @vladak @kahatlen ping!

The goal is to have scopes, but still be on the same performance as before (right now if I compare indexing to what it was before scopes I get like 20-30% slow down).
Another goal is to deduplicate methods that read and parse files to avoid bugs such as EOL parsing blocker - https://github.com/OpenGrok/OpenGrok/commit/2332ece84d127ebb7fb32cdc296444622cff1dab

**Comment by vladak** [comment]
I think anything in the order of 20-30% performance degradation is a stopper.

**Comment by tarzanek** [comment]
fix for #1092 will fix this nicely

**Comment by vladak** [comment]
This was integrated as d8d583c99ed3b39d4697571cd76622d6226209dc etc. so this can be closed I believe.
