### ISSUE TITLE
HTTP Status 404 - /source/search on windows

### ISSUE THREAD

**Issue by amitbendale8** [OpenGrok/OpenGrok#1091]
I followed this tutorial for installation in windows. Indexing is done properly.

http://algopadawan.blogspot.in/2012/07/installing-opengrok-on-windows.html

http://localhost:8080/source/

Displays the form elements. After giving input and clicking search, it's giving 404 error.

Same error for http://localhost:8080/source/xref/

Opengrok version: opengrok-0.12.1.5

**Comment by tarzanek** [comment]
that howto is for 0.11 and the command line is probably not sufficient
windows is not supported, unless you know what you are doing

Can you try the same inside a VM with Solaris/Linux using official docs please?
If for nothing else, it will at least give you using OpenGrok script correct command line for java used for jar file

Alt. we're trying to get out docker setup file for OpenGrok and ev. once official release of Ubuntu on Windows is in Windows 10, we might consider Windows as supported platform

hth
L

**Comment by amitbendale8** [comment]
Ok..thanks.. will try on ubuntu...

**Comment by tarzanek** [comment]
fwiw - most probably your web.xml needs adjustments to where the index is, ev. tomcat needs permissions
but it's just too many things that can go wrong ...

**Comment by tarzanek** [comment]
yeah - per above blog - the section of adding 
  -------Added the below------  
is wrong

to get you a quick start - SKIP steps 7 and 8 and don't modify the .war file
and instead on your drive C: do this:
create C:\var\opengrok\source
there clone your code
then indexer would look like:
 java -jar opengrok.jar -W C:\var\opengrok\etc\configuration.xml -c G:\ctags58\ctags.exe -P -S -v -s C:\var\opengrok\source -d C:\var\opengrok\data  
also create C:\var\opengrok\log

fwiw my windows indexer looks like this .bat file:
set WEBAPP="localhost:2424"
set PROPERTIES="-Dorg.opensolaris.opengrok.history.git=C:\Program Files\Git\bin\git.exe"
set SCAN_FOR_REPOS="-S"
set LPROPERTIES="-Djava.util.logging.config.file=logging.properties"
set DATA_ROOT="C:\var\opengrok\data"
set SRC_ROOT=C:\var\opengrok\source
java %PROPERTIES% %LPROPERTIES% -jar %PROGDIR%opengrok.jar -U %WEBAPP% -P -W C:\var\opengrok\etc\configuration.xml  %SCAN_FOR_REPOS% -r on -a on -v -c %EXUB_CTAGS% -s %SRC_ROOT% -d %DATA_ROOT%


default opengrok.war file always tries to find data in C:\var\opengrok ...

hth
L

**Comment by amitbendale8** [comment]
It worked... Thanks a ton..
