### ISSUE TITLE
grey bar in directory listing should be converted to floating window

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1098]
On testing instance running 42cc096fd002a6eab6be082271e28d4853acd318 I see a grey bar in directory listing which should not really be there.
![grey-bar](https://cloud.githubusercontent.com/assets/2934284/15210029/9bcb87f0-1834-11e6-98fc-e6d533cb17af.png)

**Comment by mrate** [comment]
I did some improvements to the scopes UI and this is one of the issues it addresses. Pull request is ready.

**Comment by tarzanek** [comment]
confirming @mrate last pull requests #1100 and #1101 fixed this, closing

**Comment by vladak** [comment]
As of 8c13ddaaf5d79ec5a234c256cb1a5ddaeceb7545, I am still seeing the grey bar, reopening.

**Comment by vladak** [comment]
fixed by cset 0c79c99dd8a7d8db88ecaa19f41282cb01f6ff0b
