### ISSUE TITLE
color palette for Annotate should align with overall color scheme

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1099]
The color palette used for Annotate stands out too much I think. The green color does not really match the overall coloring used in OpenGrok. Also, the yellow/green should really be a gradient of single color.

**Comment by vladak** [comment]
![grok-colors](https://cloud.githubusercontent.com/assets/2934284/15210496/11fa1732-1837-11e6-9860-a5aa27214cac.jpg)

**Comment by tulinkry** [comment]
I played a bit with the colors and propose four variants. It's hard to find a color which doesn't outstand when the main opengrok color scheme is grey.

![screenshot from 2016-06-02 14 20 52](https://cloud.githubusercontent.com/assets/6997160/15744704/d97d9eb8-28cd-11e6-872b-b324f477dff3.png) ![screenshot from 2016-06-02 14 21 56](https://cloud.githubusercontent.com/assets/6997160/15744706/d9817056-28cd-11e6-8080-93c2c5af6a8a.png) ![screenshot from 2016-06-02 14 23 33](https://cloud.githubusercontent.com/assets/6997160/15744705/d98012e2-28cd-11e6-8db0-8e6fe4f63a6d.png) ![screenshot from 2016-06-02 14 41 52](https://cloud.githubusercontent.com/assets/6997160/15745108/63a187ba-28d0-11e6-8659-c17f63c8785d.png)


The third (just yellow) looks fine with context:
![screenshot from 2016-06-02 14 27 45](https://cloud.githubusercontent.com/assets/6997160/15744755/36b15b38-28ce-11e6-9605-47e02b705695.png)

As well as the fourth (color taken from the line in the top bar)
 ![screenshot from 2016-06-02 14 43 12](https://cloud.githubusercontent.com/assets/6997160/15745118/7043feb2-28d0-11e6-9030-27c5ab7b2291.png)


Which is better?

**Comment by vladak** [comment]
If there is anything that can be called OpenGrok palette, it would be blue and grey in the log and maybe the orange in the horizontal bar. Anyways, I like the orange.

**Comment by tulinkry** [comment]
fixed by #1146
