### ISSUE TITLE
OPENGROK_WEBAPP_CONTEXT flag not updating xref for existing indexed projects

### ISSUE THREAD

**Issue by rahul-chhabra** [OpenGrok/OpenGrok#1105]
Hi,
While deploying opengrok for first time I had changed webapp name from source.war to opengrok.war. Indexing had worked fine and everything went smooth.

However I have noticed few of internal URL in xref are pointing to /source/s. 
I am indexing now with flag OPENGROK_WEBAPP_CONTEXT =/opengrok, it is working fine for new projects in list. But not for existing old one which are already indexed. The only option is to delete old projects index and reindex them again all. 

1. Is it expected behavior ?
2. Is their any flag to forcefully reindex, instead of manually deleting and indexing again.

Many thanks,
Rahul

**Comment by tarzanek** [comment]
1. Yes
2. No, unfortunately no force flag ... yet

Hth
L

**Comment by rahul-chhabra** [comment]
Thanks @tarzanek for confirmation.
I will manually delete all index, and will reindex.
