### ISSUE TITLE
annotation display breaks with long summary

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1106]
When annotation summary contains a long summary on one line, the whole annotation box is displayed incorrectly out of the screen.

Currently (for long Lorem ipsum) out of the screen on the left side:

![screenshot from 2016-06-01 12 05 36](https://cloud.githubusercontent.com/assets/6997160/15705923/7b6358cc-27f1-11e6-8976-11b49b2950cb.png)

Expected (or at least satisfying):

![screenshot from 2016-06-01 12 05 57](https://cloud.githubusercontent.com/assets/6997160/15705925/7d4af1e0-27f1-11e6-8e4d-abd24a8d44b5.png)

Possibly limit the box width, or insert newlines?

**Comment by tulinkry** [comment]
adding this option to .css may solve the problem

```css
#tooltip {
    /* ... other ... */
    word-break: break-all;
}
```

**Comment by tarzanek** [comment]
I am OK with that , it seems it won't impact anything else  ...

**Comment by tulinkry** [comment]
fiixed by #1145
