### ISSUE TITLE
What is the expected release date for v0.13?

### ISSUE THREAD

**Issue by choudhary001** [OpenGrok/OpenGrok#1149]
Hi, 
I am looking to upgrade my opengrok setup from v0.9 to latest and I see that v0.13-rc2 has been released. I am just curious whether to upgrade to v0.12-stable or wait for v0.13?

What does the developers here recommend?

Thanks,
Abhi

**Comment by vladak** [comment]
I'd wait for 0.13, it is worth it.

We should be releasing in couple of weeks, no hard dates though. There might be another rc or two.
