### ISSUE TITLE
tar.gz files unavailable for download

### ISSUE THREAD

**Issue by eric-hu** [OpenGrok/OpenGrok#1158]
The [install guide](https://github.com/OpenGrok/OpenGrok/wiki/How-to-install-OpenGrok) references binaries on java.net for installing.  However, these links redirect to Github, even though [the downloads page is still up on java.net](https://java.net/projects/opengrok/downloads).

**Comment by vladak** [comment]
fixed, thanks ! The install guide obviously needs more work.
