### ISSUE TITLE
java stack trace query parser

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1162]
It'd be lovely if grok would understand a pasted stack trace and was able to give you hints based on this stack trace
@jhkst would you dare?

Wireframes - I would expect some checkbox, that will change the "full search" input line into a box where one could paste the stack, then in backend appropriate query parser would be needed which would analyze the stack into more queries and respond with some sane result ...

**Comment by vladak** [comment]
Sounds like more of an idea for OpenGrok plugin rather than in-core functionality.

**Comment by tarzanek** [comment]
well @jhkst already has the code ready, it just needs a merge and retest (and I think the UI part is tough - so I guess @tulinkry might be able to help?)
I will be in the office this week, let's do lunch together ...

**Comment by vladak** [comment]
closing as per off-line discussion
