### ISSUE TITLE
make parsers stop producing tokens > 32766 chars

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1170]
last lucene versions imposed a limit on how big terms can be
so you can easily end up with:

> Aug 12, 2016 3:07:27 PM org.opensolaris.opengrok.index.IndexDatabase indexDown
> WARNING: Failed to add file /source/foobar.xml
> java.lang.IllegalArgumentException: Document contains at least one immense term in field="full" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[101, 57, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 102, 48, 48, 48, 48, 48, 48, 48, 102, 48, 49, 55, 48]...', original message: bytes can be at most 32766 in length; got 89226
>         at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:772)
>         at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:417)
>         at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:373)
>         at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232)
>         at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:449)
>         at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1492)
>         at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1271)
>         at org.opensolaris.opengrok.index.IndexDatabase.addFile(IndexDatabase.java:635)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:883)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
>         at org.opensolaris.opengrok.index.IndexDatabase.indexDown(IndexDatabase.java:848)
>         at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:397)
>         at org.opensolaris.opengrok.index.IndexDatabase$2.run(IndexDatabase.java:184)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 89226
>         at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:263)
>         at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:150)
>         at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:762)
>         ... 21 more

so parsers can try hard and still this will be dropped from index
- we can have files where this will take e.g. 4h for a simple file to be indexed (imagine xml file with <blob>0032023040a00f000h0004949d32323b0000 .... </blob>  - the chars between blob are hex numbers without any whitespace and it's more than 32766 of them ) - which will eventually be dropped - so once this is fixed indexing should be faster and skip/encounter such dummy binary files much earlier

**Comment by tarzanek** [comment]
@ilovemaui
filing this on your behalf, I will try to fix our jflex parsers to stop parsing after 32766 byte ...

**Comment by tarzanek** [comment]
marking as stopper since I've seen this with our repos and with android repos a lot

**Comment by tarzanek** [comment]
(so I hope once fixed my internal setup will get the indexing done in faster time, if I'd get 20% faster out of this fix, I'd be happy :) )

**Comment by tarzanek** [comment]
https://github.com/jflex-de/jflex/issues/203
now contains my Q on jflex, so wondering if it has any ways how to achieve this limiting

**Comment by joelagnel** [comment]
Do we really want to skip these files completed? Some times some files may only contain only lengthy token so other tokens are still valid.

**Comment by tarzanek** [comment]
@joelagnel this is exactly what I'd like to achieve with this fix ... skip just big token and continue with next one

**Comment by tarzanek** [comment]
@joelagnel right now whole file will be dropped just because a length token is found ...

**Comment by tarzanek** [comment]
I'd like to close this, but let's wait until we get a pom.xml integration of this fix too

**Comment by tarzanek** [comment]
closing, opened new bug for mvn, ant is the primary build system for releases

**Comment by pmv** [comment]
Is it true that this ticket should have fixed all parsers?  And the .tar.gz files of the release candidates are built by ant, and not maven (https://github.com/OpenGrok/OpenGrok/releases/tag/0.13-rc10)?

I downloaded rc10 from the link above, but I'm still seeing this error come out when trying to index some javascript files.  Just trying to determine if I've missed something or if the bug isn't completely fixed - thanks.

**Comment by tarzanek** [comment]
can you attach the file? I can try to repro again

**Comment by pmv** [comment]
It looks like it fails on javascript files that use 

```
//# sourceMappingURL=data:application/json;charset=utf8;base64,
```
with a really huge string following it.

An example is here: https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui.js

I'm attaching a zipped version:
[swagger-ui.zip](https://github.com/OpenGrok/OpenGrok/files/841839/swagger-ui.zip)

**Comment by tarzanek** [comment]
ok, I will need to add some tests, since this is breaking again, reopening, thanks for report @pmv

**Comment by tarzanek** [comment]
fwiw I have a working fix in https://github.com/tarzanek/OpenGrok with tests
I will merge once I have mvn build system patched, so travis builds will work too

**Comment by tarzanek** [comment]
closing, since I merged the fix now, mvn and ant are now testing so we don't regress on this issue

thank you @pmv !
