### ISSUE TITLE
OpenGrok home page not refreshing when index updated

### ISSUE THREAD

**Issue by cosmoJFH** [OpenGrok/OpenGrok#1175]
Every time I re-index the source files, I have to restart my tomcat server in order to display the later date when the indexes where created. Is this an issue related to Opengrok? Is any way to refresh the Opengrok home page in order to show the correct date without restarting the tomcat server?

**Comment by yschandra** [comment]
Yes with 0.13-rc2 I have same issue.

**Comment by tulinkry** [comment]
Couple of observations:

1. The timestamp **only changes** if there was a real change (fileAdd, fileRemove in the logs)
2. In the data directory (directory with your index) there is a file called `timestamp` which reflects the last successful indexer run. Does this file change its last modified time after you reindex?

3. If yes, do you see something like this in logs, indicating that there was no error in sending configuration to the webapp?
 ```
Aug 29, 2016 4:19:27 PM org.opensolaris.opengrok.index.Indexer sendToConfigHost
INFO: Send configuration to: localhost:2424
Aug 29, 2016 4:19:27 PM org.opensolaris.opengrok.index.Indexer sendToConfigHost
INFO: Configuration update routine done, check log output for errors
```
4. If yes, do you see something like this in logs of the webapp, indicating that there was no error in receiving configuration from the indexer?

  ```
29-Aug-2016 16:19:27.053 INFO [conigurationListener] org.opensolaris.opengrok.configuration.RuntimeEnvironment$6.run Configuration updated: /var/opengrok/src
```
5. If yes, if you run the re-index couple of times in a row (two times at least), does it change?

The workflow of the timestamp is somewhat following:

1. IndexDatabase updates its project = traverses and searches for the new/deleted files
2. If such file is found it marks the project `dirty`
3. After all if projects is marked `dirty` it updates the `timestamp` file
4. After all of all the new configuration (projects etc) is sent to webapp and the webapp is informed
that the reindex was made and so it should again read the `timestamp` file (**this part is crucial**)

After my investigation, there is a buggy behaviour around the dirty file, but the whole process should be ok when you run it multiple times. I can't make magic with the information you've provided. Does it solve the problem? Which step is failing?

**Comment by cosmoJFH** [comment]
The file timestamp is located on the correct directory, but it is empty. Is this correct?

**Comment by tulinkry** [comment]
It should be empty, the current timestamp is located in the file metadata not in the content. You can get it by looking at the properties of the file - (in most OS it's right click with the mouse on the file and then choose properties) - the last modified date value.

**Comment by cosmoJFH** [comment]
Do you mean the meta data obtained by the (linux) command  

ls -lisan timestamp

for example?

Is this is correct, in my case then, the date when this file was "touched" (obtained making use of the ls command)  does not correspond to the date displayed by Opengrok website.

**Comment by cosmoJFH** [comment]
I have indexed the repo. It was updated with new files. The timestamp file changed its date (meta-data), but the website does not display the correct date. I cleaned the cache of the browser, but it did not solve this issue.

I have also checked the log file catalina.out:

```
05-Sep-2016 08:27:33.157 INFO [conigurationListener] org.opensolaris.opengrok.configuration.RuntimeEnvironment$6.run Configuration updated: /svn-search/src_opengrok/DPAC
```

**Comment by tarzanek** [comment]
in browser try: Ctrl+Shift+R ?
if it will work, it means we need to revisit/check how we cache pages ...
(what browser is used?)

**Comment by cosmoJFH** [comment]
We have checked that the issue was related with the proxy. Sorry for our mistake.

**Comment by tarzanek** [comment]
just to close the loop on @yschandra - I filed #1184 to track the problem you see and marked it a stopper
