### ISSUE TITLE
NullPointerException when accessing /source

### ISSUE THREAD

**Issue by chetanpatil1984** [OpenGrok/OpenGrok#1177]
opengrok-0.13-rc2

startup.sh  -- started tomcat

setenv OPENGROK_TOMCAT_BASE /path/to/apache-tomcat-7.0.69 
./OpenGrok deploy

http://localhost:8080/source/

HTTP Status 500 - 

type Exception report

message

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.NullPointerException
    java.lang.String.startsWith(String.java:1405)
    java.lang.String.startsWith(String.java:1434)
    org.opensolaris.opengrok.configuration.RuntimeEnvironment.getPathRelativeToSourceRoot(RuntimeEnvironment.java:312)
    org.opensolaris.opengrok.configuration.Project.getProject(Project.java:197)
    org.opensolaris.opengrok.web.PageConfig.getProject(PageConfig.java:691)
    org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:54)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.69 logs.

**Comment by tulinkry** [comment]
This error means perhaps that there is no main configuration (default `/var/opengrok/etc/configuration.xml`). Did you run the index process?
```
$ mkdir -p /var/opengrok/etc && mkdir -p /var/opengrok/data && mkdir -p /var/opengrok/src
$ ./Opengrok index
```

However that will catapult you to the point that 0.13 can only run with java8 + tomcat8. After you get tomcat8, repeat the process (index + deploy) and the webapp should work.

**Comment by tarzanek** [comment]
@tulinkry anyways we should sanitize NPEs so 
 org.opensolaris.opengrok.configuration.RuntimeEnvironment.getPathRelativeToSourceRoot(RuntimeEnvironment.java:312)
should be ready to detect null and act upon ...
care to open a pull req @chetanpatil1984 or @tulinkry ?

tia
L

**Comment by tulinkry** [comment]
I believe that this is solved in the latest master by visualizing the problem on the screen

![screenshot from 2017-03-27 13-40-24](https://cloud.githubusercontent.com/assets/6997160/24354668/0c7d285a-12f3-11e7-91cd-c1372b12c402.png)
