### ISSUE TITLE
project list doesn't get updated upon new sync

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1184]
Index source dir with 2 projects
start the webapp
add another project to source dir, reindex, webapp recieves the config, but even forced refresh won't show new project list

I think this is a regression of #1161
Krystof, can you take a look please?

**Comment by tulinkry** [comment]
It's not definitely cause by #1161 since that is just a js playground on top of the html. What is not in html cannot be present in the js selectbox.

This was introduced in #1029 as a result of caching the projects and groups.
