### ISSUE TITLE
signal to the webapp once partial reindex is done

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1187]
Once the configuration listener protocol is extended so that allows more than just Configuration object to be passed, the protocol should be further extended so that partial reindex notifies the webapp to call maybeRefresh() on **specific** SearcherManager objects. This is a follow-up to the changes for #1132.

**Comment by tarzanek** [comment]
@tulinkry I think you have this ready with your messaging addition to listener, no ?

**Comment by tulinkry** [comment]
Yes. This is on the way

**Comment by vladak** [comment]
Also, with this change it would be good to relax the `IndexRefreshPeriod` which is currently set to 1 minute so every minute the webapp tries to reopen the indexes which causes syscall and I/O churn.
