### ISSUE TITLE
provide webapp statistics

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1204]
It would be nice to have overall view of what the webapp does and how it performs, namely:
- total number of requests handled (broken down into categories like successful/empty searches, history views etc.)
- cadence of the requests (e.g. how many per minute - avg/min/max)
- time to satisfy a request (both average and min/max - to see the outliers)

It would suffice if one can get these numbers by sending special message to the webapp.

**Comment by tarzanek** [comment]
special message + custom password, so we won't help the dos attackers see how they are doing ...

**Comment by vladak** [comment]
It would be sufficient to implement this as a web service which would provide some parseable (JSON) output.

**Comment by vladak** [comment]
Or alternatively, use the webapp listener channel.
