### ISSUE TITLE
Warning: Language "pascal" already defined

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1205]
When indexing with current master and Universal ctags I get bunch of these warnings:

```
14:29:02 WARNING: Error from ctags: ctags: Warning: Language "pascal" already defined
```

I assume this is related to the changes for #929, possibly Pascal handling needs to be Universal ctags aware.

**Comment by tulinkry** [comment]
Isn't this also relatet to #1137 ?

**Comment by tarzanek** [comment]
yes they are the same principle ... we override the analyzers from ctags since ours are better ...

**Comment by tarzanek** [comment]
why is this a stopper?

**Comment by tarzanek** [comment]
also this is a dup of #1137, closing
