### ISSUE TITLE
the tablesorter fails when the size of a file contains ","

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1221]
Sometimes the "," is used as a delimiter between thousands. So for every file where the `size is >= 1000 and <= 1023` regardless the concrete units the tablesorter fails taking with him also all the other javascript beauty we have.

**Comment by vladak** [comment]
Marking as stopper since 0.13 has bunch of JS goodness.

**Comment by vladak** [comment]
Incidentally, some thought should be given as to whether it would be feasible to test these JS pieces in our Junit tests.

**Comment by vladak** [comment]
The JS testing with JUnit seems possible: http://benjiweber.co.uk/blog/2013/01/27/javascript-tests-with-junit/
