### ISSUE TITLE
White space prefix remain after line numbers are turned off

### ISSUE THREAD

**Issue by Hlipa** [OpenGrok/OpenGrok#1224]
When I switch of line prefix, white space delimiter which was between line num and code remains which complicate copy out of code.

**Comment by vladak** [comment]
Caused by the changes for #540.

**Comment by tulinkry** [comment]
Not really. The space from the mentioned changes is directly in the line number so it's hidden as well.

It's this element, added in #916 
https://github.com/OpenGrok/OpenGrok/pull/916/files#diff-35d4074d8ca111eb8a6a3b8b1f7cb402R431
