### ISSUE TITLE
Messages script missing from release build

### ISSUE THREAD

**Issue by algestam** [OpenGrok/OpenGrok#1225]
I just downloaded the latest release candidate and would like to try out the new messaging functionality.

Walked into a problem since I'm running the release build and the new Messages script (`tools/Messages`) is not included in the release build (`opengrok-0.13-rc3.tar.gz`). It would be nice if it was copied over to the `bin` folder.

**Comment by vladak** [comment]
Actually, the `Group` script is missing too.
