### ISSUE TITLE
The new homepage is less readable

### ISSUE THREAD

**Issue by nerakhon** [OpenGrok/OpenGrok#1226]
Several issues:

A) The new homepage design uses too large fonts for the sections.

B) Also some default expansions of short sections would IMO make sense.
For sections with 1-3/4 children it is a waste of time to have to go and expand.

C) The show all button is in contrary very small and "hurts eyes"

D) For expansion everywhere else we use + sign shouldn't we use the same on homepage?

Including screenshot with marked issues

![screen shot 2016-10-11 at 15 28 00](https://cloud.githubusercontent.com/assets/376883/19272183/e1d4498e-8fc7-11e6-9d16-db0f26ad93cd.png)

**Comment by nerakhon** [comment]
E) The home page is incorrectly aligned as well the top starts right on the left margin, the sections seem to be centered.

F) Overall the font sizes aren't really harmonized and could use some help, good example is the search field for picking project.

![screen shot 2016-10-11 at 15 37 19](https://cloud.githubusercontent.com/assets/376883/19272366/9da4c828-8fc8-11e6-95e3-a7ef63e14d0c.png)

**Comment by tulinkry** [comment]
Closed by #1252
