### ISSUE TITLE
configuration.xml issues with 0.13-rc3

### ISSUE THREAD

**Issue by pecastro** [OpenGrok/OpenGrok#1231]
Configuration file is not being written 

`root@687749f512d0:/opengrok/bin# echo $OPENGROK_INSTANCE_BASE
/grok
root@687749f512d0:/opengrok/bin# ls -altr /grok/etc/
total 0
drwxr-xr-x 4 root root 29 Oct 12 19:39 ..
drwxr-xr-x 2 root root  6 Oct 12 19:39 .
root@687749f512d0:/opengrok/bin# ./OpenGrok deploy
Loading the default instance configuration ...
Installing /opengrok/bin/../lib/source.war to /var/lib/tomcat8/webapps ...

Start your application server (Tomcat),  if it is not already
running, or wait until it loads the just installed web  application.

OpenGrok should be available on <HOST>:<PORT>/source
  where HOST and PORT are configured in Tomcat.

root@687749f512d0:/opengrok/bin# ls -altr /grok/etc/
total 0
drwxr-xr-x 4 root root 29 Oct 12 19:39 ..
drwxr-xr-x 2 root root  6 Oct 12 19:39 .
`

Which then leads to 

`Oct 12, 2016 8:38:24 PM org.opensolaris.opengrok.web.WebappListener contextInitialized
WARNING: OpenGrok Configuration error. Failed to read config file: 
java.io.FileNotFoundException: /var/opengrok/etc/configuration.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
`

**Comment by vladak** [comment]
There are 2 issues here:
  - the `configuration.xml` file is generated upon reindex which did not seem to happen yet as the `etc` directory is empty.
  - if OpenGrok is hosted elsewhere than default location, it needs to be reflected in `CONFIGURATION` parameter in the `webapps/source/WEB-INF/web.xml` file under Tomcat.

Both seem like configuration issues to me, hence closing.
