### ISSUE TITLE
0.13-rc3: Double click on a project from “In Project(s)” will redirect to wrong url and cause Error: File not found!

### ISSUE THREAD

**Issue by amotzte** [OpenGrok/OpenGrok#1241]
When pressing on project “projectname”
Expected: page will redirect to /source/xref/projectname
Observed: page redirects to /source/undefined/projectname which shows “error File not found!”

Also if there is a message for that project (use the new Messages feature) it will append a “!”  to the end of the url which will also redirect to “error File not found!” if xref will be fixed

It seems to be related to a cookie named "OpenGrokProject" somehow. If this cookie is deleted the  problem is not seen (until pressing again on the project which recreating the cookie again)

**Comment by vladak** [comment]
Defn'tly a regression, thus marking as stopper.

**Comment by amotzte** [comment]
Thanks!

**Comment by amotzte** [comment]
@tarzanek  it seems that there is still an issue when double click on a project that has a Message on it:
**Reproduce** 
Add a Message to some project
Double click on the project in the "In Project(s)" window 
**Expected** 
Redirect to source/xref/\<project\>
**Observed**
Redirect to source/xref/\<project\>**!** which causes _"Error: File not found!"_

**Comment by tarzanek** [comment]
@amotzte can you repaste this into new issue please?
We'll try to look at it ... tia
L
