### ISSUE TITLE
OpenGrok indexpart "Error getting source root from environment. Exiting."

### ISSUE THREAD

**Issue by kd7mrx** [OpenGrok/OpenGrok#1246]
Running "OpenGrok indexpart" without specifying a readonly config fails with the message "Error getting source root from environment. Exiting."  I note the response in #975  "It is necessary to run the indexpart with readonly config which contains both src and data root" but I don't understand the reason for this requirement and don't see any mention of it in the documentation.

I see that UpdateGeneratedData uses StdInvocation while UpdateDataPartial uses CommonInvocation.  Is there some reason to not add the "-s ${SRC_ROOT}" and "-d ${DATA_ROOT}" options in UpdateDataPartial?  Or change UpdateDataPartial to use StdInvocation instead of CommonInvocation?

**Comment by vladak** [comment]
The prime reason for the configuration to be passed to partial reindex is that the `Indexer` needs to have the information about the project/repository. The source/data root can be induced from the environment as you say, at the risk of not being consistent with the configuration. Surely, the `indexpart` usage requiring source root does not make much sense.

**Comment by vladak** [comment]
A reason one might want to override source/data root would be a case of near-instant reindex however that would not work in the case of overriding source root given that RepositoryInfo objects contain full path (i.e. including source root). Thus, I will keep the function calls and will just fix the usage.
