### ISSUE TITLE
Clicking on a Git file-revision shows folders instead of the file contents

### ISSUE THREAD

**Issue by gulench** [OpenGrok/OpenGrok#1258]
I'm using `opengrok-0.13-rc4` and `git version 2.9.0.windows.1`. In the web application, clicking the revision of a file in the `GitRepository` shows folders instead of the file contents. Is this issue related to how `OpenGrok` uses the `Git` options, or how `Git` is configured?

```
File.cs revision e214d6ae
tree e214d6ae:

Folder1/
Folder2/
Folder3/
```

**Comment by vladak** [comment]
You mean if you click on revision link in history view ? (e.g. http://localhost:8080/source/xref/openssl/config?r=b33c5ffe) I can't reproduce this behavior on Solaris 11.3 with git 2.7.4 and OpenGrok rc4.

**Comment by gulench** [comment]
Yes, clicking the `revision` link in history view. I'm running this on `Windows Server 2012 R2`. I tried with `git version 2.7.4.windows.1`, but the problem persists.

**Comment by tulinkry** [comment]
Now I've got it. I believe this is connected to the fact that we don't support renamed files in git. See #1335 - maybe you see similar problem = no tooltip over the revision and when you click on it there's no file content, only some wierd directory listing.

Just to be sure, when you run the `git log` command on that file, does it find the revision or not? Most likely your file was renamed/moved in the project and this revision belongs to the previous name. We currently don't track this in OpenGrok. Hopefully we'll be doing that soon...however git has (as opposed to mercurial) very poor renamed files tracking.

**Comment by tulinkry** [comment]
@gulench I hope this is fixed for you in the rc8
