### ISSUE TITLE
Please say something better than "Your search defs:FOOBAR did not match any files" when indexing is in progress

### ISSUE THREAD

**Issue by SteveChessin** [OpenGrok/OpenGrok#1264]
I was examining a file in OpenGrok and clicked on a word (let's call it FOOBAR) and got the result "Your search defs:FOOBAR did not match any files". I asked my local OpenGrok expert and he told me it was because "The indexing is still in progress".

It would be nice if in that case OpenGrok returned something like "indexing in
progress; XX% complete, try again in YY [hours|minutes|seconds]" or some
similarly useful message, instead of the unhelpful "did not match any
files". The message it does return is especially frustrating since I can
see that FOOBAR is indeed in the file I was just viewing.

**Comment by tulinkry** [comment]
Display custom messages about index, reindex is available with #1195. Documented on [wiki page](https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-Messages).

It's not in the `OpenGrok` script yet however you can run it before the index to add the message and after the index to delete the message.

**Comment by vladak** [comment]
It is up to the deployment to provide the messaging when reindex is in progress.

**Comment by vladak** [comment]
Eventually the updating and reindexing could be done by OpenGrok itself, as laid out in #944 which would limit the inconsistency window to minimum.
