### ISSUE TITLE
Line numbers in Java code not correctly aligned on left side

### ISSUE THREAD

**Issue by kosi2801** [OpenGrok/OpenGrok#1266]
I did an update today to Git tip (to commit b35d7ab54421abe1070f582e558134b68557175c) and when viewing Java source in Firefox the line numbers seem to be scattered in the middle of the source.

See screenshot:
![screenshot - 03 11 2016 16_32_30](https://cloud.githubusercontent.com/assets/1632470/19972849/a5f5df6c-a1e3-11e6-9637-c312018791d7.png)

**Comment by tulinkry** [comment]
Did you indexed your code base from scratch? Because changes in #1256 need full reindex.

**Comment by kosi2801** [comment]
No, will try immediately. Thanks for the hint.

**Comment by kosi2801** [comment]
A complete reindex fixed this, thanks!
Btw.: Is there a better way for complete reindex than manually deleting "data/index" and "./OpenGrok index"?

**Comment by tulinkry** [comment]
I always use this. Maybe @tarzanek knows better?

**Comment by tarzanek** [comment]
nope, that is the only way ...
it would be cool if we had index versioning and  upgrader ...

**Comment by kosi2801** [comment]
Ok, so I'm at least doing the same as everybody else :)
The main issue is fixed for me, closing.
