### ISSUE TITLE
[Wish-list] Can't cooperative with many famous chrome plugins for taking sticky notes on code pages

### ISSUE THREAD

**Issue by skywind3000** [OpenGrok/OpenGrok#1288]
I want to use some chrome plugins like: [Note Anywhere](https://chrome.google.com/webstore/detail/note-anywhere/bohahkiiknkelflnjjlipnaeapefmjbh) and 
[Web page sticky notes](https://chrome.google.com/webstore/detail/web-page-sticky-notes/alpjieidnmmkljnceakgpeajlngabnee) to recording my thoughts when I am reading codes in opengrok:

But the sticky notes can not synchronize with the code pages (they should be) when I am scrolling code window down.

I have tried more than 10+ different note-on-web-pages plugins in chrome. The notes can truely stick to the origin position on one web page, when I scroll around.

They works very well on any other web sites, except the code pages generated by OpenGrok.

Can OpenGrok generate some sticky note friendly pages in the feature version ??  I want not only read the code, but also take some notes right in the code. Previously, I was using vim with cscope, I could write notes by directly adding comments to the current file in vim. Now I switch to the great project because I want to read code on my iPad. But I found I can just read in OpenGrok and can not record my thoughts right on the code, when I am reading.

After installing some famous chrome note plugins, I sadly found OpenGrok just can't cooperative with them (synchronizing issues):

![stickynote](https://cloud.githubusercontent.com/assets/3035071/20496521/7f294b9a-b060-11e6-85b7-1408c6aa81f0.png)

Could you please tell me a way I can take notes on the code with OpenGrok ?

**Comment by tarzanek** [comment]
just quick Q - what version was that? 0.13 RCx or 0.12 ?

**Comment by skywind3000** [comment]
0.12

**Comment by tulinkry** [comment]
I believe it's because the `#content` in OpenGrok is positioned as fixed - which (not only) means that the container itself doesn't move from its position on the monitor, only the content inside is scrolled. In other words the page doesn't scroll (so the sticky notes don't), only the content in some element `#content` scrolls.

**Comment by skywind3000** [comment]
but many sites with a fixed header + scroll-able body (just like OpenGrok) supports sticky nots.

**Comment by tulinkry** [comment]
The problem is that OpenGrok has it the other way around. The header is not fixed, neither the body, only the `#content` is fixed and that's the problem. I don't know why OpenGrok uses this template. If the template was like you mentioned it'd be ok. I'm not sure if I can do this in the next release.

**Comment by skywind3000** [comment]
Page structure of [Quora](https://www.quora.com/) is similar to OpenGrok, both of them have a fixed header + scroll-able body.

[Note Anywhere](https://chrome.google.com/webstore/detail/note-anywhere/bohahkiiknkelflnjjlipnaeapefmjbh) works correctly with Quora but not with OpenGrok.

It seams strange.

And one more thing, scrolling source pages of OpenGrok in an iPad with finger is **very hard**.
The most advantage of OpenGrok is that I can reading in my iPad.
Can scrolling with iPad be as smooth as Quora ??

**Comment by skywind3000** [comment]
thanks

**Comment by tarzanek** [comment]
@skywind3000 can you please test the fix?

**Comment by skywind3000** [comment]
OK I will feed you back if I encounter any issue.
