### ISSUE TITLE
Cleanup the project data when the whole project is removed

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1307]
When I delete the entire project and reindex, the project list gets updated however the timestamp doesn't. I guess it's because when a project is deleted then there's no actual `fileDelete()` call and that's the way how to update the timestamp. The indexer should remove the remove project data files.

I know it's not something which happens so often but it should be consistent.

**Comment by vladak** [comment]
If you mean the indexed timestamp at the bottom of the UI page then this should be treated in special way after #1390 integrates.

As for the removal, #1390 deals with the data removal in the `project delete` message. For individual files, this will be done in #767.

**Comment by vladak** [comment]
Closing as dup of #1390. With tools for project centric approach it does not make sense to implement this. If anyone feels otherwise, feel free to reopen (with pull request :-)).
