### ISSUE TITLE
something wrong with git log

### ISSUE THREAD

**Issue by warjiang** [OpenGrok/OpenGrok#1310]
when i use OpenGrok to generate index ,something woring happened.
![image](https://cloud.githubusercontent.com/assets/6478745/21582277/a7d8c58e-d08b-11e6-9a3e-360761d5997c.png)

**Comment by tulinkry** [comment]
This doesn't harm anything. It's trying to get the value which is displayed on the main page in the "Current version" column, you probably get "N/A" in that column.

Try to read [this comment](https://github.com/OpenGrok/OpenGrok/pull/1262#commitcomment-20273958) which may solve the problem.

**Comment by warjiang** [comment]
:thumbsup: version of current git is 1.9.1. When i try to upgrade git to 2.11.0 and execute the generating index script，no warning.Thanks!

**Comment by tulinkry** [comment]
This is now fixed in upstream with #1314. It should support git < 2.6
