### ISSUE TITLE
trying to run some test cases results in compilation error in ConditionalRunRule.java

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1327]
When I try to run some focused test methods (e.g. `parseAnnotations()` in `GitRepositoryTest.java`) in Netbeans, the compilation fails with:

```
Compiling 1 source file to /workspaces/opengrok-git-vladak/build/test/classes
/workspaces/opengrok-git-vladak/test/org/opensolaris/opengrok/condition/ConditionalRunRule.java:147: error: method assumeTrue in class Assume cannot be applied to given types;
            Assume.assumeTrue("Ignored by " + condition.getClass().getSimpleName(), false);
  required: boolean
  found: String,boolean
  reason: actual and formal argument lists differ in length
1 error
```

**Comment by tulinkry** [comment]
This overloaded method has been in junit since 2012:
https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/Assume.java#L60-L69

I have no idea what's causing this.

**Comment by vladak** [comment]
This only happens in 'Debug Focused Test Method' in Netbeans, i.e. not when 'Run Focused Test Method'.

**Comment by tarzanek** [comment]
works for me ... Debian stable, jdk 1.8 from Oracle set in netbeans.conf and NB 8.2 ....

**Comment by vladak** [comment]
Seems to be a problem with NB 8.0.2 or JUnit, no longer happens with NB 8.2, hence closing.
