### ISSUE TITLE
seeing lots of warning messages  for unknown date format with older Git

### ISSUE THREAD

**Issue by ilovemaui** [OpenGrok/OpenGrok#1331]
If anyone knows if this is a bug in the current version of opengrok - 0.13-rc5, or possibly a configuration issue, but I have been seeing thousands of these warning messages in my index output..
WARNING: Failed to determineCurrentVersion for /myopengrok/mydir java.io.IOException: fatal: unknown date format format:%Y-%m-%d %H:%M

if anyone can shed light on this. This is running with jdk1.8.0_72, universal-ctags, and opengrok-0.13-rc5

**Comment by vladak** [comment]
What SCM is this ?

**Comment by vladak** [comment]
Assuming this is Git, you are likely running version older than 2.6 and might be therefore missing the fix in cset bdb4975bfcb985c251f6bdf6f3ec95d8487edc06 which is not in 0.13-rc5.

**Comment by ilovemaui** [comment]
we are grabbing the source with an older version of git - 1.7.12.3 
I think we do have a newer version 2.10.1 - if we switch to this newer version, will this problem go away? and to use this new version, do I have to reclone all of my repos using the new version?

**Comment by vladak** [comment]
Switching to git newer than 2.6 should fix the problem I believe however I am not sure if this involves repo upgrade. Instead you can give https://github.com/OpenGrok/OpenGrok/releases/tag/0.13.rc6 a try.

**Comment by ilovemaui** [comment]
ok. let me try new version 1st of opengrok. thx.

**Comment by tulinkry** [comment]
Use any of the grok revisions after the mentioned commit (so for example rc6). The problem should be solved with that commit

**Comment by tulinkry** [comment]
No further reaction and the solution was proposed so closing.

**Comment by jvaneck** [comment]
FYI - I'm getting this error again using opengrok 1.1 rc61 and git version 1.7.1       (I'm not sure if it matters or not because the version of git I'm using is so old)



2018-10-25 13:59:03.511  WARNING [org.opengrok.indexer.history] - Failed to determineCurrentVersion for /mygitrepo: java.io.IOException: fatal: unknown date format iso8601-strict

**Comment by tulinkry** [comment]
Yes, it matters. The iso8601-strict is available in higher versions of git only.

**Comment by vladak** [comment]
Sure, go ahead, the wikis are open to edit for everyone.

Dne pá 26. 10. 2018 15:24 uživatel Jake VanEck <notifications@github.com>
napsal:
