### ISSUE TITLE
bad folding in xref view

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1332]
Recent head exhibits this folding corruption:

![badindent](https://cloud.githubusercontent.com/assets/2934284/22063245/123bcc1a-dd7e-11e6-943f-c1cebb821cf1.png)

**Comment by vladak** [comment]
seen with FF 45.4.0

**Comment by tulinkry** [comment]
Even after full reindex?

**Comment by vladak** [comment]
Ah, forgot about this was fixed, full reindex works.
