### ISSUE TITLE
Annotate partially fails with git for renamed/moved files

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1335]
Steps to reproduce:

```bash
$ git init
$ touch main.c
$ nano main.c # - add some lines
$ git commit
$ mkdir moved
$ mv main.c moved/
$ git commit
$ nano moved/main.c # - change/add some other lines
$ git commit
```

Now index and navigate to the file annotation. The old revisions aren't colored (but they should be since last 10 revisions get their color). The tooltip is empty.

On the picture the revisions on the top are the old ones (before moving), the second revisions are the one after the move:
![screenshot from 2017-01-20 12-48-05](https://cloud.githubusercontent.com/assets/6997160/22148499/bc46f496-df0e-11e6-940f-3ae3f7dc49dd.png)

**Comment by tulinkry** [comment]
For me it looks ok to add `--follow` for git log for getting history which follows all of the renames and then it knows about these old revisions.

**Comment by vladak** [comment]
It's a question what would be the side effects of adding the `--follow` flag, especially given that #794 is not implemented yet. I.e. what will happen if 2 revisions will be compared in diff view, where each was done with the same file having different names.

**Comment by vladak** [comment]
Technically this is a bug however it depends on enhancement.
