### ISSUE TITLE
Login on Apache ldaps based authetication

### ISSUE THREAD

**Issue by PawanKulkarniS** [OpenGrok/OpenGrok#1344]
we are using Opengork 0.13.rc1 with apache-2.2.23 , apache-tomcat-7.0.29 with LDAP Authentication.
we have seen that when were using Opengrok via Apache's mod_auth_ldap  ( ldaps:// ) , authenticating against a UNIX based OpenLDAP instance , we see that Login  ( < 1sec ) & even the large opengrok queries happen within 1 or 2 minutes. 

ldap group had close to 2000 users against whom we checked for user membership

We moved this setup to do LDAP authentication against the Corporate AD servers ( with CA certs ) , we see now that there is a huge login time ( 25~36 Seconds ) and query time now varies in multiple minutes to a range from 2~4 minutes.

Can you please provide us some insight as how we can improve both Login aswell as query times, please suggest changes to configuration...

**Comment by vladak** [comment]
How big/diverse is your index ? How long does a query take in general without authentication ? Is this apparent for all query types ? (definitions/full search/etc.)

I'd suggest to use the latest release candidates that have support for statistics, you can get more data about the performance that way (see https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-Messages#types)

**Comment by vladak** [comment]
As for speeding up queries, some ideas are being thrown around in #1116 , e.g. try to keep the dataset (i.e. index) in RAM with tools like `vmtouch`.

**Comment by vladak** [comment]
Looks like the communication stopped, hence closing. Feel free to reopen.
