### ISSUE TITLE
new OpenGrok - 0.13-rc7 seems really slow scrolling with large files

### ISSUE THREAD

**Issue by ilovemaui** [OpenGrok/OpenGrok#1358]
when searching a large file, eg. >10K lines, the scrolling is very very slow. If I turn off line#'s it improves quite a bit, but is this a bug in the new release? can this be fixed?

**Comment by tulinkry** [comment]
Try this pr #1349 which is in current head (and rc8). It should speed up drastically. Tell me if it doesn't. The actual patch is quite easy so you can try it without updating to rc8.

**Comment by ilovemaui** [comment]
do I have to do a full re-index?

**Comment by tulinkry** [comment]
Changes (from rc7) are:
- handling for renamed files in Git (requires reindex for git repositories)
- limit on token size (I believe that also no reindex is required)
- UI fixes (no reindex required)

**Comment by vladak** [comment]
No, this is a JS change, see cset 3c3a0f7e4cde5c6fb9dec9bcaf7edf8577c434c6

**Comment by ilovemaui** [comment]
ok. thanks.

**Comment by vladak** [comment]
Closing this now, feel free to reopen if the problem persists with 0.13-rc9+
