### ISSUE TITLE
footer displayed above page content for certain xrefs

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1360]
In 0.13-rc8 indexing file called foo.s with these contents:

```
/*
 *	 <- foo
 */
```

the page footer is placed above the contents:

![foo](https://cloud.githubusercontent.com/assets/2934284/22445721/0e981b98-e749-11e6-888e-79b687c4f78d.png)

This seems to be happening only with Universal ctags, not Exuberant ctags.

Notably, there is a folding icon on the line with `foo`. It seems that the arrow somehow triggers this behavior.

The badly placed footer is just a consequence of incorrectly formatted HTML it seems:

![html](https://cloud.githubusercontent.com/assets/2934284/22445791/61f10778-e749-11e6-8090-d6805fdf2bed.png)

**Comment by vladak** [comment]
This happens not only for files with the arrow but also other files, my theory is this happens for all files where ctags detects functions.

**Comment by tulinkry** [comment]
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/JFlexXref.java#L339-L343 Maybe?

**Comment by vladak** [comment]
Oh yes, I suspected bad scope termination.

**Comment by mrate** [comment]
I'll investigate it, feel free to assign this issue to me. It seems like a good candidate for a test suite file.

**Comment by vladak** [comment]
@mrate thanks. I fail to see the opening part of the `div` elemnt in the code.
