### ISSUE TITLE
"Help" button font size differs

### ISSUE THREAD

**Issue by jfriedel** [OpenGrok/OpenGrok#1362]
The "Help" button font size is different to the other two buttons on the main page.

![help-font](https://cloud.githubusercontent.com/assets/5879789/22463321/6017ba42-e7b1-11e6-8ec7-24ff0db2aa07.jpg)

**Comment by tulinkry** [comment]
No this is not fixed.

![screenshot from 2017-02-15 14-53-57](https://cloud.githubusercontent.com/assets/6997160/22977379/b9cb2da6-f38e-11e6-9b3d-2eb0e78cd64b.png)
![screenshot from 2017-02-15 14-54-32](https://cloud.githubusercontent.com/assets/6997160/22977380/b9d1e768-f38e-11e6-96b9-8ba68e66abcf.png)
