### ISSUE TITLE
Remove "last modified <date>" from the list of the files.

### ISSUE THREAD

**Issue by jfriedel** [OpenGrok/OpenGrok#1363]
Remove "last modified <date>" from the list of the files. It just destroys the readability (subjective) and has no other function (order by, etc.).

![remove_last_modified](https://cloud.githubusercontent.com/assets/5879789/22463635/eef10ec0-e7b2-11e6-8df7-25b5d70164ce.jpg)

**Comment by vladak** [comment]
Another option would be to present this information in a tooltip when passing over the file name link.

**Comment by vladak** [comment]
I agree that this is disturbing element, the UI should be minimalistic.

**Comment by vladak** [comment]
For the record this was added in cset 9ed9e4f8 for #590 based on my request :-)

**Comment by tulinkry** [comment]
And also it should be a tunable in `configuration.xml`. That was my first contribution and it's made as a parameter to the webapp in `web.xml` which is against our design.
