### ISSUE TITLE
autorefresh after project removal from the chosen set

### ISSUE THREAD

**Issue by jfriedel** [OpenGrok/OpenGrok#1369]
The main search page could auto-refresh (automatically resend the search request) when one
closes one from the chosen projects icons. Say, in the example below, when one closes the "openssl-1.0.0" button, the search should automatically refresh. The current behavior is that one has to click the "Search" button after the chosen project button is closed -- which seem rather superfluous (subjective).

![autorefresh](https://cloud.githubusercontent.com/assets/5879789/22465640/f6913812-e7bc-11e6-8750-433c3e3b3ded.jpg)

**Comment by tulinkry** [comment]
Doesn't feel good to me. I agree that it would be faster in some cases; but

1. searching is "quite slow" operation and if user wants to unclick several projects it could be annoying when the page refreshes everytime
2. personally it's counter-intuitive - clicking on something else than a submit button fires a submit event

**Comment by vladak** [comment]
I think we should assume that search is quick, at least Lucene promises that :-) That said, I am also torn whether to implement this or not. As for counter-intuitive, it's **kind of** similar to when you change filters in an e-shop - the list of goods is usually automatically refreshed.
