### ISSUE TITLE
move project selection list and buttons above the other search-text fields

### ISSUE THREAD

**Issue by jfriedel** [OpenGrok/OpenGrok#1370]
Please, consider moving the project list above the other search-text fields. I hope, this should provide a better navigation on narrower screens (tables, smart phones). Of course, the "In project(s)" and the buttons could be differently aligned.. Also, the chosen project buttons/icons could pop-up under the project selection-list (between the project selection-list and the "Full Search" text field).

![move_project_select](https://cloud.githubusercontent.com/assets/5879789/22466086/f3744c80-e7be-11e6-998c-3181819b249b.jpg)

**Comment by jfriedel** [comment]
It is apparently a dup of #1365.

**Comment by vladak** [comment]
No, it's not, #1365 is about the title of the page.

**Comment by vladak** [comment]
or move it below the 'Type'

**Comment by tulinkry** [comment]
On small screens the picker moves automatically bellow the search form

**Comment by vladak** [comment]
mockup:

![ui](https://cloud.githubusercontent.com/assets/2934284/23021768/f3fb2b6a-f44d-11e6-9cff-150522305bf1.png)

The 3 project selector buttons are the most troublesome aspect of this I think.

**Comment by jfriedel** [comment]
.. thats fine with me; just add a bit more space between the 3 buttons and the subsequent Full Search to visually divide the two (functionally) distinct section. And that is it. Nothing else needs to be on the minimalistic OpenGrok's front page.

**Comment by tulinkry** [comment]
This is my best so far

![screenshot from 2017-02-17 16-33-31](https://cloud.githubusercontent.com/assets/6997160/23071513/defba960-f52e-11e6-967d-9428c97e57f8.png)

**Comment by jfriedel** [comment]
IMHO, the search button and the respective fields (Full Search - History) are too far from each other. The usual use case is that the project is chosen once in a session and the searched items differ from search to search. With the suggested design one has to (needlessly) move with the mouse over the already set "In Projects" field to get to the search button..

Just my 2cetns.

**Comment by vladak** [comment]
Looks fine. Maybe I'd put the project search in a box.

**Comment by tulinkry** [comment]
> the search button and the respective fields

One can use enter to search immediately after writing however yes the distance is bigger.

I'm not sure if this is better. It might be. But I always see the concept of searching as "what to search" and then "where to search".

![screenshot from 2017-02-17 17-56-09](https://cloud.githubusercontent.com/assets/6997160/23074811/6876054a-f53a-11e6-8a70-5fde44947389.png)

**Comment by vladak** [comment]
Looks worse to me and I concur with the what-then-where concept.

**Comment by vladak** [comment]
Another thing that can visually separate the buttons would be to change colors of the project selector buttons.

**Comment by jfriedel** [comment]
Looks much better to me: from big (where) over smaller (what) to search.  In the earlier design the "Clear" button is bound to the "what" block (Full Search - History) -- which again, IMHO, suggests to stick the "Search" "Clear" and "Help" buttons together with the "what'' block (Full Search - History).
