### ISSUE TITLE
Usage of OPENGROK_WEBAPP_CONTEXT

### ISSUE THREAD

**Issue by TotoXe** [OpenGrok/OpenGrok#1378]
Hi,

In the OpenGrok script I can read:
    # OPTIONAL: Context URL of the OpenGrok webapp
    #           (default is /source)
    WEBAPP_CONTEXT=""
    if [ -n "${OPENGROK_WEBAPP_CONTEXT}" ]; then
        WEBAPP_CONTEXT="-w ${OPENGROK_WEBAPP_CONTEXT}"
    fi

The variable OPENGROK_WEBAPP_CONTEXT must be set to webapp context (_grok_ in my case) if I want to solve my current issue (links to defs are using _source_ instead of _grok_ since I indexed all my repos using default context...).

Do I need to set the value of the env variable to _grok_ or _**/**grok_ ?
Do I absolutely need to rm all my DATA dir ? Or can I just rm one of my (numerous) projects ($DATA_DIR/PROJ1/{index/xref/historycache}*) then use indexpart ? I tried and it seems not to work... 
So, last question. Does indexpart command use this webapp context ?

I am using OpenGrok 0.12.1.6, with Java 8 121, Tomcat 7.0.75, OS Linux Ubuntu.

Thanks for your help,
Christophe

**Comment by TotoXe** [comment]
Ok. Found this: https://github.com/OpenGrok/OpenGrok/issues/1038. It answers my first question. I must use: OPENGROK_WEBAPP_CONTEXT=grok

**Comment by TotoXe** [comment]
My answers to my questions :-)
I need to rm all the data to get a clean set of data. But partial reindexing of one project with new context would work for that project if I only rm the data of this particular project.
Yes, fortunately, indexpart is using webapp context!

I got no answer from you devs that work hard on this great application. What is your preferred way to ask questions ? Use of opengrok-users yahoo mailing list ?

Last note. Nice to have. I would suggest to update OpenGrok script. _Usage_ function. line 110: _echo "       ${progname} indexpart <src_root> <directory1> [..]"_  I was not able to define several repos to partially index as suggested by _<directory1> [...]_. And this is confirmed by line 1091: _if [ $# -ne 3 ]_ Only 3 arguments allowed.

**Comment by tulinkry** [comment]
This is the preferred way and we are sorry that you wasn't hearing anything from us. We are quite busy working on the release. Suggestion noted.
