### ISSUE TITLE
project picker enhancements

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1380]
The project picker window says 'Click here to search' which is not precise. It should be something like 'Click here to select project(s)'.

Also, it would be nice if the project picker could select whole groups of projects by using single click rather than double click.

 - [x] changing the label
 - [ ] changing the click

**Comment by tulinkry** [comment]
Label implemeneted in cset c26ef0d

**Comment by tulinkry** [comment]
Click implemented in 857d571
