### ISSUE TITLE
Empty project groups should be hidden

### ISSUE THREAD

**Issue by jfriedel** [OpenGrok/OpenGrok#1389]
On the OpenGrok front page, the empty project groups should be hidden (by default).
![hide_empty_groups](https://cloud.githubusercontent.com/assets/5879789/22695754/1e4704c4-ed4c-11e6-80f4-0985a5c524a7.jpg)

**Comment by jfriedel** [comment]
I'm OK with the changes (already integrated) collapsing by default the project groups. Closing this Enhancement Request.

**Comment by tulinkry** [comment]
I was wondering because we didn't change anything :D. I looked on our local deployment and the group collapse with threshold 4. This still needs to be fixed to hide empty groups.
