### ISSUE TITLE
Is there a major change in generating the git history from 13-rc4  to 13-rc7  - peformance drawback?

### ISSUE THREAD

**Issue by shauenstein-91056** [OpenGrok/OpenGrok#1402]
Hi,
I have upgraded from version 13-rc4 to 13-rc7 and facing major performance issues when generating with -H the history cache.
To me it looks like that with the latest version the history cache is not created on demand, but while indexing. This makes my project awkfull slow.

Is there a way to switch of the history cache generation, but still have the option at the tomcat gui?

**Comment by vladak** [comment]
This is surely related to #1345

**Comment by tulinkry** [comment]
See [this comment](https://github.com/OpenGrok/OpenGrok/issues/1395#issuecomment-279408378) and how to turn off the renamed files handling. That is surely the case.

**Comment by vladak** [comment]
Use the `OPENGROK_GENERATE_HISTORY=uionly` setting in the `OpenGrok` shell script. That way the history for individual files will be generated on demand in the webapp. However, the history will not be indexed, i.e. cannot be searched.
