### ISSUE TITLE
Messages -n abort should not require text

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1403]
`/usr/opengrok/bin/Messages -n abort -t foo` exits with error:

```
The text of the message must be specified
```

This does not make sense to me since there is text to be deleted.

**Comment by tulinkry** [comment]
I know that this could be solved with simple if statement. However the original design was to be independent on the exact message type and therefore I decided to keep the text required. Perhaps we could make it optional for all messages and act upon in the specific message?

**Comment by vladak** [comment]
I'd make text optional.
