### ISSUE TITLE
rename description to name in Project

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1428]
as commented in `Project.java`:

```
    // this variable is very important, since it's used as the project identifier
    // all over xrefs and webapp
    // jel: and yes - awefully misleading. It should be called 'name'!
    private String description;
```

**Comment by tulinkry** [comment]
Also it could be useful to introduce an interface with getName and put Project and Group all together with that Interface. As far as I remember that would make stuff much easier for coding
