### ISSUE TITLE
Accurev Workspace Update Enhancement

### ISSUE THREAD

**Issue by ozankiraz** [OpenGrok/OpenGrok#1441]
I was thinking about implementing automatic update of workspaces for Accurev,
This functionality exists for some other SCM's, and it can be implemented for Accurev easily

@vladak , Please mark this as Enhancement, I'll check how other repository update functionality works, then I'll implement it for accurev ( I believe it's fairly easy),
Actually I haven't figured out when repository update is done. before indexing?

Some notes related to accurev command line :
http://www.it-recipes.com/articles/blog/22

**Comment by tulinkry** [comment]
This automatic update may be implemented in the application for some repositories however it's never used. It's currently always up to the end user to sync the actual code with its remote.

This full automatic approach is subject for next releases.

**Comment by ozankiraz** [comment]
Some notes about accurev update enhancement :
Accurev command to update a repository "accurev update"

Output will be one of the following (Just in case someone needs it)

1- When there are update(s)

Update started
Scanning entire workspace for files touched since last scan - ok
Calculating changes - ok
Making 1 change
Content (36 K) of "CHANGES.txt" - ok
Update complete.

2- When there is nothing to update

Update started
Scanning entire workspace for files touched since last scan - ok
Calculating changes - ok
Already up to date. Nothing to do.

Working directory for command executor can be set as any directory under repository top level directory.

Related PR : #1444
