### ISSUE TITLE
0.13 Projects list second column not aligned properly

### ISSUE THREAD

**Issue by kosi2801** [OpenGrok/OpenGrok#1442]
With latest master 0.13 (as of 2017-02-22 08:30 UTC) there is a strange vertical "stair" effect in the second column of the project list.
It seems as if the second column is shifted right further and further for each project/group.

![screenshot - 22 02 2017 09_27_49](https://cloud.githubusercontent.com/assets/1632470/23203296/42fbce70-f8e2-11e6-98bc-cd0cfe7fd4cb.png)

**Comment by tulinkry** [comment]
Can't reproduce here.

If you try clearing the browsers cache does it solve the problem? If you do a hard reload of the page (ctrl+shift+R) does the problem persist?

There is no limitation on width for the first column (and second) so your browser adapts the column for itself.

You could try investigating a little bit further:
1. is there anything special in the html? (there should be only <td class="name (sub)repository">)
2. if you set a property for `.repository`:
    ```css
    .repository {
        width: 0;
        white-space: nowrap;
    }
    ```
    and observe how the columns appear (they should be long as the longest text inside)

Both above you can try in browser console (FF ctrl+shift+K, On Chrome you can find it somewhere between the tools for developers)

**Comment by kosi2801** [comment]
Clearing the browser cache does not change anything. I tried also on
different machines and in FF and Chrome, it's the same appearance
everywhere.
I also did no customization in the HTML/snippets.

If I apply your CSS snipped to the FF Style Editor, the first column
collapses to the longest entry for each project and the second column now
starts right after it (no "visual stacking").

I will try to save the page and post it into here for further analysis,
just have to remove all confidental information.

On Wed, Feb 22, 2017 at 12:34 PM, Kryštof Tulinger <notifications@github.com

**Comment by kosi2801** [comment]
Screenshot of search page with CSS for .repository applied
![screenshot - 22 02 2017 14_17_42](https://cloud.githubusercontent.com/assets/1632470/23213158/1c9d05fa-f90a-11e6-8732-03ad55e3f66a.png)

**Comment by kosi2801** [comment]
further info from the console:

```
pi@radiumpi ~/projects/opengrok/opengrok-trunk/OpenGrok $ date
Wed Feb 22 14:34:23 CET 2017

pi@radiumpi ~/projects/opengrok/opengrok-trunk/OpenGrok $ git config --get remote.origin.url
https://github.com/OpenGrok/OpenGrok.git

pi@radiumpi ~/projects/opengrok/opengrok-trunk/OpenGrok $ git pull
Already up-to-date.

pi@radiumpi ~/projects/opengrok/opengrok-trunk/OpenGrok $ git diff -u
diff --git a/OpenGrok b/OpenGrok
index 9f4cc17..531844b 100755
--- a/OpenGrok
+++ b/OpenGrok
@@ -323,7 +323,7 @@ DefaultInstanceConfiguration()
     fi
 
     # OPTIONAL: JVM Options
-    JAVA_OPTS="${JAVA_OPTS:--Xmx2048m}"
+    JAVA_OPTS="${JAVA_OPTS:--Xmx512m}"
     
     # OPTIONAL: Full Path to History Utilities
     HG="`Which hg`"

pi@radiumpi ~/projects/opengrok/opengrok-trunk/OpenGrok $ git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   OpenGrok
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       bin/
#       hs_err_pid2896.log
#       lib/derbyclient.jar
#       nohup.out
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by kosi2801** [comment]
I rechecked with the latest source version as of 2017-03-30 and this strange UI behavior with groupings is still present.
Can I provide you with further specific info to help analyzing this?

(And I noted something else too, the "+"/"-" on the right side of each groups header is always "+" upon loading of the page, even if all groups are expanded.)

**Comment by kosi2801** [comment]
Our project structure has changed and our installation of OpenGrok has been updated to reflect this.
With the latest version from Git and the new structure this behavior cannot be reproduced anymore.
Closing.
