### ISSUE TITLE
move scripts to the bottom of the page

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1455]
https://github.com/OpenGrok/OpenGrok/blob/master/web/httpheader.jspf#L78

scripts should be sourced in as last on page
(performance best practice)

**Comment by tarzanek** [comment]
@tulinkry what do you think?

**Comment by tulinkry** [comment]
Yes that is true and the page will load faster. However the change is not that trivial because our js code contains some constructs like:
```js
document.pageReady = [];
document.domReady = [];
```
so the whole page needs the scripts to be loaded at the top. And there may be more similar problems than just this one.
