### ISSUE TITLE
favicon.ico and Error: file not found!

### ISSUE THREAD

**Issue by ranjantomtom** [OpenGrok/OpenGrok#1460]
Opengrok latest version deploy on Apache Tomcat/8.5.11 but whenever we cleared cache and hit the url site opening with post fix keyword "favicon.icon" and on home page of Opengrok below Search button there is an error called
" Error: File not found!
The requested resource is not available. 

Can some one please let me know how to remove this.

**Comment by ranjantomtom** [comment]
![favicon error](https://cloud.githubusercontent.com/assets/22164654/23782617/b4949db4-057b-11e7-8f78-f446f822f258.png)

**Comment by vladak** [comment]
I am not sure this ever worked. The `favicon.ico` file is not delivered with OpenGrok.

See #813 for details on how the icon is displayed.

**Comment by tulinkry** [comment]
There is no `favicon.ico`. The icon we use is http://localhost:8080/source/default/img/icon.png. So the error is quite reasonable, isn't it?

**Comment by vladak** [comment]
The behavior seems to be as expected, hence closing.
