### ISSUE TITLE
get rid of sleeps in testExpirationSingle if possible

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1470]
for (int i = 0; i < 5; i++) {
            Assert.assertEquals(1, env.getMessagesInTheSystem());
            Assert.assertNotNull(env.getMessages());
            Assert.assertEquals(new TreeSet<Message>(Arrays.asList(makeArray(m1))), env.getMessages());
            sleep(100);
        }
        sleep(30);
        Assert.assertEquals(0, env.getMessagesInTheSystem());

junit/org.opensolaris.opengrok.configuration.messages/ExpirationNormalMessageTest/testExpirationSingle/

started to fail randomly, that means we have to find a better way than sleeps to check if the messages arrived ...

**Comment by tarzanek** [comment]
@tulinkry is there a better way than sleeps?

**Comment by tulinkry** [comment]
I noticed that also and it appeared as a bad design. I will try to avoid using these. Maybe it is not really necessary to control if the expiration thread works but just the methods which trash the messages.
