### ISSUE TITLE
Bad reporting of OPENGROK_WEBAPP_CFGADDR value

### ISSUE THREAD

**Issue by TotoXe** [OpenGrok/OpenGrok#1472]
Hello,

While testing 0.13-rc10, I set variable OPENGROK_WEBAPP_CFGADDR to 'localhost:2425'.

When indexng, I see in the log:
12:04:09 INFO: Done indexing data of all repositories (took 7.919 seconds)
12:04:09 INFO: Sending configuration to: **localhost**
12:04:09 INFO: Configuration update routine done, check log output for errors.

Could you fix to get the correct value:
12:04:09 INFO: Sending configuration to: **localhost:2425**

**Comment by vladak** [comment]
@TotoXe  this is a simple change - would you like to fix it ?

**Comment by vladak** [comment]
Aha, I see @tulinkry was quicker :-)

**Comment by tulinkry** [comment]
Soorry ;-)

**Comment by TotoXe** [comment]
Thanks! I had found the lines to update this we :-) But I don't know Java (only basics). I eventually had been able to fix but your are quicker and better and so safer to fix :-D !
