### ISSUE TITLE
bugs of displaying function names (C++)

### ISSUE THREAD

**Issue by huang-qiao** [OpenGrok/OpenGrok#1484]
please refer to following screenshot
![screenshot from 2017-03-27 10 28 18](https://cloud.githubusercontent.com/assets/3132687/24338629/6e6b626c-12d9-11e7-97bb-4049793d75be.png)

**Comment by vladak** [comment]
I remember filing similar report and the advice was to reindex + hard refresh the page (ctrl+shift+R).

Also, when submitting bug reports, it is always handy to supply basic information such as OpenGrok version, browser version etc.

**Comment by tulinkry** [comment]
Full reindex neeeded. Xref format has changed.

**Comment by vladak** [comment]
Closing. If the problem persists even after full reindex and refresh, feel free to reopen.
