### ISSUE TITLE
Error page does not contain a page title above the orange line

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1485]
Error page does not contain the "title" above the orange line. This is inconsistent with all other pages.

![screenshot from 2017-03-27 13-43-10](https://cloud.githubusercontent.com/assets/6997160/24354856/c8b19f7e-12f3-11e7-8d5f-5aa2e52e17db.png)

vs. 

![screenshot from 2017-03-27 13-45-45](https://cloud.githubusercontent.com/assets/6997160/24354857/c8b2cf7a-12f3-11e7-818d-75ed8a18d73c.png)

**Comment by tulinkry** [comment]
The same goes for `help.jsp`

**Comment by vladak** [comment]
fixed in cset b4fa08d7423c58bb4ab219b6eb91256d1e2332d9
