### ISSUE TITLE
Historycache generation is extremely long

### ISSUE THREAD

**Issue by ChristopheBordieu** [OpenGrok/OpenGrok#1491]
Hello,

I am still testing 0.13-rc10. I have some huge Git repos under same project.
History cache generation takes so long now compared to 0.12.1.6...
(I have also a bug I think (related to rename file) but, if confirmed, I will open another  issue.)

- Could you list the changes b/w 2 versions regarding history cache generation ?
- Is there any customization available to speed up this process ? On my Linux box, with htop, I see that at maximum 4 git log jobs are running at same time in index process.
- Also, what is the difference for variable OPENGROK_GENERATE_HISTORY between values _on_ and _uionly_ ? Does _uionly_ generate history on the fly while a user is looking at a file ?

**Comment by tulinkry** [comment]
Hello,

> (I have also a bug I think (related to rename file) but, if confirmed, I will open another issue.)

Looking forward to this.

> Could you list the changes b/w 2 versions regarding history cache generation ?

the one with the biggest impact is *Git handling renamed files* #1345

> Is there any customization available to speed up this process ? On my Linux box, with htop, I see that at maximum 4 git log jobs are running at same time in index process.

1. There is a possibility to turn off handling renamed files (as it surely does slow down the whole process) which is [described in another question's comment](https://github.com/OpenGrok/OpenGrok/issues/1395#issuecomment-279408378) - see also detailed answer two comments below this one.
2. There is a [system property](https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java#L137) to control how many threads process the history generation.
3. Then there is a [system property](https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java#L165) which can adjust the number of threads handling the renamed files (separate git log processes).

> Also, what is the difference for variable OPENGROK_GENERATE_HISTORY between values on and uionly ? Does uionly generate history on the fly while a user is looking at a file ?

@tarzanek @vladak

**Comment by vladak** [comment]
As for `OPENGROK_GENERATE_HISTORY` - yes, `uionly` should generate the history only in history view, not during reindex.

**Comment by ChristopheBordieu** [comment]
> `uionly` should generate the history only in history view, not during reindex.

History then is cached and can be indexed (and thus searched) at next reindex of the repo ?
If so, it could be a workaround t the long runtime if tuning of system properties does not help me.

To setup a property, I think I have to set into the XML config a piece of XML code related to the property. I will try to mimic what I find into my config but if you have a FAQ explaining how to do that easily, feel free to provide it to me !

**Comment by tulinkry** [comment]
1. Setting a java property is pretty straightforward:
 - when you run java
```bash
$ java -Dorg.opensolaris.opengrok.history.NumCacheThreads=50000 -jar opengrok.jar ...
```
 - when you use `OpenGrok` wrapper
```bash
$ JAVA_OPTS="-Dorg.opensolaris.opengrok.history.NumCacheThreads=50000" ./OpenGrok index
```

More about this in the [doc](http://docs.oracle.com/javase/jndi/tutorial/beyond/env/source.html)

2. Setting the xml stuff is the option number 1 in previous comment:
> There is a possibility to turn off handling renamed files (as it surely does slow down the whole process) which is described in another question's comment - see also detailed answer two comments below this one.

and is described in the mentioned comment.

**Comment by ChristopheBordieu** [comment]
Thanks! I will play with all these settings and will keep you posted.

**Comment by vladak** [comment]
The slow history index is similar to question in #1402

**Comment by vladak** [comment]
Be careful when specifying the number of threads. By default, the thread pool size is set to `availableProcessors()` which is the number of online CPUs in the system.

**Comment by vladak** [comment]
The `uionly` setting means that the history will be available only in the webapp, i.e. cannot be searched.

**Comment by ChristopheBordieu** [comment]
I am not able to test `uionly`.
I have deleted all date regarding project PROJ (into data directory). Then set OPENGROK_GENERATE_HISTORY to `uionly` then  run `OpenGrok indexpart` on one of the repos inside this project. I get all history cache file generated ???
```
export OPENGROK_GENERATE_HISTORY=uionly
READ_XML_CONFIGURATION=/srv/staging-opengrok-var/etc/configuration.xml /srv/opengrok-0.13-rc10/bin/OpenGrok indexpart /srv/staging-opengrok-var/src /PROJ/repo1
```
What am I doing wrong ?

**Comment by vladak** [comment]
I think the way it was designed^Whacked together, the `uionly` and other flags can only work for not-dirbased repositories such as CVS. Will file separate issue for that.

In your case I think it is sufficient to turn off renamed file handling and the performance will be back to the previous level.

**Comment by ChristopheBordieu** [comment]
History cache generation with renamed file handling: 12:16:03
History cache generation without renamed file handling: 00:05:01
Ouaw!
I will not try to play with system options. The feature is unusable for us (thousands of Git repos to index) :-(

(Regarding the bug I had during my first run (with rename file handling on), it was not reproduced during the second run (with rename file handling on).)

**Comment by tulinkry** [comment]
There could be some unnecessary work which has to be further inspected and optimized however it will take more time always as it handles the renamed files. That's a tradeoff for more accurate history cache.

**Comment by ChristopheBordieu** [comment]
Agreed. Since it is a tradeoff, would be good user can decide if he/she wants or not the feature to be set.

**Comment by tulinkry** [comment]
> Is it possible to disable by default the feature ? 

This feature provides more correct data

> And/or to set/unset it via an environment variable OPENGROK_* into OpenGrok script ?

Yes this may be the way to simplify the process with renamed files. Also we consider project centralized management (options are now shared - no customization for single project) (#1390) which would make it more customizable for single projects.

**Comment by tulinkry** [comment]
I filed an enhancement request #1500 for the simplification

**Comment by ChristopheBordieu** [comment]
Thanks! Yep #1390 would be a great feature. (Still beter would be it is customizable at repo level instead of project level ;-))
