### ISSUE TITLE
Provide a way how to simplify turning off the renamed files

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1500]
In #1491 and some others we discussed that the process of turning off the renamed files handling is somewhat cumbersome (adding a property to a xml file and using `OPENGROK_READ_XML_CONGURATION` variable). It would be nice if there was a quicker way through say `OPENGROK_RENAMED_FILES`. 

I know we're almost out of the alphabet in the command line but this appeared as really important for several users.

**Comment by vladak** [comment]
As for the getopt, I think the time has come to switch to longopts.
