### ISSUE TITLE
Navigate and Scopes windows superimpose

### ISSUE THREAD

**Issue by ChristopheBordieu** [OpenGrok/OpenGrok#1501]
These 2 windows superimpose when both activated at same time.
![image](https://cloud.githubusercontent.com/assets/26546513/24453965/2df9088a-148a-11e7-8c1c-d71f466c8309.png)
When both are empty, only Navigate window is visibe. 
When at least Navigate is non empty, Scopes is always in front.
I have no idea what happens when Navigate is empty but not Scopes ?

Maybe, these 2 windows when activated at same time should be side by side ?

**Comment by tulinkry** [comment]
I currently updated this in #1502 and it should by fine when it gets merged.

The idea is (and was partially supported) that when both are open then the navigate moves down a bit.

**Comment by tulinkry** [comment]
Closing as this is implemented in #1502. Feel free to reopen if the problem persists
