### ISSUE TITLE
main page not valid HTML

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1509]
http://src.couchbase.org/source/

https://validator.w3.org/check?uri=http%3A%2F%2Fsrc.couchbase.org%2Fsource%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&No200=1&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

the div and js are not well formed

**Comment by tulinkry** [comment]
and for the second part it seems to me that the extra `<div>` element was added in cset dc2627429268b6ece694374ed41014269dd8a976 by mistake as a part of pr #1342. @vladak can you please review this again? it seems to me that

```html
        <div id="results">
            <%= PageConfig.get(request).getEnv().getConfiguration().getBodyIncludeFileContent() %>
        </div> <!-- THIS ONE IS EXTRA -->
```

this `<div>` can be safely removed to make the main page valid again

**Comment by vladak** [comment]
Good catch, the terminating div indeed seems superfluosly added.
