### ISSUE TITLE
support for nested git repositories

### ISSUE THREAD

**Issue by dohseven** [OpenGrok/OpenGrok#1512]
I'm using the latest OpenGrok 1.0 release, and I have an issue with the repository detection for the history creation.

Our project is using `repo` for the file versioning, allowing to have a Git repository inside another one. The folder structure looks like:
```
baseDirectory/.git
baseDirectory/anotherDirectory
baseDirectory/anotherDirectory/.git
```

The first Git repository `baseDirectory` is correctly detected and the history is retrieved, but the second one `anotherDirectory` is never seen. I have tried to use the `-z` command-line option, but it doesn't solve my issue.

Looking at [the code](https://github.com/OpenGrok/OpenGrok/blob/b9a9ac8ac8c99dbddc850331b5f8229ed0ac3509/src/org/opensolaris/opengrok/history/HistoryGuru.java#L339) of the `addRepositories` function, I'm under the impression that the case of a repository inside another repository is not supported. Am I right?

I know that I could create the history for all sub-repositories using the `-h` option, but this would be extremely painful as all absolute paths should be added manually. This would also not be easy to maintain if a repository is added or removed.

**Comment by vladak** [comment]
Nested repos work fine for Mercurial cause it sets `supportsSubRepositories`

**Comment by vladak** [comment]
relevant piece of code in `addRepositories()`:

```
385                      if (recursiveSearch && repository.supportsSubRepositories()) {
386                          File subFiles[] = file.listFiles();
387                          if (subFiles == null) {
388                              LOGGER.log(Level.WARNING,
389                                      "Failed to get sub directories for ''{0}'', check access permissions.",
390                                      file.getAbsolutePath());
391                          } else if (depth <= scanningDepth) {
392                              // Search only one level down - if not: too much
393                              // stat'ing for huge Mercurial repositories
394                              addRepositories(subFiles, repos, ignoredNames,
395                                      false, depth + 1);
396                          }
397                      }
```
