### ISSUE TITLE
rename EXUBERANT_CTAGS env var

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1514]
The `OpenGrok` shell script uses `EXUBERANT_CTAGS` which has 2 problems:
   - does not have the `OPENGROK_` suffix
  - OpenGrok supports Universal ctags as well so the name could be confusing

So, it should be renamed to something more fitting, e.g. `OPENGROK_CTAGS`

**Comment by tulinkry** [comment]
I checked these variables in #1487 and I didn't propose this ctags variable as it can have a meaning for the system itself. Anyway the "exuberant" is a little bit confusing.
