### ISSUE TITLE
cannot go to Annotate from history view

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1520]
clicking in the Annotate link in the history view does nothing

**Comment by tulinkry** [comment]
For the record, I found a code that had built the annotate link (so everything look cool although not correct) when the prefix is history but got commented out.
```java
    if (!cfg.hasAnnotations() /* || cfg.getPrefix() == Prefix.HIST_S */ ) {
        %><li><span class="c"><span class="annotate"></span>Annotate</span></li><%
    } else if (cfg.annotate()) {
```
