### ISSUE TITLE
Filter used by webapp happens to be filtering on Tomcat path

### ISSUE THREAD

**Issue by shauenstein-91056** [OpenGrok/OpenGrok#1533]
Hi folks,

I like the new opengrok 1.0 with the navigation pane and would like to migrate.

However I have a problem which drives me nuts.  Searching works fine. But the directory listing is always empty. Eg

http://localhost:8095/1830srosviews/xref/panos-sidewinder/iom_api/iom_api.h

fileaccess is fine. However 

http://localhost:8095/1830srosviews/xref/panos-sidewinder/iom_api/

shows only an empty file list.

I had also to upgrade the the apache-tomcat-6.5 to apache-tomcat-9.0.0.M19.

Caching is switched of.
Does anybody have the same problem? 

A1: firebug httml response protocol:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta name="robots" content="noindex,nofollow" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="generator" content="{OpenGrok 1.0 (2850968932c2933b8ebb1f9808991cda0be846ed)" />
<link rel="icon" href="/1830srosviews/default/img/icon.png" type="image/png" />
<link rel="stylesheet" type="text/css" media="all"
    title="Default" href="/1830srosviews/default/style.css" />
<link rel="alternate stylesheet" type="text/css" media="all"
    title="Paper White" href="/1830srosviews/default/print.css" />
<link rel="stylesheet" type="text/css" href="/1830srosviews/default/print.css" media="print" />
<link rel="stylesheet" type="text/css" href="/1830srosviews/default/jquery-ui-1.12.0-custom.min.css"
 />
<link rel="stylesheet" type="text/css" href="/1830srosviews/default/jquery.tooltip.css" />
<link rel="stylesheet" type="text/css" href="/1830srosviews/default/jquery.tablesorter.css" />
<link rel="stylesheet" type="text/css" href="/1830srosviews/default/searchable-option-list-2.0.2.min
.css" />
<link rel="search" href="/1830srosviews/opensearch"
    type="application/opensearchdescription+xml"
    title="OpenGrok Search for current project(s)" />
<script type="text/javascript">/* <![CDATA[ */
    window.contextPath = '/1830srosviews';
    document.xrefPath = '/1830srosviews/xref';
    document.pageReady = [];
    document.domReady = [];
/* ]]> */
</script>
<title>iom_api - OpenGrok cross reference for /panos-sidewinder/iom_api/</title></head><body>
<script type="text/javascript">/* <![CDATA[ */
    document.rev = function() { return getParameter("r"); };
    document.annotate = false;
    document.domReady.push(function() { domReadyMast(); });
    document.pageReady.push(function() { pageReadyMast(); });
/* ]]> */</script>
<div id="page">
    <div id="whole_header">
<div id="header"></div>
<div id="Masthead">
    <a href="/1830srosviews/xref/">xref</a>: /<a href="/1830srosviews/xref/panos-sidewinder/">panos-sidewinder
</a>/<a href="/1830srosviews/xref/panos-sidewinder/iom_api/">iom_api</a>/<span id="dtag">
    </span>
    </div>
<form action="/1830srosviews/search">
<div id="bar">
    <ul>
        <li><a href="/1830srosviews/"><span id="home"></span>Home</a></li><li><a href="/1830srosviews
/history/panos-sidewinder/iom_api/"><span id="history"></span>History</a></li><li><span class="c"><span
 class="annotate"></span>Annotate</span></li><li><input type="text" id="search" name="q" class="q" /
>
            <input type="submit" value="Search" class="submit" /></li><li><input type="checkbox" name
="path" value='"/panos-sidewinder/iom_api/"' /> only in <b>this directory</b></li>
    </ul><input type="hidden" id="contextpath" value="/1830srosviews" />
</div>
        </form>
    </div>
<div id="content">
<script type="text/javascript">/* <![CDATA[ */
document.pageReady.push(function() { pageReadyList();});
/* ]]> */</script>
<table id="dirlist" class="tablesorter tablesorter-default">
<thead>
<tr>
<th class="sorter-false"></th>
<th>Name</th>
<th class="sorter-false"></th>
<th class="sort-dates">Date</th>
<th class="sort-groksizes">Size</th>
</tr>
</thead>
<tbody>
<tr><td><p class="'r'"/></td><td><b><a href="..">..</a></b></td><td></td><td>Today</td><td>4 KiB</td
></tr>
</tbody>
</table><div id="footer">
<p><a href="http://opengrok.github.com/OpenGrok/"
 title="Served by OpenGrok"><span id="fti"></span></a></p>
<p>Indexes created Mon Apr 10 12:05:06 EDT 2017</p>
</div></div>
</div>
<script type="text/javascript" src="/1830srosviews/js/jquery-3.2.0.min.js"></script>
<script type="text/javascript" src="/1830srosviews/js/jquery-ui-1.12.0-custom.min.js"></script>
<script type="text/javascript" src="/1830srosviews/js/jquery.tablesorter-2.26.6.min.js"></script>
<script type="text/javascript" src="/1830srosviews/js/tablesorter.parsers-0.0.1.js"></script>
<script type="text/javascript" src="/1830srosviews/js/searchable-option-list-2.0.3.min.js"></script>

<script type="text/javascript" src="/1830srosviews/js/utils-0.0.8.js"></script>
</body>
</html>

```

**Comment by vladak** [comment]
First thing I'd do is to switch to the user the Tomcat is running under and try to perform directory listing in affected paths.

Any relevant warning/error messages in Tomcat logs ?

Do you have any features enabled that would make the directory listing more complicated ? (e.g. SELinux and such)

Is the Tomcat run with Java SecurityManager perhaps ?

**Comment by shauenstein-91056** [comment]
Hi vladak,
- there are no tomcat (warning logs)
- the Java SecurityManager is not active
- Indexing and tomcat run under the same user
- all dirs are readable

I am now using apache-tomcat-8.5.13
I have added  some debug printf to the list.jsp to see if tomcat can read the corresponding dirs and can verify that I get a response. E.g

```
      if (!files.isEmpty()) {
            List<String> readMes = dl.listTo(
                    Util.URIEncodePath(request.getContextPath()),
                    resourceFile, out, path, files);
                    System.out.println("ContextPath:" + Util.URIEncodePath(request.getContextPath()) + " resoureFile:" + resourceFile + " out:" + out + " path:" + path + " files:" + files );
                    System.out.println("readMes:" + readMes);

gives me a decent file dir pointer and the list of files:

ContextPath:/1830-srosviews_source resoureFile:/devel/opengrok-data-sros/stage1/source/panos-pkt2-dune/bcm/sdk-new/include/bcm_int out:org.apache.jasper.runtime.JspWriterImpl@15ea310 path:/panos-pkt2-dune/bcm/sdk-new/include/bcm_int/ files:[api_ref.h, api_xlate_port.h, async_req.h, async_server.h, bcm_dlist.h, bst.h, caladan3_dispatch.h, client_dispatch.h, common, compat, control.h, dfe, dfe_dispatch.h, dispatch.h, dnx, dnx_dispatch.h, dnxf, dnxf_dispatch.h, dpp, ea, esw, esw_dispatch.h, loop_dispatch.h, petra_dispatch.h, ptp_common.h, regex_api.h, robo, robo_dispatch.h, rpc, sbx, sbx_dispatch.h, shadow_dispatch.h, tk371x_dispatch.h, xasync_req.h]
readMes:[]

```
Happ Easter anyway..

**Comment by vladak** [comment]
The `listTo()` received non-empty `files` list but did not write it to the `out`. In the listing above we can see the tablesorter and `..` entries which means it arrived to the code:

```
161          // print the '..' entry even for empty directories
162          if (path.length() != 0) {
163              out.write("<tr><td><p class=\"'r'\"/></td><td>");
164              out.write("<b><a href=\"..\">..</a></b></td><td></td>");
165              printDateSize(out, dir.getParentFile(), null, dateFormatter);
166              out.write("</tr>\n");
167          }
168  
169          Map<String, Date> modTimes =
170                  HistoryGuru.getInstance().getLastModifiedTimes(dir);
171  
172          if (files != null) {
173              for (String file : files) {
174                  if (ignoredNames.ignore(file)) {
175                      continue;
176                  }
177                  File child = new File(dir, file);
178                  if (ignoredNames.ignore(child)) {
179                      continue;
180                  }
```

This looks as if all the files inside the directory were ignored.

What does `configuration.xml` say w.r.t. ignored entries ?

Happy Easter to you as well !

**Comment by shauenstein-91056** [comment]
Hi Vladak,
thanks for picking this up.

I think in the context of the list.jsp the empty listTo() is ok. I verfied it on my grok 0.12 that the list there is also empty. 

The diretory listing is pushed in somewhere else. But I am not familiar with the grok java code or the jsp framework.

My ignore file ist is
    IGNORE_PATTERNS="-i "*/buildlogs/*" -i"*/objs/*" -i"*/deps/*" -i"*/bin/*""
also seen in configuration.xml
```
  <void id="IgnoredNames0" property="ignoredNames">
   <void id="IgnoredFiles0" property="ignoredFiles">
    <void property="items">
     <void method="add">
      <string>*/buildlogs/*</string>
     </void>
     <void method="add">
      <string>*/objs/*</string>
     </void>
     <void method="add">
      <string>*/deps/*</string>
     </void>
     <void method="add">
      <string>*/bin/*</string>
     </void>
    </void>
   </void>
```
on linux I see also the indexed file
http://localhost:8095/1830srosviews/xref/panos-sidewinder/bcm/sdk-new/include/bcm_int/api_xlate_port.h

but not the directory listing under
http://local:8095/1830srosviews/xref/panos-sidewinder/bcm/sdk-new/include/bcm_int

on the file system I get a full list of indexed dirs:
e.g

 ls /devel/opengrok-data-sros/stage1/data/xref/panos-sidewinder/bcm//sdk-new/include/bcm_int/
api_ref.h.gz         bcm_dlist.h.gz          common        dfe_dispatch.h.gz  dnxf                esw                  ptp_common.h.gz     rpc                   tk371x_dispatch.h.gz
api_xlate_port.h.gz  bst.h.gz                compat        dispatch.h.gz      dnxf_dispatch.h.gz  esw_dispatch.h.gz    regex_api.h.gz      sbx                   xasync_req.h.gz
async_req.h.gz       caladan3_dispatch.h.gz  control.h.gz  dnx                dpp                 loop_dispatch.h.gz   robo                sbx_dispatch.h.gz
async_server.h.gz    client_dispatch.h.gz    dfe           dnx_dispatch.h.gz  ea                  petra_dispatch.h.gz  robo_dispatch.h.gz  shadow_dispatch.h.gz

I did clear the firefox cache..

**Comment by vladak** [comment]
I think your `ignoredFiles` entries are biting you. The specification should be a regular expression. I just tried running the indexer with `-i */bin/*` and getting the same result - all entries are ignored.

**Comment by vladak** [comment]
The `*/bin/*` pattern gets normalized to something like `.*/bin/.*`. This code in `Filter.java`:

```
107      public boolean match(File file) {
108          String fileName = file.getName(); // basename
109          String absolute = file.getAbsolutePath();
110  
111          if (filenames.contains(fileName)) {
112              return true;
113          }
114  
115          for (Pattern p : patterns) {
116              // Try to match the basename first.
117              Matcher m = p.matcher(fileName);
118              if (m.matches()) {
119                  return true;
120              }
121              // Try the full path next.
122              if (p.pattern().contains("/")) {
123                  m = p.matcher(absolute);
124                  if (m.matches()) {
125                      return true;
126                  }
127              }
128          }
```

gets a match for the patter on line 125, thus the file gets ignored.

There is a weird twist to this though - the `fileName` in my case is `foo` and the `absolute` string got expanded to `/export/home/.../apache-tomcat-8.0.36/bin/foo` so there comes the match.

Of course, the absolute path is derived from the runtime Tomcat directory which is not good.

**Comment by vladak** [comment]
The problem starts here in `Filter.java`:

```
139      /**
140       * Does the file name match any of the filenames, patterns or paths ?
141       * @param name the name of the file to check
142       * @return true if this pathname matches, false otherwise
143       */
144      public boolean match(String name) {
145          return match(new File(name));
146      }
```

**Comment by shauenstein-91056** [comment]
Hi vladak,
you are my hero of the day. Many Thanks 👍 👍 🥇 
I removed the */bin/* pattern and got my file list back!
I owe you a beer!

My pattern looks good for indexing, but I did not realize that the web app is involved there as well.

Unfortunately I never did  grok web application debugging before. I am not a web programmer. I would love to do it once. If time permits.
kind regards
siggi

**Comment by shauenstein-91056** [comment]
just to be correct. This issue is **not** introduced with opengrok 1.0. 

In 0.12 I was using no ignore pattern  -i"\*/bin/\*"

**Comment by vladak** [comment]
You're welcome. I think the workaround might be to ignore the `bin` directory using the `-i d:bin` argument to the indexer.
