### ISSUE TITLE
OpenGrok 1.0 does not generate history for non cached history repositories

### ISSUE THREAD

**Issue by mmmarq** [OpenGrok/OpenGrok#1539]
I have just finished to deploy opengrok 1.0 and after run index command without "-H" flag I'm not able to get file history from web interface.

In a separate project, I ran index command with "-H" flag, all history cache files were created and even I delete history cache from an item, opengrok is able to recreate the history when requested by web interface again.

All my projects are on GIT

Also I saw that on configuration.xml file from non cached history session below is missing:

```<void property="repositories">```

My index command line is:

```/sse/components/jre/bin/java -server -Xmx8192m -Xms8192m -XX:PermSize=1024m -XX:MaxPermSize=2048m -jar /sse/components/opengrok/lib/opengrok.jar -c /sse/bin/ctags -a on -P -S -r on -s /sse/src_root/ -d /sse/data/ -L polished -w source -W /sse/etc/configuration.xml -U ilclsse02:2222 -T 96 -z 10 -i <exclude file list>```

Since my repository is a huge one, O would like to generate history on demand and not by index process.

Is this behavior WAD?

Thanks in advance

**Comment by tarzanek** [comment]
This might be a bug ... but from your options it's hard to see which is used and which one we dropped in between ;)

Can you try to convert to using OpenGrok script and its env variables?
We tried hard to fit every use case, so please check head of OpenGrok and try to run it like that
also some of your options might not be relevant anymore (especially for jdk8)

That said ... no one tried the history generation on demand, so you really might be hitting a bug ...
(but let's start with using OpenGrok script first to avoid defaults override)

ttyl
L

**Comment by vladak** [comment]
I think the semantics of the -H option is on/off and should be further controlled with the -r option (modulo bugs like #1498). So, it's not surprising to me that omitting -H will generate no history.

**Comment by tarzanek** [comment]
I remember some "economic" option, but not sure how good does it work these days

**Comment by vladak** [comment]
The -r is the "economic" (or fuzzy logic option). The -H should either enable or disable history generation. If it's enabled, it can be further tuned with -r. So the reported behavior is correct. This should really be solved with the beforementioned issue.

**Comment by mmmarq** [comment]
Hi Guys,

Sorry my delay to reply you about my own issue... I was out of office since last Friday without internet access.

I really appreciate you comments, but I think I did not reach a command line configuration that could take desired effect I'm looking for.

I just want a command line that could populate my configuration file with:

```
<void property="repositories">
...
...
</void>
```

This "**repositories**" session enable history generation without previous cached file generated by **-H** flag on command line. Since we have really huge repositories (full index with history cache takes 48 hours) it is not a good approach when I have to index new branches.

I have created a workaround to get configuration file without running index or history cache. See patch below:

```
diff --git a/src/org/opensolaris/opengrok/index/Indexer.java b/src/org/opensolaris/opengrok/index/Indexer.java
index 9cd6f50..7608ccb 100644
--- a/src/org/opensolaris/opengrok/index/Indexer.java
+++ b/src/org/opensolaris/opengrok/index/Indexer.java
@@ -561,7 +561,7 @@ public final class Indexer {
                 getInstance().prepareIndexer(env, searchRepositories, addProjects,
                         defaultProjects, configFilename, refreshHistory,
                         listFiles, createDict, subFiles, repositories,
-                        zapCache, listRepos);
+                        zapCache, listRepos, runIndex);
                 if (listRepos || !zapCache.isEmpty()) {
                     return;
                 }
@@ -616,7 +616,8 @@ public final class Indexer {
             List<String> subFiles,
             List<String> repositories,
             List<String> zapCache,
-            boolean listRepoPaths) throws IndexerException, IOException {
+            boolean listRepoPaths,
+            boolean runIndex) throws IndexerException, IOException {
 
         if (env.getDataRootPath() == null) {
             throw new IndexerException("ERROR: Please specify a DATA ROOT path");
@@ -636,7 +637,7 @@ public final class Indexer {
         if (searchRepositories || listRepoPaths || !zapCache.isEmpty()) {
             LOGGER.log(Level.INFO, "Scanning for repositories...");
             long start = System.currentTimeMillis();
-            if (refreshHistory == true) {
+            if (refreshHistory == true || runIndex == false ) {
                 HistoryGuru.getInstance().addRepositories(env.getSourceRootPath());
             }
             long time = (System.currentTimeMillis() - start) / 1000;
```

I know that the patch above is now best fix for my needs, but now I'm able to enable on demand history generation by webapp without **-H** on command line.

Thank you guys for your attention.

**Comment by vladak** [comment]
Glad you were able to spin up a solution. I will try to take this use case into account when fixing #1498 so that you will be able to use something like `-H -r uionly`.

**Comment by tarzanek** [comment]
@mmmarq what about -n ?
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/CommandLineOptions.java#L94

**Comment by mmmarq** [comment]
Hi @tarzanek,

"**-n**" flag does not works because the needed config file entries (```<void property="repositories">```) only happens when I use "**-H**" flag, but using this flag, opengrok will generate all history cached files. I just want a way to add repositories description on config file without cached history files generation.

Thank you for your attention.

**Comment by tarzanek** [comment]
this looks like the options seriously call for some cleanup / improvement

**Comment by vladak** [comment]
The `-r` cleanup will happen in #1498. As for the `-n` option, the usage for it says:

```
Do not generate indexes, but process all other command line options
```

It's a question if this means all indexes (i.e. including history index). If yes, then it does not behave like this because the code goes like this (`runIndex` is set to false by `-n`):

```
569                  // Get history first.
570                  getInstance().prepareIndexer(env, searchRepositories, addProjects,
571                          defaultProjects, configFilename, refreshHistory,
572                          listFiles, createDict, subFiles, repositories,
573                          zapCache, listRepos);
574                  if (listRepos || !zapCache.isEmpty()) {
575                      return;
576                  }
577  
578                  // And now index it all.
579                  if (runIndex || (optimizedChanged && env.isOptimizeDatabase())) {
580                      IndexChangedListener progress = new DefaultIndexChangedListener();
581                      getInstance().doIndexerExecution(update, noThreads, subFiles,
582                              progress);
583                  }
```

Anyone feel free to file a new issue for this.
