### ISSUE TITLE
Authorization check message

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1542]
To quickly check if given user is authorized for given project/group new Message should be introduced, returning True/False.

**Comment by vladak** [comment]
Ideally, it would be nice if the return data would contain full trace of the authorization stack traversal along with the partial results from individual plugins.

**Comment by tulinkry** [comment]
This is not that easy as it seems because the check needs a full HTTP request with proper headers. OpenGrok has no entity such as user - the meaning is given by the particular plugins.

**Comment by vladak** [comment]
Agree - it is easier to construct the request by hand.
