### ISSUE TITLE
consider suppressing length for directories in directory listing

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1552]
`printDateSize()` in `DirectoryListing.java` contains this curious piece of commented out code:

```
84          // if (isDir) {
85              out.write(Util.readableSize(child.length()));
86          // }
```

Thing is, the `length()` value for directories is unspecified. On some systems it is a reference count, on others some different value. Also, I think in the case of simplified directory listing wrong directory might be taken for `length()`. So we should consider not writing the length for directories.

**Comment by vladak** [comment]
`DirectoryListingTest.java` would have to be updated.

**Comment by tulinkry** [comment]
And tablesorter parsers could need an update too
