### ISSUE TITLE
How to use "Message -n stats reload"

### ISSUE THREAD

**Issue by cosmoJFH** [OpenGrok/OpenGrok#1583]
I have successfully indexed my repository making use of Opengrok 1.0.

I have tried to make use of the new tool

./Messages -v -n stats reload

But I got the following error

Configuration loaded
	JAVA_HOME = /software/jdk1.8.0_60/
	JAVA = /software/jdk1.8.0_60//bin/java
	JAVA_OPTS = -Xmx32m
	JAVA_CLASSPATH = :/home/svnsearch/OpenGrok/tools/../dist/opengrok.jar
	OPENGROK_JAR = /home/svnsearch/OpenGrok/tools/../dist/opengrok.jar
	OPENGROK_CONFIGURATION = 
	OPENGROK_STANDARD_ENV = 
	OPENGROK_DISTRIBUTION_BASE = /home/svnsearch/OpenGrok/tools/../dist
	OPENGROK_JAR = /home/svnsearch/OpenGrok/tools/../dist/opengrok.jar

Files used
	DATE = date
	REMOTE_SERVER = localhost
	REMOTE_PORT_NUM = 2424
	MESSAGE_TYPE = stats
	MESSAGE_TAGS = 
	MESSAGE_CLASS = info
	MESSAGE_EXPIRE = +5 min
	MESSAGE_EXPIRE_TIMESTAMP = 1494189766
	MESSAGE_TEXT = reload
	MESSAGE_FILE = 

Message was not accepted by the remote server (error 0x4).
java.io.IOException: Message was not accepted by the remote server (error 0x4).
	at org.opensolaris.opengrok.configuration.messages.Message.throwIfError(Message.java:385)
	at org.opensolaris.opengrok.configuration.messages.Message.write(Message.java:307)
	at org.opensolaris.opengrok.configuration.messages.Messages.main(Messages.java:167)

I had to create by hand the file  $DATA_ROOT/data/statistics.json

Could you tell how to fix this issue?

**Comment by tulinkry** [comment]
The file is created when you shut down the application for the first time, so I guess you haven't stopped your application yet.

When the application has not been stopped yet the reload command does not make really sense - reload what? Or what did you expect from the command?

**Comment by cosmoJFH** [comment]
Thanks for your explanation. Now I understand the purpose of the "reload" option.
