### ISSUE TITLE
pluginDirectory null even if specified in 1.1-rc4

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1609]
Was running 1.1-rc3 with non-empty authorization config. Then upgraded to 1.1-rc4, deployed the webapp and Tomcat logs contained this:

```
23-May-2017 22:22:52.390 INFO [localhost-startStop-5] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /var/tomcat8/webapps/source.war
23-May-2017 22:22:53.062 WARNING [localhost-startStop-5] org.opensolaris.opengrok.authorization.AuthorizationFramework.reload Plugin directory not found or not readable: null. All 
requests allowed.
```

although `pluginDirectory` is defined and valid in `configuration.xml`.

**Comment by vladak** [comment]
Could this be possibly related to cset 8ca5403c32d4b13469d49e692dcbdbaa9002be25 ?

**Comment by vladak** [comment]
The `null` plugin directory message comes form `AuthorizationFramework#reload()`. In this case it gets called via `getInstance()` call in `contextInitialized()`:

```
63      public void contextInitialized(final ServletContextEvent servletContextEvent) {
64          ServletContext context = servletContextEvent.getServletContext();
65          RuntimeEnvironment env = RuntimeEnvironment.getInstance();
66  
67          String config = context.getInitParameter("CONFIGURATION");
68          if (config == null) {
69              LOGGER.severe("CONFIGURATION section missing in web.xml");
70          } else {
71              try {
72                  env.readConfiguration(new File(config));
73              } catch (IOException ex) {
74                  LOGGER.log(Level.WARNING, "OpenGrok Configuration error. Failed to read config file: ", ex);
75              }
76          }
```

and only then the configuration gets loaded so it looks like the "allow everything" decision is permanent after the first call.

**Comment by vladak** [comment]
The `null` directory comes from:

```
    private AuthorizationFramework authFramework = new AuthorizationFramework(null);
```

that gets called when RuntimeEnvironment gets instantiated that happens to be on line 65 above.

**Comment by tulinkry** [comment]
> Could this be possibly related to cset 8ca5403 ?

Yes it is. Will fix it
