### ISSUE TITLE
improve doFilter() logging

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1611]
I see entries like this in the Tomcat logs:

```
23-May-2017 23:09:42.081 INFO [http-nio-8888-exec-96] org.opensolaris.opengrok.web.AuthorizationFilter.doFilter access denied for uri: /source/xref/foo/
```

Ideally it should log the user identity.

Also, `uri` should be spelled in capital lettes.

**Comment by vladak** [comment]
while there, this line:

```
63              httpRes.sendError(403, "Access forbidden");
```

should be changed to use the symbolic instead of numeric error code.

**Comment by tulinkry** [comment]
> user identity.

the problem is that we don't know what is user identity
