### ISSUE TITLE
Want option to find matches within words

### ISSUE THREAD

**Issue by evanmorton** [OpenGrok/OpenGrok#1612]
It seems to match only on whole words rather than parts of words.  If I search for "max", I want to match on "local_max_temp".  This could be an option, as it is on many other search systems.

**Comment by tarzanek** [comment]
use * or ?
more in help

**Comment by tarzanek** [comment]
e.g. *max*
should do what you wanted

**Comment by evanmorton** [comment]
Good, thanks.
