### ISSUE TITLE
on demand xref generation does not produce Scopes

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1622]
It seems that if the indexer is run with -e (generate xrefs on demand), the Scopes are not generated. Not sure if this is a inherent limitation or could be fixed. @mrate ?

**Comment by mrate** [comment]
Yep, scopes were formely generated separately but due to some optimizations we merged them to xref generation. So if xrefs are disabled then scopes will not be generated... This could be fixed that if scopes are enabled and xrefs are not then run xref but ommit output and just generate the scopes.

**Comment by tarzanek** [comment]
I think with -e xrefs are generated on demand, it could very well be, that webapp container is not able to properly run them on top of source (e.g. webapp is missing ctags in path, etc. )
