### ISSUE TITLE
More highlighting colors in xref!

### ISSUE THREAD

**Issue by aerofeev2k** [OpenGrok/OpenGrok#1634]
Highlighting symbols in xref is a very useful feature.

As an enhancement I'd like to request addition of more colors, and e.g. binding them to keys 3, 4, 5, 6. Current binding for "3", which currently means "deselect all", is kind of a waste anyway, and can be sacrificed in favor of the new colors.

**Comment by tulinkry** [comment]
Just to make it clear, so you want to highlight more distinct symbols on the page. Like highlight all "foo" symbols with yellow color and all "bar" symbols with idk blue color?

**Comment by aerofeev2k** [comment]
Yes, like in the attached screenshot.



------ Original Message ------
   Received: 10:50 AM EDT, 06/19/2017

**Comment by tulinkry** [comment]
I added two more colors
