### ISSUE TITLE
introduce per project tunable to open Navigate window by default

### ISSUE THREAD

**Issue by tanglianggithub** [OpenGrok/OpenGrok#1636]
Navigate is helpful. I want it to open default. How can I do that?

Case-sensitive searching cannot still work, just for index size will increase?

Thanks.

**Comment by tarzanek** [comment]
first can be done by some post script on client side, e.g. greasemonkey?

second thing - upvote -  #463 , I guess nowadays the engine would handle it easily
we'd need to fix analyzers and add UI for switcher and ev. add flip for indexer to use it or not (but the costs might be so low now, that we should just go for it and enable case sensitive index by default ... )

**Comment by vladak** [comment]
The open navigate by default could be a per-project tunable.

**Comment by vladak** [comment]
I converted this issue to enhancement for the Navigate window. Let the other part (case sensitivity) continue in the respective (already existing) issue.

**Comment by vladak** [comment]
Looks like this was fixed in cset 3ef7a06
