### ISSUE TITLE
Is there any way to analyze *.h as C++?

### ISSUE THREAD

**Issue by tetsurom** [OpenGrok/OpenGrok#1641]
In some project C++ headers have `*.h` suffix.
As default they are analyzed as C, which make search result noisy.
For example C++ keyword such as `class` are recognized as symbol.

**Comment by tarzanek** [comment]
you would need to play with factory of C and CXX
and switch around H
alt. way (not sure if it will fully work) is to temporarily for particular project switch the H dynamically using -A option https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/CommandLineOptions.java#L75

**Comment by tarzanek** [comment]
(e.g. using indexpart just index the one project with flipped H using -A
to make this temporary)

**Comment by tetsurom** [comment]
It was solved adding this to command line.
```
-A .h:org.opensolaris.opengrok.analysis.c.CxxAnalyzerFactory
```
