### ISSUE TITLE
Grok will not worked on another network when indexing done but it will work on same network.

### ISSUE THREAD

**Issue by TusharPawar11** [OpenGrok/OpenGrok#1657]
When i am searching on Grok in my local network it will not giving updated copy of the code but its work on company network .

Please help .

**Comment by vladak** [comment]
Need a bit more info in order to help you.

Couple of questions:
  - Did you do any debugging yourself ?
  - What exactly is the problem ?
  - What version are you running ? (at home and at work - are these the same ?)

**Comment by TusharPawar11** [comment]
On both sides i am accessing through url.but at work got updated code nd at home it is not getting updated.

**Comment by vladak** [comment]
What do you mean by 'not getting updated' ? OpenGrok does not update the source code, this has to be done externally.
