### ISSUE TITLE
No Java symbol recognized

### ISSUE THREAD

**Issue by ChristopheBordieu** [OpenGrok/OpenGrok#1664]
OpenGrok 1.1-rc5

On our service, this search returns no file:
http://server/grok/search?project=ABC&q=&defs=&refs=_defaultValue&path=DEF&hist=&type=java
This one returns 4 files:
http://server/grok/search?project=ABC&q=_defaultValue&defs=&refs=&path=DEF&hist=&type=java
with a line example:
386 buffer.append("defaultValue=\"").append(_defaultValue).append("\" ");

We use Exuberant ctags when indexing.

Any idea why symbol is not found ?

**Comment by tarzanek** [comment]
yes, local vars are enabled only for universal ctags
can you reindex from scratch with universal ctags?

**Comment by ChristopheBordieu** [comment]
ok. what version of universal cags do i need to build for 1.1-rc5 ?

**Comment by vladak** [comment]
Thing is universal ctags does not use any versioning yet. Grab the latest.

**Comment by ChristopheBordieu** [comment]
ok. I read the doc... universa ctags installed. will reindex asap...

**Comment by ChristopheBordieu** [comment]
I have reindexed my staging to reproduce issue, still using exuberant ctags: symbol is found. I removed again index files and used universal ctags to reindex: symbol is found.
On prod, symbol not found when using exuberant ctags. 

I am quite lost...

**Comment by davecahill** [comment]
I am seeing the same or similar issue after upgrading to the latest OpenGrok. Essentially no Java symbols indexed in defs / refs.

When I run locally (ubuntu / Exuberant Ctags 5.9), defs and refs seem to index correctly. However, on CentOS / Exuberant Ctags 5.8, no symbols seem to be indexed. Note that on our old copy of OpenGrok (0.12.1) we were using CentOS / Exuberant Ctags 5.8 and defs / refs were correct. 

@ChristopheBordieu - which version of Exuberant Ctags are you using, on which OS?

**Comment by ChristopheBordieu** [comment]
Hi @davecahill 

- Exuberant Ctags 5.9~svn20110310
- Ubuntu

**Comment by davecahill** [comment]
@ChristopheBordieu  - Interesting. I'm trying to figure what the difference between my local env and prod env might be which is leading to defs/refs working in dev and not in prod. Sounds like you're in a similar situation. The main candidates in my case are: indexing many more repos in prod than in dev, ubuntu vs centos. Can you think of any differences between your staging and prod envs?

**Comment by tarzanek** [comment]
well I tested last time with ctags 5.9 like > 1 year ago
since then I switched to universal ctags

is it possible you make the switch in your prod envs too?

I don't think it makes sense for us to support too old versions of ctags, I am actually seriously tempted to stop supporting exuberant ctags, since they are too old and buggy

**Comment by tarzanek** [comment]
well the only other difference that comes to my mind can be regexp lib implementation, but then we test everything on Solaris with posix compliance, so unless the system breaks posix, it should work

also since local vars lookup in exctags is buggy(and no one is fixing exctags since 2011 :( ), we only enable it for universal ctags if detected

I know it's harder to get universal ctags to production machine, but it's the only way forward now ... (but hopefully we get a release of unictags very soon)

**Comment by tarzanek** [comment]
the differentiating factor - try to have a look at line which is used to launch ctags
also with OpenGrok 1.0 the ctags launch line became VEEERY long, so I hope we don't hit some limit of the (older?) OS  or some local limit setting on single command length
(we should definitely put the new language defs into a file)

**Comment by davecahill** [comment]
Interesting - any ideas where I should add logging to catch the potential long ctags line issue? I'm already making changes to the OpenGrok code, so I don't mind making changes and redeploying.

**Comment by tarzanek** [comment]
I filed #1672 on the length command

**Comment by tarzanek** [comment]
I guess you don't need logging,
just do 
$ ps axf
during indexing to see the tree and check the options of ctags process (in /proc )

**Comment by davecahill** [comment]
If I can see the process via ps, doesn't that mean it's running though? I've seen "command line too long" issues with java in the past, and they usually cause a failure for the process to launch. If I do see the process via ps, how would I know that it's *too* long?

**Comment by tarzanek** [comment]
check its /proc if any of the line is omitted
if the ctags process won't launch, opengrok will error out

**Comment by ChristopheBordieu** [comment]
All,

Some info on my part.

In my prod env, once all index/xref/historycache data removed for the projects impacted, after partial reindex, all defs and symbols are searchable again via symbol and definition boxes.
Same in dev env.
Both envs run Exuberant  ctags 5.9 on Ubuntu.

Tomorrow, I will try to use Universal ctags in dev env to see if it is working well too.

**Comment by tarzanek** [comment]
yes, deleting whole /var/opengrok/data is seriously advised between upgrades ...
(same for webapp/source* in tomcat)

**Comment by davecahill** [comment]
For info, I deleted /var/opengrok/data before last index, defs / refs still don't work (CentOS / Exuberant 5.8), so I'll see if I can find more info.

**Comment by ChristopheBordieu** [comment]
@tarzanek , I had deleted already all data when installing 1.1-rc5. So, it seems by a way or another, indexes were corrupted...  I am going to check Universal in dev because I am not sure it is working well based on my quick and dirty trials previous week...

**Comment by davecahill** [comment]
Looking at logs here, the only ctags related issue is a lot of the harmless-looking 'WARNING: Error from ctags: ctags: Warning: Language "pascal" already defined' and 'null expansion of name pattern "\2"'.

**Comment by tarzanek** [comment]
null expansion of name pattern is not good ... that needs to be fixed, @davecahill can you share the whole message? (I will try to repro, too)

**Comment by ChristopheBordieu** [comment]
All,
I close this issue. Whatever ctags I use, Exuberant or Universal, once index/historycache/xref have been cleaned, symbols or defs are searchable and results returned corectly.
(So I don't clearly understand the initial comment  of @tarzanek "yes, local vars are enabled only for universal ctags" but I close the issue anyway.)

**Comment by tarzanek** [comment]
index should have been enough, but for the sake of data sanity cleaning all is good

local variables in java don't work properly with exctags, so we only enable them with unictags

**Comment by ChristopheBordieu** [comment]
ok. thanks for clarification. made a trial. with both ctags, i am able to find local var in java. anyway, will update my envs to use universal ctags since it is more robust and efficient.
