### ISSUE TITLE
1.1-rc6 not able to search

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1680]
In the recent version I'm not able to search - always hit the invalid project error

![screenshot from 2017-07-24 14-26-26](https://user-images.githubusercontent.com/6997160/28523312-1e906f2a-707c-11e7-899a-7c8413c3dc6c.png)

projects enabled, projects are marked as indexed, they're present in the select box but still there is this error (even when I select just a subset)

I suspect the changes in #1663

**Comment by tulinkry** [comment]
```java

Set <Project> projectSet = projects.stream().
+                    map(x -> Project.getProject(x)).collect(Collectors.toSet());
+                if (projectSet.contains(null)) {
+                    errorMsg = "Project list contains invalid projects";
+                    return this;
+                }
```

the set always contains a null because the Project.getProject accepts a path relative to source root yet with absolute slash so /project instead of project.

**Comment by tulinkry** [comment]
using this looks better for me

`public static Project getByName(String name)`

**Comment by vladak** [comment]
Actually I remember changing `getByName()` to `getProject()`. I got confused by the tests in `SearchHelperTest.java` that pass project path to `prepareExec()`.

**Comment by tulinkry** [comment]
So also updating the doc would a nice step forward for this method :+1:

**Comment by vladak** [comment]
Well, primarily get the tests fixed.
