### ISSUE TITLE
.opengrok_skip_history not honored with non-embedded repositories

### ISSUE THREAD

**Issue by shaehn** [OpenGrok/OpenGrok#1720]
After looking at the placement of the .opengrok_skip_history code in HistoryGuru.java it is clear to me that its usage is for keeping repositories out of consideration during indexing when the –S option, search for repository, is in use (so a more appropriate name might be .ignore_repository :-). I suppose for what I will call embedded repositories, say like SCCS and the like, where the source control data for a directory is kept in an enclosed directory, the current code may work. For example, the following folder structure would keep project2 out of consideration for indexing.
```
source_code_root
    |
    |== project1
    |== project2
        |
        | == .opengrok_skip_history
        | == .SCCS
```

I propose modifying addRepositories in HistoryGuru.java to look into directories for the .opengrok_skip_history file so that its intent will work with non-embedded repositories, such as AccuRev.

**Comment by vladak** [comment]
The `addRepositories()` is actually buggy - If the traversal descends into the directory that happens to be a repository, it already added the repository to the list, so the check for the ".opengrok_skip_history" file inside will do nothing. It could never work I think.

**Comment by vladak** [comment]
Also, it's a question whether this mechanism should not be replaced by some stanza in `Configuration`. Relying on the presence of magic files is not very transparent or manageable.

**Comment by shaehn** [comment]
change set: a8c2792
