### ISSUE TITLE
Stuck at "Loading the default instance configuration"

### ISSUE THREAD

**Issue by totembe** [OpenGrok/OpenGrok#1732]
After deploying ppengrok-1.1-rc11, indexing stuck at "Loading the default instance configuration...".

I have reverted back to opengrok-.1.1-rc10 which was working and it is not working. 

I have deleted /var/opengrok completely and tried to regenerate from stratch and no avail.

And I am monitoring both tomcat8 and opengrok logs. There is no indication.

Only error I get is,

==> catalina.out <==
14-Aug-2017 11:07:57.871 INFO [localhost-startStop-1] org.opensolaris.opengrok.web.WebappListener.contextInitialized Could not load statistics from a file.
 java.io.FileNotFoundException: Statistics file is not set (null)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.loadStatistics(RuntimeEnvironment.java:1573)
	at org.opensolaris.opengrok.web.WebappListener.contextInitialized(WebappListener.java:122)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

What am I missing? There hasn't any configuration alteration or else.

**Comment by tarzanek** [comment]
if rc10 worked and after revert it isn't , there must have been some config change ;)

you can try to clean /var/opengrok and the binary dir , download 1.0 and try with it

the other option is to use strace / truss and check the java process
and also there is a log file in /var/opengrok/log - so you can always check that for what indexer is doing ...

**Comment by totembe** [comment]
I have completely emptied /var/opengrok and reindexing again with rc10. At the moment it is indexing and waiting for results. 

strace output of R11, it seems it is waiting for fileloghandler process. Output stops here wait for further action. "wait4(-1, Logging filehandler pattern: /var/opengrok/log/opengrok%g.%u.log"

root@debian64:/opt/opengrok-1.1-rc11/bin# OPENGROK_VERBOSE=on strace ./OpenGrok index /home/ethem/og/src
execve("./OpenGrok", ["./OpenGrok", "index", "/home/ethem/og/src"], [/* 24 vars */]) = 0
brk(0)                                  = 0x1cef000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe22c6c6000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("tls/x86_64/libc.so.6", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("tls/libc.so.6", O_RDONLY)         = -1 ENOENT (No such file or directory)
open("x86_64/libc.so.6", O_RDONLY)      = -1 ENOENT (No such file or directory)
open("libc.so.6", O_RDONLY)             = -1 ENOENT (No such file or directory)
open("/home/ethem/ora/instantclient_11_2/tls/x86_64/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/ethem/ora/instantclient_11_2/tls/x86_64", 0x7ffc5a71bfb0) = -1 ENOENT (No such file or directory)
open("/home/ethem/ora/instantclient_11_2/tls/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/ethem/ora/instantclient_11_2/tls", 0x7ffc5a71bfb0) = -1 ENOENT (No such file or directory)
open("/home/ethem/ora/instantclient_11_2/x86_64/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/ethem/ora/instantclient_11_2/x86_64", 0x7ffc5a71bfb0) = -1 ENOENT (No such file or directory)
open("/home/ethem/ora/instantclient_11_2/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/ethem/ora/instantclient_11_2", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/etc/ld.so.cache", O_RDONLY)      = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=106060, ...}) = 0
mmap(NULL, 106060, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fe22c6ac000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\357\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1607696, ...}) = 0
mmap(NULL, 3721272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe22c11c000
mprotect(0x7fe22c2a0000, 2093056, PROT_NONE) = 0
mmap(0x7fe22c49f000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x183000) = 0x7fe22c49f000
mmap(0x7fe22c4a4000, 18488, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe22c4a4000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe22c6ab000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe22c6aa000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe22c6a9000
arch_prctl(ARCH_SET_FS, 0x7fe22c6aa700) = 0
mprotect(0x7fe22c49f000, 16384, PROT_READ) = 0
mprotect(0x7fe22c6c8000, 4096, PROT_READ) = 0
munmap(0x7fe22c6ac000, 106060)          = 0
getpid()                                = 8255
rt_sigaction(SIGCHLD, {0x40f270, ~[RTMIN RT_1], SA_RESTORER, 0x7fe22c14e1a0}, NULL, 8) = 0
geteuid()                               = 0
brk(0)                                  = 0x1cef000
brk(0x1d10000)                          = 0x1d10000
getppid()                               = 8254
stat("/opt/opengrok-1.1-rc11/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat(".", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("./OpenGrok", O_RDONLY)            = 3
fcntl(3, F_DUPFD, 10)                   = 10
close(3)                                = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {0x40f270, ~[RTMIN RT_1], SA_RESTORER, 0x7fe22c14e1a0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_DFL, ~[RTMIN RT_1], SA_RESTORER, 0x7fe22c14e1a0}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, {SIG_DFL, ~[RTMIN RT_1], SA_RESTORER, 0x7fe22c14e1a0}, NULL, 8) = 0
read(10, "#!/bin/sh\n#\n# OpenGrok Wrapper ("..., 8192) = 8192
geteuid()                               = 0
stat("/bin/uname", {st_mode=S_IFREG|0755, st_size=31152, ...}) = 0
faccessat(AT_FDCWD, "/bin/uname", X_OK) = 0
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8256
close(4)                                = 0
read(3, "Linux\n", 128)                 = 6
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 6
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8256
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8257
close(4)                                = 0
read(3, "3.2.0-4-amd64\n", 128)         = 14
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 14
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8257
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8258
close(4)                                = 0
read(3, ".\n", 128)                     = 2
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 2
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8258
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8259
close(4)                                = 0
read(3, "/opt/opengrok-1.1-rc11/bin\n", 128) = 27
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 27
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8259
read(10, " \"${SCRIPT_DIRECTORY}/dist/sourc"..., 8192) = 8192
read(10, "NG: ${@}\" 1>&2\n    fi\n}\n\nError()"..., 8192) = 8192
read(10, "... \"\n        ${DO} mkdir -p \"${"..., 8192) = 8192
stat("/pkgs/sbin/CronExecutionEnvironment.sh", 0x7ffc5a71d1f0) = -1 ENOENT (No such file or directory)
stat("", 0x7ffc5a71d1d0)                = -1 ENOENT (No such file or directory)
write(1, "Loading the default instance con"..., 47Loading the default instance configuration ...
) = 47
stat("/opt/opengrok-1.1-rc11/bin/dist", 0x7ffc5a71c9b0) = -1 ENOENT (No such file or directory)
stat("/opt/opengrok-1.1-rc11/bin/dist/opengrok.jar", 0x7ffc5a71c9b0) = -1 ENOENT (No such file or directory)
stat("/opt/opengrok-1.1-rc11/bin/dist/source.war", 0x7ffc5a71c9b0) = -1 ENOENT (No such file or directory)
stat("", 0x7ffc5a71ca90)                = -1 ENOENT (No such file or directory)
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8260
close(4)                                = 0
read(3, "/usr/bin/ctags-exuberant\n", 128) = 25
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 25
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8260
faccessat(AT_FDCWD, "/var/opengrok/etc/ctags.config", R_OK) = -1 ENOENT (No such file or directory)
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8266
close(4)                                = 0
read(3, "/opt/jdk/jdk1.8.0_141\n", 128) = 22
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 22
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8266
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8272
close(4)                                = 0
read(3, "", 128)                        = 0
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8272
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8274
close(4)                                = 0
read(3, "", 128)                        = 0
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8274
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8276
close(4)                                = 0
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8276
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 8276
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8278
close(4)                                = 0
read(3, "/usr/bin/svn\n", 128)          = 13
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 13
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8278
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8280
close(4)                                = 0
read(3, "", 128)                        = 0
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8280
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8282
close(4)                                = 0
read(3, "", 128)                        = 0
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8282
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8284
close(4)                                = 0
read(3, "/usr/bin/git\n", 128)          = 13
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 13
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8284
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8286
close(4)                                = 0
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8286
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 8286
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8288
close(4)                                = 0
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8288
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 8288
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8290
close(4)                                = 0
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 8290
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 8290
read(10, "dateConfiguration\n        Create"..., 8192) = 379
geteuid()                               = 0
stat("/usr/bin/ctags-exuberant", {st_mode=S_IFREG|0755, st_size=250056, ...}) = 0
faccessat(AT_FDCWD, "/usr/bin/ctags-exuberant", X_OK) = 0
stat("/home/ethem/og/src", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/opengrok/data", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/opengrok/data", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/opengrok/etc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/opengrok/etc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/opengrok/logging.properties", {st_mode=S_IFREG|0644, st_size=2807, ...}) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe22c6aa9d0) = 8292
wait4(-1, Logging filehandler pattern: /var/opengrok/log/opengrok%g.%u.log

**Comment by tarzanek** [comment]
anything logged in /var/opengrok/log/opengrok%g.%u.log ?
another thing is to up the logging with OPENGROK_VERBOSE=true Opengrok ...

**Comment by totembe** [comment]
==> opengrok0.0.log <==
java.io.IOException: Message was not accepted by the remote server - 0 (error 0x4).
	at org.opensolaris.opengrok.configuration.messages.Message.throwIfError(Message.java:385)
	at org.opensolaris.opengrok.configuration.messages.Message.write(Message.java:307)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1238)
	at org.opensolaris.opengrok.index.Indexer.sendToConfigHost(Indexer.java:924)
	at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:622)

2017-08-14 21:04:36.003+0300 INFO t1 Indexer.sendToConfigHost: Configuration update routine done, check log output for errors.
2017-08-14 21:04:36.003+0300 INFO t1 Statistics.report: Total time: 20.574 seconds
2017-08-14 21:04:36.073+0300 INFO t1 Statistics.report: Final Memory: 66M/275M

**Comment by totembe** [comment]
root@debian64:/var/opengrok/log# cat opengrok2.0.log 
2017-08-14 23:27:34.296+0300 FINE t1 Executor.registerErrorHandler: Installing default uncaught exception handler


root@debian64:/opt/opengrok-1.1-rc11/bin# ./OpenGrok index /home/ethem/og/src
Loading the default instance configuration ...
Logging filehandler pattern: /var/opengrok/log/opengrok%g.%u.log

**Comment by totembe** [comment]
It has something with Project centric approach. After I start indexing with OPENGROK_ENABLE_PROJECTS=false option, it is no more hung.

**Comment by totembe** [comment]
I still got stuck. Configuration xml is not accepted somehow.

## ./OpenGrok index
15:07:43 SEVERE: Failed to send configuration to localhost:2424 (is web application server running with opengrok deployed?)
java.io.IOException: Message was not accepted by the remote server - 0 (error 0x4).
	at org.opensolaris.opengrok.configuration.messages.Message.throwIfError(Message.java:385)
	at org.opensolaris.opengrok.configuration.messages.Message.write(Message.java:307)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1238)
	at org.opensolaris.opengrok.index.Indexer.sendToConfigHost(Indexer.java:924)
	at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:622)

## ==> catalina.2017-08-15.log <==
15-Aug-2017 15:07:43.617 WARNING [configurationListener] org.opensolaris.opengrok.configuration.RuntimeEnvironment.handleMessage Message dropped: {0} - message error
 java.lang.ArrayIndexOutOfBoundsException: 0
	at java.beans.XMLDecoder.readObject(XMLDecoder.java:250)
	at org.opensolaris.opengrok.configuration.Configuration.decodeObject(Configuration.java:1196)
	at org.opensolaris.opengrok.configuration.Configuration.makeXMLStringAsConfiguration(Configuration.java:1181)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.applyConfig(RuntimeEnvironment.java:1667)
	at org.opensolaris.opengrok.configuration.messages.ConfigMessage.applyMessage(ConfigMessage.java:79)
	at org.opensolaris.opengrok.configuration.messages.Message.apply(Message.java:85)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.handleMessage(RuntimeEnvironment.java:1809)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment$9.run(RuntimeEnvironment.java:1769)
	at java.lang.Thread.run(Thread.java:748)

## ==> opengrok2.0.log <==
java.io.IOException: Message was not accepted by the remote server - 0 (error 0x4).
	at org.opensolaris.opengrok.configuration.messages.Message.throwIfError(Message.java:385)
	at org.opensolaris.opengrok.configuration.messages.Message.write(Message.java:307)
	at org.opensolaris.opengrok.configuration.RuntimeEnvironment.writeConfiguration(RuntimeEnvironment.java:1238)
	at org.opensolaris.opengrok.index.Indexer.sendToConfigHost(Indexer.java:924)
	at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:622)

2017-08-15 15:03:26.879+0300 INFO t1 Indexer.sendToConfigHost: Configuration update routine done, check log output for errors.
2017-08-15 15:03:26.879+0300 INFO t1 Statistics.report: Total time: 14.9 seconds
2017-08-15 15:03:26.959+0300 INFO t1 Statistics.report: Final Memory: 66M/263M

**Comment by totembe** [comment]
After doing clean install, it is working. Still it can't send new configuration to server, it does not affect functionality. I am closing this issue. Sorry for disturbance.
