### ISSUE TITLE
How to enable History & Annotate in Opengrok

### ISSUE THREAD

**Issue by venkateshp651** [OpenGrok/OpenGrok#1733]
Hello,

I've configured Opengrok for one of our projects (hg) using the instructions from "https://github.com/OpenGrok/OpenGrok/wiki/How-to-install-OpenGrok "  , and all the search features are working fine. But however 'History' (H) link is NOT enabled. I did some research and found that a local CVS repository must be available in order to fetch the revisions. Then I've installed CVS in my unix box and checked out my project from hg to CVS ROOT folder (I'm pretty new to CVS, not sure this is correct) and changed the configs and re-ran the tomcat. But still the history links are not enabled. I didn't find any links/documents related to this topic. Can anyone please help me pointing to right link to setup the history? 

versions used:
OS: Cent OS
Opengrok-1.1-rc8
Tomcat 8
JDK 1.8
Mercurial hg  1.8.2

Thanks a lot in advance
-Venkatesh

**Comment by tarzanek** [comment]
if your project is in hg, then index a hg clone of your project, opengrok plays MUCH better with mercurial(hg) and git than with cvs
with cvs your tomcat has to have access to remote cvs repo to get the history (and indexer as well)

**Comment by venkateshp651** [comment]
Thank you so much tarzanek for your reply. I will try that :)

**Comment by vladak** [comment]
I am not sure I got the part about mixing Mercurial with CVS - this makes no sense to me until you provide the exact commands executed.

In order for the history/annotate to work, the webapp must be able to get some data from `cvs log` command run in the repository - try running the command for a few files under the same user the Tomcat runs under and you'll see if it works or not.

**Comment by vladak** [comment]
There seems to be lack of response, hence closing; feel free to reopen.

**Comment by alokprasad** [comment]
i have repo of git, but same issue.anything specific needs to be done to get history of file in opengrok

**Comment by vladak** [comment]
Running the indexer with -H should be sufficient.
