### ISSUE TITLE
Can we ignore some files or file folders when doing index operation? 

### ISSUE THREAD

**Issue by fcharming** [OpenGrok/OpenGrok#1734]
For example,when doing index,some kinds of file such as *so or *jar which is not readable ,I dont want take them into consideration.
Or assuming another situation, we don't want some folder in source code path appear in web.
Can we just ignore it?like .gitignore.

**Comment by tarzanek** [comment]
yes -I or -i should have the power to do this , resp. -i should be used:
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/CommandLineOptions.java#L86

**Comment by vladak** [comment]
Use IGNORE_PATTERNS env var for the OpenGrok shell script or the -i option uf you run via the opengrok.jar. wildcards are supported.

**Comment by fcharming** [comment]
@vladak thaks for you helo! Do just opengrok.jar have the -i option? what about ./bin/OpenGrok index?

**Comment by vladak** [comment]
OpenGrok shell script takes environment variables (see its cobtents for details), opnegrok.har takes options (run it with -h for details).

**Comment by fcharming** [comment]
@vladak Below is my command,something wrong?

lenovo@nfsserver:/usr/tools/opengrok-1.0/bin$ IGNORE_PATTERNS=*so ./OpenGrok index /home/lenovo/work/tt
Loading the default instance configuration ...
Error getting source root from environment. Exiting.
