### ISSUE TITLE
Solarized Color Style / Syntax highlighting

### ISSUE THREAD

**Issue by neerajbadlani** [OpenGrok/OpenGrok#1742]
Is it possible to have solarized dark style for syntax highlighting as an added option ?

**Comment by vladak** [comment]
It should be possible to add your own styles and specify them using the `SKIN` env var (in the `OpenGrok` shell script) or via the `-L` option to opengrok.jar. As for bundling styles in OpenGrok, we just recently removed non-default styles (#1481) so I guess this action answers that part. If you find some issues when overriding styles in default's `style.css`, feel free to reopen.
