### ISSUE TITLE
how to config secure ldap (ldaps)

### ISSUE THREAD

**Issue by guy3145** [OpenGrok/OpenGrok#1744]
Hi
we currentlly using ldap and we would like to move to ldaps.
im looking for a guide on how to configure it.
thanks!

**Comment by vladak** [comment]
Not sure how this is related to OpenGrok ?

**Comment by guy3145** [comment]
can you help pointing me where to look?
opengrok is installed on ubuntu with tomcat

**Comment by guy3145** [comment]
im using ldap to connect to opegrok...

**Comment by vladak** [comment]
In what way are you using LDAP to connect top opengrok ? You will have to supply some details in order to get some meaningful response.

**Comment by guy3145** [comment]
ldap is configured in server.xml just need instruction to change to ldaps
<Realm className="org.apache.catalina.realm.JNDIRealm"
          connectionURL=

**Comment by tarzanek** [comment]
http://support.rundeck.com/customer/en/portal/articles/2433205-configuring-tomcat-for-ldaps ?
(this Q is a bit offtopic on opengrok forums ... isn't it?)

**Comment by guy3145** [comment]
thanks!
sorry for the offtopic i thought its a opengrok thing...

**Comment by vladak** [comment]
OpenGrok is just a webapp running in Tomcat container so any Tomcat specific LDAP setting is completely opaque to OpenGrok unless you are utilizing OpenGrok's authorization framework.

**Comment by tarzanek** [comment]
actually ... if you would write up a howto on ldap/ldaps with tomcat and opengrok it'd be cool, I would like to see it on wikis https://github.com/OpenGrok/OpenGrok/wiki
then with a how to it would be an opengrok thing and wouldn't be off topic anymore! :)
Share your howto!
