### ISSUE TITLE
Project search selection is not preserved upon subsequent navigation

### ISSUE THREAD

**Issue by CannedYerins** [OpenGrok/OpenGrok#1751]
Hi,

Sorry if this is a duplicate.  I searched briefly but I'm pretty bad at searching GitHub issues.

When I execute a search on OpenGrok (let's use this as an example http://src.couchbase.org/source/) with multiple projects selected, and then pick a file to view, navigating to any linked non-local symbol in that file executes a search restricted to the project the file itself is in, throwing away my previous project selection.

So if you select all projects at couchbase, search for file "SigarTestPrinter", pick the first in the list (in the 1.7.0 project), and click on the "Version" symbol imported in the resulting page, you're only seeing results from the 1.7.0 project.

That's a bit surprising to me as a user.  I think it's unlikely that a hypothetical user's intent for the search's project scope has changed after navigating to one file in the search results.  I suppose this couchbase instance is a not-too-great example because most of the projects are just different versions of the same code (whereas my use case, and, I'd guess, the generally more common use case is to have many truly distinct projects in one OpenGrok instance), but even in this example I feel like the case for retaining the all-projects search is more compelling than not.

I see when I'm viewing the first file I still have the "OpenGrokProject" cookie including all of the projects I selected in the original search.  Is it possible that the search links on the page could include the contents of this cookie?

Thanks!

**Comment by vladak** [comment]
seems like a dup of #1447

**Comment by CannedYerins** [comment]
Got it, thanks.

**Comment by CannedYerins** [comment]
I think that is basically the same except that reporter talks about the search box and I am talking about the links on the page.  Same problem otherwise.
