### ISSUE TITLE
Add PowerShell Analyzer to OpenGrok

### ISSUE THREAD

**Issue by shaehn** [OpenGrok/OpenGrok#1753]
I would like to add a Windows PowerShell analyzer to the OpenGrok system. Initially it will be based off of the current Shell analyzer and proceed from there.

**Comment by tarzanek** [comment]
cool idea, go for it, setup a lexer, ev. set rules for ctags (check universal ctags, maybe it already supports powershell),
any Qs ask here, we will try to guide you

**Comment by shaehn** [comment]
Thanks for encouragement. How do I get questions answered?  I have tried posting to opengrok-dev@yahoogroups.com, but that so far seems to be like the proverbial black-hole, nothing comes back out.

**Comment by tarzanek** [comment]
ask here in the scope of the issue, will be the fastest

**Comment by shaehn** [comment]
OK,  I have most of the items for PowerShell analysis set up. I have one last item I would like to add so that the Scopes mechanism will work also.  I have added the incScope, decScope, and endScope calls in the PoshXref.lex file. This gets me the name of the functions when I play with the Scopes feature, but after each name is 'null'. I tracked this down to being a missing signature (params to functions). I see that there is a setSignature method in Scopes.java, but when I looked to see how other modules used this, I could find no other references. So how are the other Analyzers doing this?

**Comment by shaehn** [comment]
I have some new ctag –regex options for PowerShell.
I see that the initialization code inside Ctags.java is getting huge with new strings added for new languages.
There is even a comment inside indicating that the command line is eventually going to get too long.

I note that ctags has an –options=  flag which allows as its value a directory. The directory will be scanned
for all the *.ctag, or *.conf files it can find.  Would it be reasonable to change the Ctags.java initialization code so that
it looks in some standard place(s) for a ‘tags’ directory and we can then add *.conf files to that directory when
new languages are going to be added instead of having to modify Ctags.java. For example,

tags/PowerShell.conf
tags/swift.conf
tags/scala.conf …

Also, during my testing, ctags is complaining about already having tags for 'rust' and a few other languages. Should those items be removed?

**Comment by tarzanek** [comment]
the warnings about "rust" and others can be ignored, some of the analysis was back then better in Opengrok, so it needs investigation if they ctags analyzer is better/newer than the regexp

the ctags conf file - this needs to be carefully done with the file that can be passed to opengrok and merged together ... but yes, creating directory tags and having opengrok generate files there would be better than storing them inside ctags.java ... care to open this as separate patch? (bare in mind the option opengrok has to provide custom conf file)

and yes to get scopes working, ctags need to be working properly for method calls ...

**Comment by shaehn** [comment]
I need an answer to my question about function signatures too please. (before the one about tags)

**Comment by shaehn** [comment]
Ok, I found the stuff inside Ctags.java that is dealing with signatures. It looks like it is expecting the ctags program to provide the signature component. I will have to go read the ctags documentation to see how to activate it, because it doesn't come for free.

**Comment by tarzanek** [comment]
yes, you need the regexp that will detect that
however, you can push what you have and add this later, I like when contributions come in smaller packages, integration is easier and there is no hold up.
Divide & conquer !

**Comment by shaehn** [comment]
Too late for smaller packaging, I am pretty much finished. I do have some niggling problems. I cannot get the Mirror display on the front page. I do see that the projects have the "indexed" element set to true. So how do I debug a .jsp file?  I have an attached netbeans debugger onto Tomcat server. Netbeans does not let me set a break point. Do I need some special netbeans plugin or some other configuration mechanism.

![image](https://user-images.githubusercontent.com/13596544/30136042-362b6f00-932b-11e7-8732-3d739a2a758c.png)

**Comment by tarzanek** [comment]
you need to open project  opengrok-web-nbproject/
have properly setup tomcat in netbeans (not sure if it works with latest tomcat ... I had some issues lately and didn't try since then)
then open the web/index.jsp and setup breakpoints and run debug from netbeans on top of above project

**Comment by shaehn** [comment]
Here is my following setup on my Windows box:
Using apache-tomcat-8.5.16 and have set the environment variable:
CATALINA_OPTS =  -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
I have actually been trying what you mentioned earlier, but to no avail.
![image](https://user-images.githubusercontent.com/13596544/30168197-ae50b8ce-93b6-11e7-83bd-439361dad66a.png)
I select the toggle break point menu item, but no red dot is set that indicates that any action has taken place.

**Comment by shaehn** [comment]
Hmm....  I just opened the file index.jsp, not a project. So I poked around and found the following:
(It shows that it does not recognize this as a project and is asking if I am missing a plugin. What plugin would that be?
![image](https://user-images.githubusercontent.com/13596544/30168584-d7cef66a-93b7-11e7-9bf6-32e2fc96ab78.png)

**Comment by shaehn** [comment]
I am using netbeans-8.2-javase-windows.exe

**Comment by shaehn** [comment]
I pushed up the code that I currently have for the moment. Do I need to enter a pull request to get it looked at?  If elements are satisfactory, when do pull requests get incorporated into main branch? I have one other pull request which Vlad had looked at. It is still marked for "Changes Requested", but I don't know if that is just because Vlad has not re-reviewed what I pushed up there or not.

**Comment by shaehn** [comment]
Travis Build is broken and I have no idea what to do.  I need some help at this point.

**Comment by tarzanek** [comment]
let me have a look at the pull request
travis build uses still old exuberant ctags, since universal ctags are not packaged for ubuntu (yet)

**Comment by tarzanek** [comment]
I have restarted the Travis, it seems there is some race in some other tests which got triggered, I will file a separate issue for that, let's see if it will pass for second try

**Comment by shaehn** [comment]
Since the PowerShell analyzer depends on the Universal Ctags, and Travis is not using it, this whole effort has been a waste of time. The build is never going to succeed.

**Comment by shaehn** [comment]
Am I not seeing the opengrok-web-nbproject as a project because I am using the SE version of Netbeans install instead of EE version?

**Comment by tarzanek** [comment]
no, the build will be OK, don't worry, let's make this happen, the travis look to me like it is failing on auth plugins, I will meet Krystof tomorrow and ask him to take a look

regarding netbeans I always use the full .zip , so yes, SE version might not work properly with the web project
- this is the zip I use: https://netbeans.org/downloads/start.html?filename=zip/netbeans-8.2-201609300101.zip

**Comment by tarzanek** [comment]
fwiw - I have in ctags java several languages that try to work their way with exuberant ctags as a simplistic implementation and eventually leverage the support in universal ctags

**Comment by tarzanek** [comment]
so don't panic ;)

**Comment by vladak** [comment]
addressed in cset e7aa2981919474db65fd7bf632add0a32a750ae3
