### ISSUE TITLE
Incomplete filetypes list for PL/SQL

### ISSUE THREAD

**Issue by mbaluda** [OpenGrok/OpenGrok#1763]

**Comment by mbaluda** [comment]
OpenGrok does not include a full list of file name extensions for pl/sql sources, in particular PKB and PCK are missing in /src/org/opensolaris/opengrok/analysis/sql/PLSQLAnalyzerFactory.java
cfr: http://www.orafaq.com/wiki/File_extensions

**Comment by tarzanek** [comment]
I can add the types, should be a quick fix ...

**Comment by tarzanek** [comment]
(or you can whip up a patch and ask for a pull req, it's easy)

**Comment by tarzanek** [comment]
ctags --list-maps 
will print out what extensions are supported where ....

**Comment by mbaluda** [comment]
Super, shell I update the documentation?
https://github.com/OpenGrok/OpenGrok/wiki/Supported-Languages-and-Formats

**Comment by tarzanek** [comment]
yes please, would be lovely if you do
