### ISSUE TITLE
Selecting folding icon next to function causes jump to top of web page

### ISSUE THREAD

**Issue by shaehn** [OpenGrok/OpenGrok#1764]
Tested against OpenGrok 1.0, Tomcat 8.5.16

This is a very simple fix inside of JFlexXref.java:521  Instead of using href="#" to get the cursor to change (it is this reference to nowhere which causes the page activity), put in its place, style='cursor:pointer;'

**Comment by vladak** [comment]
could you try with 1.1 RC and various browsers ?

**Comment by shaehn** [comment]
Vlad, I am not sure how to reference what you have called 1.1 RC. I am using the OpenGrok that is on the main branch here at GitHub.  I tested on Chrome, Firefox, and Internet Explorer. They all exhibited bad behavior of jumping to top of page after selecting folding icon. I then modified the mentioned line in the code and tested again in those 3 browsers and they behaved more as I expected, lines associated with the fold disappearing without moving the page.

**Comment by vladak** [comment]
The RC's (release candidates) are on https://github.com/OpenGrok/OpenGrok/releases

As for when developing in your fork, usually one grabs the latest changeset that is common to the upstream and references that, e.g. "I am on cset XYZ", implying that the changesets added on top of that do not influence the issue in question.

It seems that you've done sufficient testing so feel free to open a pull req.

**Comment by vladak** [comment]
Noticed that too on 1.1-rc10.
