### ISSUE TITLE
README claims "Sample configuration file for Solaris code base is delivered in the doc/ directory" but that doesn't seem so

### ISSUE THREAD

**Issue by idodeclare** [OpenGrok/OpenGrok#1775]
It is missing when I check opengrok-1.1-rc13.tar.gz.

**Comment by tarzanek** [comment]
d'oh!
we use the same readme for source and for binary ...
so it refers of course to https://github.com/OpenGrok/OpenGrok/tree/master/doc
I guess this should be fixed in the README ...

**Comment by tarzanek** [comment]
(care to file a pull req? I'll gladly approve  ;-) )
