### ISSUE TITLE
switch xref directory list ordering to criteria preferring directories

### ISSUE THREAD

**Issue by TerraTech** [OpenGrok/OpenGrok#1776]
It would be easier on the eyes, and navigation if the directories were sorted/grouped to the top with files below.

Right now:
```
..
AUTHORS
ChangeLog
config/
Makefile.am
NEWS
po/
README
README.md
resources/
src/
```

Would like to see it as:
```
..
config/
po/
resources/
src/
AUTHORS
ChangeLog
Makefile.am
NEWS
README
README.md
```
What makes it even more difficult is the lack of margin space on the left.  Your eyes are contending with reading text that is so close to the edge of your monitor.  I can see how this would be nice for laptops, but working on a widescreen desktop monitor, it is fatiguing.  At least a knob or something to tweak this UI experience would be nice.

**Comment by vladak** [comment]
The ordering option sounds good to me. As for the margin, can you maybe post a screenshot of your situation ? Also, what browser is this visible with ?

**Comment by TerraTech** [comment]
@vladak  the file/directory ordering would be a nice change.  Thank you for making it seem it will become reality.  :)

In regards to the margin, I think the main issue is it being so close to the left screen edge coupled with all the empty whitespace on the right side.  Here is a screenshot link.
https://drive.google.com/file/d/0B9L0eDJu-2GMczljWl9laVFISmc/view?usp=sharing

Browser is Chrome Version 61.0.3163.79 (Official Build) (64-bit)

FWIW - I also found another oddity with version opengrok-1.0 and I'm not sure if it is intended or not.  Please view what the red arrows are pointing out:
https://drive.google.com/file/d/0B9L0eDJu-2GMelM0czFXRS15YTA/view?usp=sharing

Thanks!

**Comment by TerraTech** [comment]
@vladak should I create a separate issue for the layout items?

**Comment by vladak** [comment]
Feel free to submit pull request for the ordering change, should be easy even for non-Java programmer.

As for the margin, according to your description I thought there is no margin at all however there is one so I am at loss w.r.t. how to fix this.

For the functions headings sticking out pls create separate issue.

Also, do not be afraid to attach screenshots to github issues, it works nicely.
