### ISSUE TITLE
where do i get the wrapper script?

### ISSUE THREAD

**Issue by ICEDLEE337** [OpenGrok/OpenGrok#1788]
The documentation states the following: `For *nix systems there is a shell script called OpenGrok which simplifies most of the tasks. It has been tested on Solaris and Linux distributions` but where can I obtain this wrapper script? (This probably isn't the proper place for question either, so sorry and) Thanks!

**Comment by ICEDLEE337** [comment]
nvm. i found it => https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok.

**Comment by tarzanek** [comment]
it also should be part of your zip file, resp. package for your OS, if it isn't then it's a prob! :)
