### ISSUE TITLE
jQueryUI tooltip prevents navigation on files with long filenames

### ISSUE THREAD

**Issue by emergie** [OpenGrok/OpenGrok#1795]
This is very annoying.

firefox:
![peek 2017-09-30 12-32](https://user-images.githubusercontent.com/2456881/31045441-314af1ce-a5e4-11e7-9aa3-81150eaf188e.gif)

chrome:
![peek 2017-09-30 12-55](https://user-images.githubusercontent.com/2456881/31045442-36053e4a-a5e4-11e7-84c6-5fd1bed3895b.gif)

To fix remove `$('a.result-annotate').tooltip()` from utils-0.0.15.js.

IMO standard browser tooltips are good enough:
![selection_009](https://user-images.githubusercontent.com/2456881/31045461-df493254-a5e4-11e7-936f-489c92208631.png)

**Comment by vladak** [comment]
Feel free to submit pull req for this.
