### ISSUE TITLE
Change program option parsing to handle long form options (ie. --switch)?

### ISSUE THREAD

**Issue by shaehn** [OpenGrok/OpenGrok#1803]
OpenGrok has just about used all the Latin alphabet up in choosing options names due to the limitation of a single character per option. Would you/we be interested in being able to parse the long form of switches?  I have a working model, ala ruby style, taking advantage of the java 8 lambda expressions and Consumer interface. This allows the documentation and the handling of the option to coalesce in the same region (unlike what is present today).  If interested, what would be the best way for me to present this new 'library/functionality' so that it can be critiqued before full incorporation into Indexer.java?

**Comment by vladak** [comment]
Yeah, proposed already in #1503. Feel free to submit a pull req.

**Comment by shaehn** [comment]
Realize that this will be a radical departure from getopt mechanism.  Enclosed is sample:

![image](https://user-images.githubusercontent.com/13596544/31140797-8bc36c2e-a843-11e7-89c0-e82b620e2b19.png)


I will use #1503 for the issue number and we can close this one out.

**Comment by shaehn** [comment]
Usage output will look like this:

![image](https://user-images.githubusercontent.com/13596544/31141127-7b070778-a844-11e7-8034-c67f5a1980eb.png)

**Comment by shaehn** [comment]
I have some questions that needs answering before I go any further.  I have a complete working solution for OptionParser.java along with a Junit test OptionParserTest.java. Before I go and start ripping apart the Indexer.java file, I would like to get this code reviewed (because I know there are always asks to change things and I don't want to have monkey around reworking Indexer.java because of changes to OptionParser). May I just submit a pull request for what I have so far to get the review going?

Once the reviewing is satisfied, do I continue with this issue to handle the Indexer.java changes, or do I use another issue (say #1503, even though it is assigned to Vlad)?

**Comment by vladak** [comment]
Just submit a pull request and we will go from there. To paraphrase recommendation from internal architecture process (that is relevant to wholly different piece software but it applies anyway): send pull requests early and often.

I've removed myself from #1503 so it is free now :-)

**Comment by vladak** [comment]
closing as dup of #1503
