### ISSUE TITLE
markdown readme is rendered twice

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1818]
When readme is in markdown we process it and display the converted html. However it is displayed again unprocessed.

<img width="773" alt="screen shot 2017-10-11 at 12 13 44" src="https://user-images.githubusercontent.com/6997160/31434797-b16a05ba-ae7d-11e7-9395-73144b484a3f.png">
<img width="656" alt="screen shot 2017-10-11 at 12 13 54" src="https://user-images.githubusercontent.com/6997160/31434799-b1827122-ae7d-11e7-92bd-f77fce53d7a6.png">

This is regression of something cause I remember this wasn't happening when I implemented the markdown conversion.

**Comment by vladak** [comment]
time for unit test then..
