### ISSUE TITLE
Rename IGNORE_PATTERNS to OPENGROK_IGNORE_PATTERNS

### ISSUE THREAD

**Issue by tulinkry** [OpenGrok/OpenGrok#1823]
OpenGrok script contains a way to add ignored names to jar file with env variable

```bash
    # OPTIONAL: Ignore these patterns as names of files or directories
    #IGNORE_PATTERNS="-i dummy"
```

this variable should follow our convention with OPENGROK_ prefix.

Also a note should be added to readme/doc that this can be used (without directly calling the jar file)

**Comment by vladak** [comment]
I think that a good general practice with environment variables processing in the `OpenGrok` script would be to avoid passing the options to `opengrok.jar` verbatim. For ignore patterns, the env var needs to hold multiple entries. Given that the patterns are used to match not only path components, but also paths (`IgnoredDirs` can match paths relative to source root), some uncommon separator char should be used (say `%` or something like that).

**Comment by tulinkry** [comment]
```bash
IGNORE_PATTERNS="-i dummy"
IGNORE_PATTERNS="$IGNORE_PATTERNS -i tmp"
IGNORE_PATTERNS="$IGNORE_PATTERNS -i f:package.json"
```

I'm not sure why there is need for a separator or am I missing something?

**Comment by vladak** [comment]
I just wanted to isolate the env vars from `opengrok.jar` options. Most of the other OPENGROK_ env vars do not include command line switches, so your proposal would get us on the slippery slope. Once the `OpenGrok` script is converted to Python we can have proper JSON/YAML config (maybe even within optargs).
