### ISSUE TITLE
Cant search Russian word

### ISSUE THREAD

**Issue by Teriand** [OpenGrok/OpenGrok#1825]
When i search any russian word, i get nothing.

ex:
/source/search?project=BalanceStorage&q=*%D0%B8%D1%85%D0%B0%D0%B8%D0%BB*&defs=&refs=&path=&hist=&type=
result:
Your search full:*ихаил* did not match any files. 

in XREF file with this word:
`
<a class="l" name="4" href="#4">4</a>Changeset 1499224 | TFS#1360809 | Checked in by &#1050;&#1091;&#1087;&#1095;&#1091;&#1082; &#1052;&#1080;&#1093;&#1072;&#1080;&#1083; &#1043;&#1077;&#1086;&#1088;&#1075;&#1080;&#1077;&#1074;&#1080;&#1095; | Balance recalculation procedure updated to support big intermediate values during calculation process`

Original file in UTF8
4 Changeset 1499224 | TFS#1360809 | Checked in by Купчук Михаил Георгиевич | Balance recalculation procedure updated to support big intermediate values during calculation process

versions:
OpenGrok-1.0
oracle-java8 8u121-1~webupd8~0          
tomcat8  8.5.14-1+deb9u1 
SMP Debian 4.9.30-2+deb9u2 (2017-06-26)

**Comment by tarzanek** [comment]
what locale is used ?

**Comment by Teriand** [comment]
locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by tarzanek** [comment]
can you attach the file with russian word here ?

**Comment by emergie** [comment]
Is it supposed to work at all?

`PlainFullTokenizer.lex` uses basic latin alphabet.

For example search attempt for _zajączek_ results in:
`+full:zaj +full:czek_freetext +hist:zaj +hist:czek_hist +path:zajączek_file`


``` java
@Test
public void testGetQueryZajaczek() throws Exception {
    SearchEngine instance = new SearchEngine();
    instance.setHistory("zajączek_hist");
    instance.setFile("zajączek_file");
    instance.setFreetext("zajączek_freetext");
    assertTrue(instance.isValidQuery());
    assertEquals("will fail", instance.getQuery());
}
```

```
    [junit] Testcase: testGetQueryZajaczek(org.opensolaris.opengrok.search.SearchEngineTest):	FAILED
    [junit] expected:<[will fail]> but was:<[+full:zaj +full:czek_freetext +hist:zaj +hist:czek_hist +path:zajączek_file]>
    [junit] junit.framework.AssertionFailedError: expected:<[will fail]> but was:<[+full:zaj +full:czek_freetext +hist:zaj +hist:czek_hist +path:zajączek_file]>
    [junit] 	at org.opensolaris.opengrok.search.SearchEngineTest.testGetQueryZajaczek(SearchEngineTest.java:172)
```

**Comment by Teriand** [comment]
original file in attach
[history.txt](https://github.com/OpenGrok/OpenGrok/files/1405980/history.txt)

**Comment by tarzanek** [comment]
well some analyzers do try to save all the UTF chars, but all of them will need to be improved in how much they do it ...

**Comment by Teriand** [comment]
is there a chance to fix it using the settings? Or need pr?

**Comment by tarzanek** [comment]
changes need to happen in lexers, java code is mostly ready for this(UTF support) for a long time, but lexers somehow lag behind (even though they can read UTF, they later on don't use it for index, since they only consume/read ASCII chars) 
I have some changes to lexers that increase this support, but they are at a very early state (I mostly tried to sync plain analyzers from lucene to OpenGrok, lucene does better job here)
& if you want to try it, I did some description in #1391
(but it needs more work to get it stable)

**Comment by tarzanek** [comment]
I think Russian should be in ExtendNumLetEx group for the UTF standard or ComplexContextEx ?
anyways we basically need more such groups in our full tokenizers and then grok will behave properly ...

**Comment by Teriand** [comment]
I can help to check, only I need builds with changes from # 1391
Where can I get them?

**Comment by tarzanek** [comment]
#1391 lists what is needed to put into your PlainTokenizer lex file ... 
see https://github.com/OpenGrok/OpenGrok/pull/1391#issuecomment-306165170

**Comment by Teriand** [comment]
with u comment:
`

    [jflex]
    [jflex] Error in file "/opt/opengrok/opengrok-git/OpenGrok-master/generatedsrc/org/opensolaris/opengrok/analysis/plain/PlainFullTokenizer.lex" (line 66):
    [jflex] Unexpected end of file in action code
    [jflex]
    [jflex] {Identifier}|{Number}|{Printable} { // below assumes locale from the shell/container, instead of just US
    [jflex]
`

**Comment by tarzanek** [comment]
yes, comment out the first {Identifier}|{Number}|{Printable} { // below assumes locale from the shell/container, instead of just US
since it's picked up by later
I will try to make it a pull request so you can get the patch directly

**Comment by Teriand** [comment]
1st try - get error 
`
 [javac] /opt/opengrok/opengrok-git/OpenGrok-master/generatedsrc/org/opensolaris/opengrok/analysis/plain/PlainFullTokenizer.java:751: error: incompatible types: boolean cannot be converted to int
    [javac]                         return true;
`
change  true to 1

2. 
`
 [javac] /opt/opengrok/opengrok-git/OpenGrok-master/src/org/opensolaris/opengrok/analysis/FileAnalyzer.java:187: error: constructor PlainSymbolTokenizer in class PlainSymbolTokenizer cannot be applied to given types;
    [javac]     protected JFlexTokenizer SymbolTokenizer=new PlainSymbolTokenizer();
`

I think the best way for me to wait for a full PR

**Comment by tarzanek** [comment]
yes, let me open a new PR, sharing diffs in github comments is not good

**Comment by Teriand** [comment]
mb changle label to enhancement ?

**Comment by idodeclare** [comment]
I found success by simply the Plain[Full,Symbol]Tokenizers just to include `\p{Letter}` in the {Identifier} initial character match and including both `\p{Letter}` and `\p{Number}` in the continuing characters.

E.g., from:
    `Identifier = [a-zA-Z_] [a-zA-Z0-9_]*`
to:
    `Identifier = [a-zA-Z\p{Letter}_] [a-zA-Z\p{Letter}0-9\p{Number}_]*`

**Comment by Teriand** [comment]
I change in this files:
\src\org\opensolaris\opengrok\search\context
HistoryLineTokenizer.lex
PlainLineTokenizer.lex

\src\org\opensolaris\opengrok\analysis\plain
PlainFullTokenizer.lex

and its work!

**Comment by tarzanek** [comment]
cool, if Letter is enough, then let's do it! 
(the original merge I had from lucene tokenizers is much more complicated and I basically didn't finish it due to lack of testing, but Letter doesn't need testing at all ... )

**Comment by tarzanek** [comment]
will you open a PR @Teriand ?

**Comment by Teriand** [comment]
yes, i can open, but need more info about change Identifier in other file.
in src\org\opensolaris\opengrok\analysis\*\*Tokenizer.lex need change?

**Comment by idodeclare** [comment]
@Teriand , I do not believe right now any language-specific lexer should be changed. Those will probably need new, specific samples of non-English input — that is valid for each language — to verify the lexers' functionality via their unit tests.

**Comment by tarzanek** [comment]
I agree, let's start with the plain text first
