### ISSUE TITLE
`OpenGrok index` now aborts with "** Unknown option: -a"

### ISSUE THREAD

**Issue by idodeclare** [OpenGrok/OpenGrok#1836]
I think this is related to the new OptionParser.

**Comment by idodeclare** [comment]
A quick reconciliation shows the options below from Indexer.java no longer there.

-a [... cfg.setAllowLeadingWildcard(]
-B [cfg.setUserPage(]
-C [cfg.setPrintProgress(true);]
-D [cfg.setHandleHistoryOfRenamedFiles(]
-K [listRepos = true;]
-k [zapCache.add(]
-L [cfg.setWebappLAF(]
-N [allowedSymlinks.add(]
-X [cfg.setUserPageSuffix(]
-y [noindex = true;]
-z [cfg.setScanningDepth(]

**Comment by shaehn** [comment]
yes, that is correct. Indexer.java was changed at the request of owner to remove those single character options in favor of long option names.  I knew that it would be a breaking change, but 'them' was my marching orders.

**Comment by idodeclare** [comment]
OK — I think though that you attended to the OpenGrok script, but it needs a bit more work.

**Comment by shaehn** [comment]
Ok,  I see it.  I don't use this script. Did you happen to see any more?   I tried an eyeball search, then a regular expression search to locate any -<singleCharacter> and I still missed the -a that you found.

**Comment by idodeclare** [comment]
Yes:
* several 1-char options used in the ClearHistory() function
* function StdInvocation is run at one point with -y
* a comment has SKIN= set to use -L

**Comment by shaehn** [comment]
Thank you. I found them,
-k : --deleteHistory
-y: --updateConfig
-L: --style

**Comment by vladak** [comment]
Fixed in
