### ISSUE TITLE
Message was not accepted from Indexer

### ISSUE THREAD

**Issue by idodeclare** [OpenGrok/OpenGrok#1838]
Running a build from a recent master aborts with the following:

09:38:48 SEVERE: Unexpected Exception
java.io.IOException: Message was not accepted by the remote server - The message tag must be either setconf, getconf, auth or set (error 0x4).
	at org.opensolaris.opengrok.configuration.messages.Message.throwIfError(Message.java:385)
	at org.opensolaris.opengrok.configuration.messages.Message.write(Message.java:307)
	at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:234)

**Comment by vladak** [comment]
Does this get triggered by actually sending the message (via the `Messages` tool) or during reindex ?

**Comment by vladak** [comment]
I think the culprit is clear:

```
            if (addProjects && host != null && port > 0) {
                Message m = Message.createMessage("config");
                m.addTag("addOption");
```

the tag changed from "set" in e6e4c3ccb9f0bf69cf4af8fcefae34853f0dae62.
