### ISSUE TITLE
How to exclude n files(full path) from search results?

### ISSUE THREAD

**Issue by senthilkumarsh** [OpenGrok/OpenGrok#1849]

**Comment by vladak** [comment]
Use the `NOT` operator (or `!`).

**Comment by senthilkumarsh** [comment]
Thing is we may need to exclude 100s of files which are listed in a external text file.

**Comment by vladak** [comment]
So, do you actually want to avoid indexing the files ?

**Comment by senthilkumarsh** [comment]
no, just want to exclude from search result when specific search criteria is choosen

**Comment by vladak** [comment]
Without telling us what exactly is your use case we can only give you generic guidance (also filing issues without clear description of a problem is really asking for it to be closed at once), e.g.: Implementing a wrapper page using the RESTful OpenGrok API that would automatically populated the ignored files could do the job.

**Comment by senthilkumarsh** [comment]
Ok. I will explain you my requirement in detail. I have a txt file in which the folder names are listed say 100 folders  1 folder name in each line. In opengrok search page we have option to choose exclude, if that option is selected then we have to show the results by excluding those folders, otherwise usual result should be shown.

**Comment by vladak** [comment]
It's hard to imagine this to be part of the main repository (UI clutter, complexity with setting this up per-project, feels wrong to be done server side), it really seems quite specific to your environment.
