### ISSUE TITLE
how to backup the index after opengrok indexing is failed

### ISSUE THREAD

**Issue by hal02** [OpenGrok/OpenGrok#1856]
I am using opengrok, and we have a very large code repository which are renewed very frequently, so I need to execute the Opengrok index very frequently. We found if the Opengrok indexing failed, the whole repository won’t work and code cannot be searched anymore till we succeed in execute indexing again.  

We are wondering whether there is a way to back up the index, then even if the new index failed, we can still use the old ones, or the index always point to the old ones and switch to the new ones only when indexing succeeded. Does anyone have such experience and share any suggestions? thanks in advance.

**Comment by vladak** [comment]
The backup part already answered on the `opengrok-users` ML.

As for the corrupted problem, I'd really like to get to the bottom of the problem. What exactly do you see in the logs etc. when the indexer fails ?

**Comment by hal02** [comment]
thanks, vladak

**Comment by vladak** [comment]
It does not look like we won't ever receive any info w.r.t. the index failure so closing for now. Feel free to reopen.
