### ISSUE TITLE
unconfigured plugins appended by AuthorizationFramework to the tail of the list cause authorization failures

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1874]
In order do a change in one of the autorization plugins, I had reverted authorization stack configuration to bare minimum so that it basically had only `UserPlugin`, `LdapUser` and `LdapFilter` plugins. The `LdapAttr` plugin was not present in the configuration (but it was in the `plugins.jar`) yet it was added:

```
08-Nov-2017 17:33:48.184 WARNING [http-nio-8084-exec-4] org.opensolaris.opengrok.authorization.AuthorizationFramework.addPlugin Plugin class "opengrok.auth.plugin.LdapAttrPlugin" was not found in configuration. Appending the plugin at the end of the list with flag "required"
```

Given it was not present in the configuration, it was missing the required parameter:

```
08-Nov-2017 17:33:48.333 SEVERE [http-nio-8084-exec-4] org.opensolaris.opengrok.authorization.AuthorizationPlugin.load Plugin "opengrok.auth.plugin.LdapAttrPlugin" has failed while loading with exception:
 java.lang.NullPointerException: Missing param [attribute] in the setup
	at opengrok.auth.plugin.LdapAttrPlugin.load(Unknown Source)
	at org.opensolaris.opengrok.authorization.AuthorizationPlugin.load(AuthorizationPlugin.java:119)
	at org.opensolaris.opengrok.authorization.AuthorizationStack.load(AuthorizationStack.java:145)
	at org.opensolaris.opengrok.authorization.AuthorizationFramework.loadAllPlugins(AuthorizationFramework.java:339)
...
```

which resulted in all the requests to be denied.

This is also a problem now that `plugins.jar` is shipped with `FalsePlugin`.

I don't remember why this practice of appending plugins not present in any stack was added however this definitely back fired. @tulinkry ?

**Comment by tulinkry** [comment]
This practice is there for the plug&play experience with minimum configuration. The user does not have to do anything just drop the plugin class into the plugin directory.

However it does not seem that perfect now

**Comment by vladak** [comment]
I see. Given the current plugins it does not seem to be reasonable now.
