### ISSUE TITLE
project bubble(s) placed below search form

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#1876]
Using the latest `master` I noticed this:

![bubble-bug](https://user-images.githubusercontent.com/2934284/32663755-54fd64ba-c62f-11e7-9d38-684252364320.png)

i.e. the "bubble" with the project is placed below the search form, along its side.

**Comment by vladak** [comment]
@Orviss is there a chance this could be related to one of your commits since 1.1-rc16 ?

**Comment by Orviss** [comment]
Possibly, I will take a look later today.

**Comment by Orviss** [comment]
This is caused by this line 
```css
* {		clear: both }
```
in `mandoc.css` on line `38` which was added by @idodeclare

**Comment by idodeclare** [comment]
Oops, that definition escaped my attention when I translated mandoc.css for import to OpenGrok. I'll push a fix.

**Comment by vladak** [comment]
fixed in 2daafcd
