### ISSUE TITLE
how to switch manifest,or switch branch 

### ISSUE THREAD

**Issue by kaoer** [OpenGrok/OpenGrok#1888]
how to switch another  manifest,or switch another branch ?

I installed a Opengrok environment, ready to use a few people together.They want to be able to switch between different branches to see the code.how can i do?

**Comment by vladak** [comment]
If you mean branches of repositories indexed by OpenGrok, this is not possible. It is necessary to checkout all the branches to be indexed separately.

Possibly a dup of #425
