### ISSUE TITLE
History can't be search by SHA key

### ISSUE THREAD

**Issue by JustSong** [OpenGrok/OpenGrok#1893]
OpenGrok Version: opengrok-1.1-rc11
JDK: Oracle java version "1.8.0_144"
OS: Ubuntu 12.04.5 LTS
Tomcat: Tomcat8

Hi sir,

I'm sure there is history in this project but we can't search history by SHA key.
Can you help me to find out the problem?
Thanks.

![image](https://user-images.githubusercontent.com/19389481/33194279-c867c24e-d109-11e7-90dc-a4c645e724bf.png)

**Comment by JustSong** [comment]
If I click the button which I highlight with redbox , the error message was shown.

![image](https://user-images.githubusercontent.com/19389481/33196140-940a54c6-d118-11e7-9ce3-cdf842f7a7f4.png)

**Comment by vladak** [comment]
As you can see in the first image, the search term was split into 2. This is a bug by itself (there is an issue for that). However, even substring search for the hash should work I believe.

Could you remove the index for given project and reindex from scratch to see if this helps ?

**Comment by JustSong** [comment]
Hi Vladak,

Yes, It's work now.
I thinks this issue is related to my last question #1884 .
After I fix #1884 problem, it need to reindex again.

Thanks a lot.

**Comment by tarzanek** [comment]
yeah, query parser needs to be fixed to only split by whitespace, current splitting is a "feature" that came in with one of the lucene upgrades ...
