### ISSUE TITLE
FortranAnalyzerFactory claims the INC suffix

### ISSUE THREAD

**Issue by idodeclare** [OpenGrok/OpenGrok#1896]
Hello,

It's odd that .inc files are claimed by FortranAnalyzerFactory. Neither Universal ctags nor Wikipedia shows it as a standard Fortran extension. (BTW, both ctags and Wikipedia show some other extensions which might be claimed by FortranAnalyzerFactory.)

What are thoughts about removing INC?

What are thoughts about adding missing Fortran suffixes?

Thank you.

**Comment by tarzanek** [comment]
I agree
since .inc might be custom to whomever pushed the fortran analyzer ... we can document this on our wiki and there is an easy way on assign the extension to an analyzer from command line, so they can customize the extension back instead of being in mainstream
