### ISSUE TITLE
Add OPENGROK_CTAGS info to the installation manual

### ISSUE THREAD

**Issue by maximvl** [OpenGrok/OpenGrok#1933]
Hi guys, I have `universal-ctags` installed manually in `/usr/local/bin` because my distro doesn't have it packaged. And only by searching in the code I found that ctags implementation can be set via env variable. I think it would be nice to mention the `OPENGROK_CTAGS` variable in the manual somewhere in the indexing section. 

Cheers.

**Comment by tarzanek** [comment]
feel free to fork/clone the repo and document it
resp. https://github.com/OpenGrok/OpenGrok/wiki/How-to-install-OpenGrok is open for editing

we desperately need collaborators(especially in docs), so if you can help with this people will highly appreciate it

tia
L

**Comment by maximvl** [comment]
@tarzanek done :)

**Comment by tarzanek** [comment]
thank you, sir! :)

**Comment by maximvl** [comment]
@tarzanek could you add me to slack chat? I requested on mailing list :)

**Comment by tarzanek** [comment]
AH ... it can very well be I have wrong email in mailing list ... d'oh!

**Comment by tarzanek** [comment]
@maximvl what is your mail ?

**Comment by maximvl** [comment]
@tarzanek  https://groups.yahoo.com/neo/groups/opengrok-users/conversations/messages/135

**Comment by tarzanek** [comment]
I generated a shared invite link, can you please use it: 
https://join.slack.com/t/opengrok/shared_invite/enQtMjg1OTQ3MTU1MTIwLWE2Yzk1ZTAyMmE3NzAxNzAyYjIzMjA3OGMyZGQ0MjM1MjE0M2U1OGIxYjRhNzVhOTQxOTU0MzRmNzg0NzJmMDg ?
