### ISSUE TITLE
OPENGROK_SCAN_DEPTH not userful, long path no history 

### ISSUE THREAD

**Issue by kaoer** [OpenGrok/OpenGrok#1942]
echo command, 
MinimalInvocation    -r on -H  -D off  -z 6  -C -c /usr/bin/ctags-exuberant -a on  -U localhost:2424    -W /var/data/opengrok/660/etc/configuration.xml -S -P -s /var/data/660 -d /var/data/opengrok/660/data -w 660

OpenGrok  1.1-rc16

**Comment by kaoer** [comment]
my repositories path maybe deeper，some long path cannot scan the history 

how can i do ?

tks!

**Comment by kaoer** [comment]
i set OPENGROK_SCAN_DEPTH="6"，but no effect

**Comment by tarzanek** [comment]
this should work ... can you run above with java agent and troubleshoot trace the jvm?
checkout sources, run netbeans
above instrument with e.g. 
```
-agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y
```
then connect with netbeans to :9009 and set proper breakpoints to see the tracing with long depth ...

**Comment by tarzanek** [comment]
(after few iterations you should be able how deep it goes for scanning of repos ... )

**Comment by tarzanek** [comment]
(and I hope you use latest trunk - see https://github.com/OpenGrok/OpenGrok/wiki/Developer-intro for starter)
possible breakpoints are in
HistoryGuru
on lines 389 and 411
e.g. https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/history/HistoryGuru.java#L389

**Comment by vladak** [comment]
Could you provide more information about the directory structure (relative to source root) and what kind of repository this is ?

**Comment by kaoer** [comment]
I modified the source "src/org/opensolaris/opengrok/configuration/Configuration.java",and  set "defaultScanningDepth = 6", now it's ok.

**Comment by kaoer** [comment]
660/.repo
660/vendor/my/overlay/source/common/.git
 ./OpenGrok index 660

the "common/.git" is no history

**Comment by tarzanek** [comment]
so that means that passing the parameter didn't work properly ?

**Comment by vladak** [comment]
the `OpenGrok` shell script contains:

```
331     # OPTIONAL: override depth of scanning for repositories
332     if [ -n "${OPENGROK_SCAN_DEPTH}" ]
333     then
334         SCAN_DEPTH="--depth ${OPENGROK_SCAN_DEPTH}"
335     fi
```

and `Indexer.java`:

```
425              parser.on("--depth", "=number", Integer.class,
426                  "Scanning depth for repositories in directory structure relative to",
427                  "source root. Default is " + Configuration.defaultScanningDepth + ".").Do( depth -> {
428                  cfg.setScanningDepth((Integer)depth);
429              });
```

I don't think there is a test case for that.

**Comment by kaoer** [comment]
my version is tag: 1.1-rc16 .

maybe i can update to 1.1-rc17 take a try

**Comment by vladak** [comment]
I assume the path to the repository above is relative to source root ?

**Comment by kaoer** [comment]
<void property="sourceRoot">
   <string>/var/data/660</string>


./OpenGrok index /var/data/660

**Comment by vladak** [comment]
A data point for the parameter passing: `-z` got changed to `--depth` with cset e6e4c3cc which is part of 1.1-rc17

**Comment by vladak** [comment]
Reproducible with latest `master`. This happens because the `cfg` member is set at the end of `parseOptions()`:

```
        if (cfg == null) {
            cfg = new Configuration();
        }
```

however this is called in `main()` like this:

```
            argv = parseOptions(argv);
            
            env = RuntimeEnvironment.getInstance();
```

and the singleton constructor looks like this:

```
private RuntimeEnvironment() {
        configuration = new Configuration();
        threadConfig = new ThreadLocal<Configuration>() {
            @Override
            protected Configuration initialValue() {
                return configuration;
            }
        };
    }
```

so basically everything set by the options parser is lost.
