### ISSUE TITLE
Branch and Version doesn't show up on the Project listing for Subversion

### ISSUE THREAD

**Issue by Suwadith** [OpenGrok/OpenGrok#1944]
I was finally able to generate history details using the following command

`java -Xms2g -Xmx4g "-Dorg.opensolaris.opengrok.history.Subversion=C:\Program Files\TortoiseSVN\bin\svn.exe" -jar E:\tools\opengrok-1.0\lib\opengrok.jar -m 512 -W E:\tools\opengrok-1.0\etc\r81-configuration.xml -r on -H -c E:\tools\ctags58\ctags.exe -R E:\tools\opengrok-1.0\etc\grouping.xml -P -S -v -s E:\Source\R81 -d E:\tools\opengrok-1.0\data\r81 -w /r81`

Now History/Annotate Links do work. But now in the homepage as you can see below, The branch and the version is not showing up. 

![image](https://user-images.githubusercontent.com/20539850/33882632-bd806c42-df5e-11e7-962f-e6c11b6ccbea.png)

How can I fix this? 

Thanks

**Comment by vladak** [comment]
What version are you running again ? I think you needed 1.1 for SVN history (introduced cset 0ba7200d) and branch (introduced cset 3638ee32).

**Comment by Suwadith** [comment]
@vladak I see. I'm using v1.0 the stable one. I'll give a try at v1.1-rc and let you know. Thanks.

**Comment by vladak** [comment]
Keep in mind that once switching to 1.1 you will need to reindex.

**Comment by Suwadith** [comment]
@vladak Yeah it works with v1.1-rc17
