### ISSUE TITLE
option to turn off history completely

### ISSUE THREAD

**Issue by cnst** [OpenGrok/OpenGrok#32]
There doesn't seem to be any command-line option to turn off `historycache`.  The most relevant documentation says this:

```
-H
        Generate history cache for all repositories
-h /path/to/repository
        just generate history cache for the specified repos (absolute path from source root)
…
-k /path/to/repository
        Kill the history cache for the given repository and exit. Use '*' to delete the cache for all repositories.
```

**Comment by vladak** [comment]
Trying this with 1.0, the behavior is correct, -S without -H does not generate history. After all, history is generated only when `refreshHistory` variable is set in Indexer which only happens when -H is specified.

**Comment by vladak** [comment]
Actually, the history is generated for individual files in the second phase of indexing.

**Comment by vladak** [comment]
First problem is in `IndexDatabase.java#update()`:

```
365                  HistoryGuru.getInstance().ensureHistoryCacheExists(sourceRoot);
```

Second problem is in `AnalyzerGuru.java#populateDocument()`:

```
334              HistoryReader hr = HistoryGuru.getInstance().getHistoryReader(file);
335              if (hr != null) {
336                  doc.add(new TextField(QueryBuilder.HIST, hr));
337                  // date = hr.getLastCommentDate() //RFE
338              }
```

Both should consult whether history is enabled.

**Comment by vladak** [comment]
The fact that this was observed when using CVS stems from the fact that CVS does not support per-directory history so relies on `populateDocument()` to supply the history for individual files.

The bottom line is that history should not be generated at all (be it in indexer or webapp) if -H is not used as noted in #1539.

**Comment by vladak** [comment]
There is a `historyCache` / `isHistoryCache()` in `Configuration` and `useHistoryCache()` in `RuntimeEnvironment` which is consulted in `HistoryGuru`:

```
78      private HistoryGuru() {
79          HistoryCache cache = null;
80          RuntimeEnvironment env = RuntimeEnvironment.getInstance();
81          scanningDepth = env.getScanningDepth();
82          if (env.useHistoryCache()) {
83              cache = new FileHistoryCache();
84  
85              try {
86                  cache.initialize();
...
```

and seems unused otherwise.

**Comment by vladak** [comment]
`fetchHistoryWhenNotInCache` property in `Configuration` is relevant to this as well - could well serve as a workaround by setting it in read-only configuration like this:

```
  <void property="fetchHistoryWhenNotInCache">
   <boolean>false</boolean>
  </void>
```

**Comment by vladak** [comment]
Disabling just the history cache does not make much sense I think because that would mean the `populateDocument()` has to acquire history by running SCM commands which would make indexing painfullly slow for no reason.
