### ISSUE TITLE
history for a file shouldn't display the complete history (Bugzilla #11197)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#404]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2009-09-04 18:58:03 +0000, Trond Norbye wrote:

> But instead use pagination to show 20 entries at a time..

**Comment by tulinkry** [comment]
Fixed by #1049
