### ISSUE TITLE
project list on main page should be sorted as case insensitive (Bugzilla #12989)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#424]
status NEW severity _minor_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2009-12-02 11:21:46 +0000, Vladimir Kotal wrote:

> If the list of projects contains projects which have a name which begins with upper case letter these will be displayed first (in 0.8), e.g.:
> 
> NetBSD-current
> OpenBSD-current
> 
> ...
> onnv-clone
> opengrok-trunk
> ...
> 
> This is confusing. The sorting function should be case insensitive.

**Comment by rahul007ashok** [comment]
+1
Any updates on this?

**Comment by tulinkry** [comment]
This has been already fixed in the master. Projects are sorted while having all letters in upper case.
![screenshot from 2016-12-23 12-37-19](https://cloud.githubusercontent.com/assets/6997160/21453143/9872be00-c90c-11e6-8882-593d36d3cc2e.png)

**Comment by rahul007ashok** [comment]
Should this ticket be closed then?
