### ISSUE TITLE
Improve usability of project picker on homepage (Bugzilla #1451)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#436]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _Other_
Assigned to: Trond Norbye

On 2008-04-23 05:04:41 +0000, Lubos Kosco wrote:

> Project picker stands in the way ...
> 
> The way we choose projects should be somehow improved.
> With more than 4 projects the listbox is unusable.
> 
> Also it makes sense to put the chooser box NEXT to search fields, not beneath it (usually people have widescreens or wide resolutions ). It would save space and don't stand in the way for search results.

**Comment by tulinkry** [comment]
This is already in the master by now.
