### ISSUE TITLE
OGAgent should read config from /var/opengrok/etc (Bugzilla #15653)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#444]
status NEW severity _minor_ in component _agent_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-04-16 09:20:48 +0000, Knut Anders Hatlen wrote:

> OGAgent reads its configuration from /etc/opengrok/opengrok.properties. Other OpenGrok config files have been moved from /etc/opengrok/ to /var/opengrok/etc/. For consistency, we should do the same with OGAgent's config files.
> 
> When this change has been made, we can remove /etc/opengrok from the Solaris packages (they currently create an empty /etc/opengrok directory).

**Comment by tulinkry** [comment]
This tool was eoled in #1343
