### ISSUE TITLE
Allow %include directive in lex files (Bugzilla #16053)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#458]
status NEW severity _minor_ in component _build_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-05-24 18:31:09 +0000, Knut Anders Hatlen wrote:

> It would be useful to be able to use the %include directive in the JFlex files to avoid repeating boilerplate code.
> 
> Currently, if we add an %include, the build fails when it's started from NetBeans. This is because NetBeans starts Ant in the current working directory, not in the project basedir, so the relative file name in the %include directive no longer points to the file to include.

**Comment by idodeclare** [comment]
@vladak , oh hey, this is resolved by dca9fde67fc930e3b8a7d6ae24ac50efa0952401.

**Comment by tarzanek** [comment]
thank you Chris @idodeclare , closing
