### ISSUE TITLE
grouping of projects (Bugzilla #17189)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#480]
status FIXINPROGRESS severity *enhancement* in component *webapp* for *---*
Reported in version *unspecified* on platform *ANY/Generic*
Assigned to: Vladimir Kotal

Original attachment names and IDs:
- _project-groups.jpg_ (ID 4323)

On 2010-10-08 09:08:43 +0000, Lubos Kosco wrote:

> provide user configurable grouping such as on http://grok.czech.sun.com:8080/source/index.jsp

On 2010-10-08 09:09:53 +0000, Lubos Kosco wrote:

> Vladimir is working on this bug and in first iteration we will get a cli interface to create group definitions, which then can generate front page such as on grok.czech

On 2010-10-08 14:31:58 +0000, Vladimir Kotal wrote:

> Created attachment 4323
> screenshot of main page with project groups
> 
> This page with project groups was generated by crude shell script which traverses the directory with projects and uses simple configuration file which maps projects into group based on regular expression. The final version of the enhancement will be fully implemented within OpenGrok and managed by the OpenGrok script.

On 2011-01-05 08:36:02 +0000, Knut Anders Hatlen wrote:

> Resetting target milestone since this won't make it into 0.10.

**Comment by vladak** [comment]
This change has several pre-requisites:
  - ability to display parent info for a project (#937)
  - ability to display branch info for repository
  - project listing on index page

**Comment by vladak** [comment]
There are a few things for consideration:
  - how to specify the groups
    - the original shell script takes a config file in the form of `regexp whitespace name`. Initially I was thinking about CLI to feed this into OpenGrok configuration however this would be too convoluted. Rather, I'd like to create separate configuration file which can be read (simiarly to -R) and merged with runtime configuration. The config file would be Java beans XML representation (HashMap ?).
  - whether to introduce the ability to define subgroups

**Comment by tarzanek** [comment]
I agree on both, they would be a good step forward to finally get full project support from grok ala other code search engines (which just consume SCM URL and name, ev. group/subgroup and generate the rest , I think code sight does it and I played with one more which name I forgot)

**Comment by vladak** [comment]
This was implemented in cset d470e59c0405a31b7e5f194bd9b705e91b12bf0a
