### ISSUE TITLE
tooltip in annotate needs to be improved(faster) and it has to be w3c valid (Bugzilla #17480)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#484]
status NEW severity _minor_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-11-25 14:51:31 +0000, Lubos Kosco wrote:

> click on annotate of any file
> 
> tooltip is just too slow - use e.g. hashmaps in js to make it faster
> also contents of tooltip are not encoded, hence not w3c valid (js hashmap would solve this too)

**Comment by tulinkry** [comment]
New tooltip added in #1145
