### ISSUE TITLE
add authorization layer (Bugzilla #18242)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#503]
status REOPENED severity *enhancement* in component *misc* for *---*
Reported in version *unspecified* on platform *ANY/Generic*
Assigned to: Lubos Kosco

On 2011-05-03 18:29:39 +0000,  wrote:

> Would like to see the ability to secure access to the source code that OpenGrok is presenting for browsing. 
> Need to add a way to redirect access to authentication via https.
> 
> This could require changes to the project, or updating of documentation on how to accomplish this.

On 2011-05-03 22:08:36 +0000, Darren J Moffat wrote:

> I'm not sure that doing authentication (and particularly authentication without a subsequent authorisation and audit system too) in the opengrok application is the correct way to solve this.
> 
> Why can't the hosting webserver/application server authentication and access control system be used for this ? What aren't they providing that requires this be pushed up into the opengrok app ?
> 
> I've always thought of opengrok as "web browser" cscope and there is no way we would add authentication into the UNIX cscope command.

On 2011-05-03 22:26:11 +0000, James C. McPherson wrote:

> Implementing closedgrok seems to be the wrong thing to do. Especially when
> we already have the infrastructure built in to apache / S1WS / etc to do 
> authentication against LDAP and LDAPS, which can be turned on really easily
> with a few lines in the server's configuration file.
> 
> Bruce - have a read of http://httpd.apache.org/docs/2.2/mod/mod_authnz_ldap.html
> for examples.

On 2011-05-04 08:47:58 +0000, Lubos Kosco wrote:

> I understand that the first phase should be leveraging existing pieces to do auth in opengrok - so tomcat auth(either through pam or other pluggable means) and ssl
> 
> so first phase should be a documentation page on how to achieve above
> 
> 
> Second phase is something which is already in place on opensolaris.org - restricting access per project
> for which the web application has to be adjusted slightly (to have users per project which have access) - opensolaris.org implementation is not that pluggable and I am curious how much can be leveraged and taken upstream ...
> 
> someone correct me if wrong
> L

On 2011-05-04 12:54:06 +0000, Lubos Kosco wrote:

> tomcat and ldap - http://blog.mc-thias.org/?title=tomcat_ldap_authentication&more=1&c=1&tb=1&pb=1
> 
> tomcat proxy(in case we will redirect the queries through some other machine or use different outer server name) - http://tomcat.apache.org/tomcat-6.0-doc/proxy-howto.html

On 2011-05-04 22:22:30 +0000, Vaishak Suvarna wrote:

> (In reply to comment # 4)
> > tomcat and ldap -
> > http://blog.mc-thias.org/?title=tomcat_ldap_authentication&more=1&c=1&tb=1&pb=1
> > 
> > tomcat proxy(in case we will redirect the queries through some other machine or
> > use different outer server name) -
> > http://tomcat.apache.org/tomcat-6.0-doc/proxy-howto.html
> 
> I don't think the documentation regarding the proxy set-up is complete atleast from opengrok perspective. All the opengrok links will be broken when accessing via a proxy (e.g from apache webserver). I assume you need some additional apache modules which can automatically resolve the broken links

On 2011-05-04 22:55:56 +0000, Vaishak Suvarna wrote:

> (In reply to comment # 4)
> > tomcat and ldap -
> > http://blog.mc-thias.org/?title=tomcat_ldap_authentication&more=1&c=1&tb=1&pb=1
> > 
> 
> The tomcat ldap authentication & access restriction (by group/roles etc) can be configured only at opengrok instance level not for the directories within that particular opengrok webpapp. 
> 
> For e.g if the opengrok webpapp has multiple projects, within the same instance then I am not sure if its possible to restrict access using the tomcat default authentication features.

On 2011-05-05 07:58:51 +0000, Lubos Kosco wrote:

> (In reply to comment # 6)
> > (In reply to comment # 4)
> > > tomcat and ldap -
> > > http://blog.mc-thias.org/?title=tomcat_ldap_authentication&more=1&c=1&tb=1&pb=1
> > > 
> > 
> > The tomcat ldap authentication & access restriction (by group/roles etc) can be
> > configured only at opengrok instance level not for the directories within that
> > particular opengrok webpapp. 
> > 
> > For e.g if the opengrok webpapp has multiple projects, within the same instance
> > then I am not sure if its possible to restrict access using the tomcat default
> > authentication features.
> 
> yes, you're correct, most probably that will have to be next phase(second one) which can allow per project access ...
> (adding Martin in case he has some input on lessons learned)

On 2011-05-05 09:21:23 +0000, Martin Walsh wrote:

> (In reply to comment # 3)
> > 
> > Second phase is something which is already in place on opensolaris.org -
> > restricting access per project
> > for which the web application has to be adjusted slightly (to have users per
> > project which have access) - opensolaris.org implementation is not that
> > pluggable and I am curious how much can be leveraged and taken upstream ...
> > 
> 
> I don't think much can be taken upstream, as the implementation is very specific to what we needed to achieve. The main part of access control was done with a servlet filter, allowing us to control access before/after the request/response has been handled by OpenGrok.  This was pretty simple, and required no changes to the actual application.  Application changes were required to prevent certain projects from being displayed in project listings etc, such as the /xref/ servlet. 
> 
> I am happy to help with the second phase, if required.

On 2011-05-05 09:27:19 +0000, Martin Walsh wrote:

> (In reply to comment # 7)
> > (In reply to comment # 6)
> > > (In reply to comment # 4)
> > > > tomcat and ldap -
> > > > http://blog.mc-thias.org/?title=tomcat_ldap_authentication&more=1&c=1&tb=1&pb=1
> > > > 
> > > 
> > > The tomcat ldap authentication & access restriction (by group/roles etc) can be
> > > configured only at opengrok instance level not for the directories within that
> > > particular opengrok webpapp. 
> > > 
> > > For e.g if the opengrok webpapp has multiple projects, within the same instance
> > > then I am not sure if its possible to restrict access using the tomcat default
> > > authentication features.
> > 
> > yes, you're correct, most probably that will have to be next phase(second one)
> > which can allow per project access ...
> > (adding Martin in case he has some input on lessons learned)
> 
> As an intermediary step, if just access controls are required, a simple servlet filter should be able to achieve this by manipulating the request/response.  This would however still list hidden projects in the webapp, returning a HTTP 403 if selected.

On 2011-05-05 11:32:08 +0000, Vladimir Kotal wrote:

> (In reply to comment # 7)
> > (In reply to comment # 6)
> > > (In reply to comment # 4)
> > > > tomcat and ldap -
> > > > http://blog.mc-thias.org/?title=tomcat_ldap_authentication&more=1&c=1&tb=1&pb=1
> > > > 
> > > 
> > > The tomcat ldap authentication & access restriction (by group/roles etc) can be
> > > configured only at opengrok instance level not for the directories within that
> > > particular opengrok webpapp. 
> > > 
> > > For e.g if the opengrok webpapp has multiple projects, within the same instance
> > > then I am not sure if its possible to restrict access using the tomcat default
> > > authentication features.
> > 
> > yes, you're correct, most probably that will have to be next phase(second one)
> > which can allow per project access ...
> > (adding Martin in case he has some input on lessons learned)
> 
> Not mentioning per project-group access.. (https://defect.opensolaris.org/bz/show_bug.cgi?id=17189)

On 2011-05-05 11:59:29 +0000, Trond Norbye wrote:

> I don't think this kind of configuration is a common use case for the average deployment of an OpenGrok server, so I'd hate to add a ton of code that adds complexity to the code base. All of the logic for the authorization stuff should be stored and maintained _outside_ the OpenGrok project and the OpenGrok core should not be modified to achieve this (That means that you would have to use the operating systems facilities to protect someone from running searches through the CLI).
> 
> We should define an interface the web front-end would call that checks the access for each page hit and update the JSF files to check the access..
> 
> All of the code, documentation and configuration for how to set this up should live in its own repository.

On 2011-05-06 08:36:08 +0000, Knut Anders Hatlen wrote:

> I agree with Trond. Adding an actual implementation of authentication and authorization in OpenGrok would open a can of worms. It would be better to let the servlet container handle the authentication and provide hooks in the webapp to check against the ACL. In its simplest form, OpenGrok could have this interface:
> 
> interface AccessControl {
>     boolean canAccess(String user, String path);
> }
> 
> And those who need access control would point the webapp to their own implementation that checked the ACL wherever it's stored and in whichever format (in a database, XML file, on an LDAP server, ...).
> 
> Doing the actual filtering/blocking inside the webapp using such an interface shouldn't be too tricky, I think.

On 2011-05-06 09:07:44 +0000, Trond Norbye wrote:

> What about:
> 
> interface AccessControl {
>     boolean canAccess(javax.servlet.http.HttpServletRequest request, String path)
> }
> 
> We would then call canAccess(request, NULL) top of all of the JSP files to see if the user got access to that specific page (this could filter out all navigation in the xrefs). In addition we would call canAccess for all of the different projects we're going to add in the menu list (this will help up don't reveal any project names they shouldn't see), and canAccess for all of the files we're adding for search results (this won't give the one-liner hit). 
> 
> I suggest we just pass the complete request object to avoid having to patch this later on if someone wants to add additional checks...

On 2011-05-06 13:33:14 +0000, Trond Norbye wrote:

> I added an initial shot at this in changeset:   1173:813a4561226a
> 
> It would be nice if someone who needs this feature could check it it solves their needs?

On 2011-05-06 19:43:42 +0000, Trond Norbye wrote:

> One should use a Filter (as in : http://download.oracle.com/javaee/5/api/javax/servlet/Filter.html ) instead to achieve this.

On 2011-05-06 19:45:19 +0000, Trond Norbye wrote:

> (please reopen the bug if it is impossible to achieve the desired functionality by using a Filter)

On 2011-05-08 06:01:38 +0000, Lubos Kosco wrote:

> reopening, I would like to document info gathered in this bug in the code/doc of the product itself (since bugzilla might go away, but this info should stick with opengrok to save time for future bugs like this)

On 2011-09-22 01:01:27 +0000, Joshua Kugler wrote:

> A feature such as this would be very beneficial.  I was directed to this issue report by knut.hatlen@oracle.com when I asked:
> 
> > Can the opengrok search front-end be configured to honor permissions 
> > from a repository?  In other words, not show code to the user if that 
> > user could not read that part of the repository?
> 
> I first became aware of this feature while searching for full-text indexers for our SVN repository.  Other SVN indexers may have this feature, but I first read about it at http://svn-search.sourceforge.net/  Not only will it search the repository, but it will only show files to which the logged-in-user has access.
> 
> I *LIKE* that feature. But what I like about OpenGrok is the code cross referencing it does.  And the fact that it is maintained.
> 
> I would love to add the feature, but I know *no* Java. :(
> 
> So, reading over this bug, it seems that it started as a discussion regarding simple authentication, but then progressed into the "authorization" functionality I describe above.  If so, I'll leave this right here. If not, let me know, and I'll open a new bug. :)

**Comment by vladak** [comment]
This was implemented in cset 6c5588deac931d8ca1d9f09fe9a5db32155d7f4c

**Comment by tobegit3hub** [comment]
@vladak  Is there any document about this feature?

**Comment by tarzanek** [comment]
see https://github.com/OpenGrok/OpenGrok/blob/master/doc/authorization_howto.txt

**Comment by tobegit3hub** [comment]
Thanks @tarzanek very much 😃
