### ISSUE TITLE
Clicking on navigator doesn't work if line # are disabled (Bugzilla #18514)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#506]
status NEW severity _normal_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

On 2011-06-09 16:02:26 +0000, Ranjeeth Nagarajan wrote:

> With line # off, if I go to the navigator and click on a function, it doesnt take me to the function i clicked.
> 
> This is because it tries to navigate to the function by using its line number in the url.
> 
> The navigate toolbar should probably enable line # before trying to jump.

**Comment by tulinkry** [comment]
Already fixed in master
