### ISSUE TITLE
searching all projects can make the webapp to run out of heap space (Bugzilla #19192)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#541]
status NEW severity *critical* in component *webapp* for *---*
Reported in version *unspecified* on platform *ANY/Generic*
Assigned to: Lubos Kosco

On 2012-03-09 17:42:11 +0000, Vladimir Kotal wrote:

> Search across all projects (e.g. path search or full text search) in 0.11 can result in the webapp running out of memory. This is permanent condition and the container server (in our case Tomcat) has to be restarted.
> 
> /var/tomcat6/logs/catalina.out contains entries like:
> 
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> Mar 9, 2012 4:10:53 PM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run
> SEVERE: Socket accept failed
> java.lang.OutOfMemoryError: Java heap space
> 
> or
> 
> Mar 9, 2012 4:11:08 PM unknown unknown
> SEVERE: Error reading request, ignored
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> 
> The localhost log contains these entries:
> 
> /var/tomcat6/logs$ cat localhost.2012-03-09.log
> Mar 9, 2012 4:11:23 PM org.apache.catalina.core.ApplicationDispatcher invoke
> SEVERE: Servlet.service() for servlet jsp threw exception
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> Mar 9, 2012 4:11:27 PM org.apache.catalina.core.StandardWrapperValve invoke
> SEVERE: Servlet.service() for servlet search threw exception
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> Mar 9, 2012 4:11:27 PM org.apache.catalina.core.StandardWrapperValve invoke
> SEVERE: Servlet.service() for servlet search threw exception
> java.lang.OutOfMemoryError: GC overhead limit exceeded 
> /var/tomcat6/logs$

On 2012-03-24 06:28:06 +0000, Jens Elkner wrote:

> It would probably help to get a heap dump, when this happens - add the following JVM parameter: -XX:+HeapDumpOnOutOfMemoryError

On 2012-03-26 08:59:11 +0000, Vladimir Kotal wrote:

> (In reply to comment # 1)
> > It would probably help to get a heap dump, when this happens - add the
> > following JVM parameter: -XX:+HeapDumpOnOutOfMemoryError
> 
> We got a dump using -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/tomcat6/logs/dumps/ and it's 800 MB file. Most probably it cannot be shared outside of the company but I believe Lubos can provide the data extracts from jhat.
> 
> I think the overall conclusion from the jhat debugging session from last Friday is that there is some kind of memory leak of Lucene related data probably caused by OpenGrok itself.
> 
> Some web searches based on the leaked objects got us to sites like http://sangosthi.blogspot.co.uk/2010/01/alfresco-is-taking-too-much-memory.html

On 2012-03-26 14:18:41 +0000, Jens Elkner wrote:

> "cannot be shared outside": hmm, bad. Anyway, I usually find jhat not that useful. The standalone version of eclipse mat may give much more insights ...

On 2012-03-26 14:39:06 +0000, Lubos Kosco wrote:

> (In reply to comment # 3)
> > "cannot be shared outside": hmm, bad. Anyway, I usually find jhat not that
> > useful. The standalone version of eclipse mat may give much more insights ...
> 
> mainly because of the size ;)
> 
> I will use mat to have a look too
> but from rough jhat I've seen
> 
> objects org.apache.lucene.index.SegmentReader$Norm
> blocked like 80% of the heap
> 
> so I will try to figure out if this is because of how are opengrok analyzers structured or how are search is done , or if this is lucene bug
> (to me it rather seems like lucene bug ... )
> 
> I will also try to reproduce with current trunk with lucene 3.5 , it would be ideal, since 3.5 has some fixes in this area + multisearch now has more control over the thread pool

On 2012-03-26 15:28:37 +0000, Lubos Kosco wrote:

> (In reply to comment # 4)
> > (In reply to comment # 3)
> > > "cannot be shared outside": hmm, bad. Anyway, I usually find jhat not that
> > > useful. The standalone version of eclipse mat may give much more insights ...
> > 
> > mainly because of the size ;)
> > 
> > I will use mat to have a look too
> > but from rough jhat I've seen
> > 
> > objects org.apache.lucene.index.SegmentReader$Norm
> > blocked like 80% of the heap
> > 
> > so I will try to figure out if this is because of how are opengrok analyzers
> > structured or how are search is done , or if this is lucene bug
> > (to me it rather seems like lucene bug ... )
> > 
> > I will also try to reproduce with current trunk with lucene 3.5 , it would be
> > ideal, since 3.5 has some fixes in this area + multisearch now has more control
> > over the thread pool
> 
> ok
> so in the end this was all valid, we simply take 5MB per project
> on the internal server there are ~250 projects
> which needed like 2.2G of RAM for more complex queries and this hit the tomcats upper limit ... increasing the tomcat limit to 3G makes the queries work now ...
> 
> now only address the url length bug ...
> 
> guess this bug could make a suggestion that when indexer detects huge amount of projects it will complain and suggest increasing tomcat memory to satisfy multi searches ...
> (and I still think with lucene 3.5 in trunk the footprint will be smaller, we should try to test it)

On 2012-03-28 11:30:30 +0000, Vladimir Kotal wrote:

> (In reply to comment # 5)
> 
> <snip>
> 
> > so in the end this was all valid, we simply take 5MB per project
> > on the internal server there are ~250 projects
> > which needed like 2.2G of RAM for more complex queries and this hit the tomcats
> > upper limit ... increasing the tomcat limit to 3G makes the queries work now
> > ...
> > 
> 
> I think the equation to get an estimate of heap size is:
> 
>   ( 7 MB * number of projects ) + 300 MB for cache 
> 
> This should be enough, at least works for our deployment.

On 2012-03-28 11:32:33 +0000, Vladimir Kotal wrote:

> (In reply to comment # 5)
> 
> <snip>
> 
> > now only address the url length bug ...
> 
> This actually turned out to be caused by HTTP headers length limit in Tomcat. The Referer was too long (it contained list of all projects in the URL) which triggered the problem and Tomcat returned error code 400 as result. This can be easily fixed by adjusting the limit with maxHttpHeaderSize in server.xml:
> 
> <Connector port="8888" protocol="HTTP/1.1"
>                connectionTimeout="20000"
>                maxHttpHeaderSize="65536"
>                redirectPort="8443" />

**Comment by zmt** [comment]
Still open?

**Comment by tarzanek** [comment]
Yes, I think this can be closed, all is documented and I hesitate to change url params or shortener, it's good we can use just url to get to any result, server url handling and sizing should adapt to accommodate a lot of projects
