### ISSUE TITLE
Diffs in raw text format (Bugzilla #3510)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#586]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2008-09-20 11:36:15 +0000, Knut Anders Hatlen wrote:

> We should add the option to view diffs in raw text format, so that it is possible to save it to a file and apply it on the code.

**Comment by tulinkry** [comment]
I believe this is already in  the trunk
![screenshot from 2016-11-14 14-00-59](https://cloud.githubusercontent.com/assets/6997160/20265701/da587048-aa72-11e6-99c3-c93524921d73.png)

**Comment by tulinkry** [comment]
Implemented in #1283
