### ISSUE TITLE
size of the select menu should be more dynamic or configurable (Bugzilla #5879)

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#597]
status NEW severity _minor_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _Other_
Assigned to: Trond Norbye

On 2008-12-17 08:24:18 +0000, Vladimir Kotal wrote:

> By default, the front page displays list of projects in a select menu.
> This is limited by the following expression in web/menu.jspf:
> 
> size="<%=Math.min(5, env.getProjects().size())%>"
> 
> For sites with many (tens of) projects this does not scale, the window
> is just too small and cumbersome to navigate which leads to user frustration.
> 
> Possible approaches:
> - configurable (via configuration.xml) lower and upper bound
>   - say the size of the menu will not go below the lower bound
>     and will not go above upper bound:
> - size based on percentage of HTML page height
>   - say the select box height should be 30% of the page
>   - this could be done via CSS

**Comment by tulinkry** [comment]
New project picker without these limitations was introduced in #1161
