### ISSUE TITLE
"tab" doesn't show where you are when navigating OpenGrok index

### ISSUE THREAD

**Issue by ilovemaui** [OpenGrok/OpenGrok#642]
In OpenGrok 0.9 - when you navigate down into your index, the "tab" of you windows indicates where you are. In the new version 0.11.1 it always says "search" in the tab, regardless of which page you navigate down to.

**Comment by vladak** [comment]
Actually, even the "Cross reference" prefix could pose a problem when one has more than couple of tabs since the title of all the tabs will shrink to something like "Cross referenc...".
