### ISSUE TITLE
derbyclient.jar handling should be reworked

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#658]
In order to use JavaDB (Derby) the derbyclient.jar must be installed near `opengrok.jar` for both the indexer and webapp. It is so easy for the file to get lost when e.g. the OpenGrok package is reinstalled or webapp redeployed (we got bitten by that recently).

There really has to be better way to copy the file over and over. Both the indexer and webapp should be able to find it more dynamically or the file should be always shipped or deployed or ...

**Comment by tulinkry** [comment]
Derby support has been removed with #1463
