### ISSUE TITLE
Annotate sometimes rendered incorrectly in OpenGrok

### ISSUE THREAD

**Issue by acwarya** [OpenGrok/OpenGrok#669]
![image](https://f.cloud.github.com/assets/5599959/1279115/4a44aae2-2f2f-11e3-89bd-51b643131aa8.png)

Annotate sometimes rendered incorrectly in OpenGrok
Its reproducible in all browsers (FireFox , chrome , IE) but not frequently 1 out of 20 times.

**Comment by tulinkry** [comment]
This is already fixed in 0.13-rc8 and the other weird behaviour with annotations (#1356) will be fixed soon with #1392
