### ISSUE TITLE
regexp search only shows files, not line#s.

### ISSUE THREAD

**Issue by tad44** [OpenGrok/OpenGrok#679]
Using 0.12-rc1.
When searching with regexp, the result only shows the files, not the line#s with the match.
It would be nice if it can show the line#s also.

Thanks for the very useful tool.

**Comment by dobrou** [comment]
Hi,
with 0.12.1 version I don't see any line preview when I search with regex.
It would be nice to be able to use both features together.

And thanks for the very useful tool too!
