### ISSUE TITLE
Navigate doesn't work without Line#

### ISSUE THREAD

**Issue by tad44** [OpenGrok/OpenGrok#690]
Using 0.12rc2.
Not sure if this is intentional, but, it seems navigate to function, etc. doesn't work when Line# is not displayed.

Thanks,

**Comment by Hlipa** [comment]
It is still not fixed in 0.12.1.5. :(

**Comment by tarzanek** [comment]
@Hlipa we look for patches, got one? :-P

**Comment by harryxp** [comment]
The problem seems to be that the navigation links point to anchor links
which are hidden when Line# are gone.  I don't see an immediate fix.

**Comment by tarzanek** [comment]
fix is to disable the navigation with line # being disabled ...

**Comment by harryxp** [comment]
Haha good thinking.  Or we can make clicking navigation links force the Line# to show.



—

**Comment by tarzanek** [comment]
yes, this is probably a better approach
I have to finally update jquery so the speed will be better ...

**Comment by harryxp** [comment]
@Hlipa I made a patch in pull request #927.  Care to test it on more OS/browsers?  I only did Linux/Chrome.
