### ISSUE TITLE
Clicking include file sometimes returns error

### ISSUE THREAD

**Issue by tad44** [OpenGrok/OpenGrok#691]
With 0.12-rc2
I'm not sure if this is really an OpenGrok issue.
When I click on an include file name in a source code, sometimes I see this error:
    Error
    Index database(s) not found.
Our network does some http caching. Maybe that's causing the problem...
BTW, the path name is not double-quoted, e.g. source/s?path=stdlib.h
It is probably better to use double-quotes like 'only in this directory' check box.
Thanks,

**Comment by hellochenhang** [comment]
What is the status of this issue now ?
I came into the same issue with tomcat + opengrok 0.12

**Comment by urol** [comment]
I'm very interested in the actual status as well?
I was running into this "occasionally" trouble with tomcat7 + opengrok 0.12.1.5
"occasional" seems to mean the application is out of a certain state. !?
Would be nice to look forward to a solution.

**Comment by tarzanek** [comment]
it's session based problem, so your browser session will be in some weird state, I will try to debug and fix it soon

**Comment by carlobongiovanni** [comment]
Hi all, I recently played with opengrok (latest LTS release) and experienced the same problem. This is how I reproduced it:
1 access opengrok
2 double click on a project from the list
3 click on the top logo to be redirected at the home
4 repeat step 2
5 repeat step 3
6 type into the form, in the full search field, the word 'version' or any other word that could produce a result
7 press the search button

When the steps 2/3 are repeated, the user lands at the home without any project selected. It seems that the problem depends from that factor.

Hope this helps anyone.

C.

**Comment by tarzanek** [comment]
thnx @carlobongiovanni
can reproduce fully here, so clicking on home looses cookie

**Comment by tarzanek** [comment]
I think this is also related to #1064 , part of this might be also fixed by server side matching of projects that happened in #1074 and #1085

**Comment by tarzanek** [comment]
I think this issue might be closed now by all above changes in place.
Cookie wasn't properly set.
Funny thing is, that if you now do the same repro steps, you end up with multiple projects selected ;)
Which is a nice "feature" I guess :)

**Comment by urol** [comment]
Thanks @tarzanek 

in which version the fix will be included?

**Comment by tarzanek** [comment]
0.13 rc is due in few days
