### ISSUE TITLE
get rid of JDBCHistoryCache.updateIndexCardinalityStatistics()

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#762]
When investigating sub-optimal JDBC behavior @kahatlen found that the database is spending too much time while processing SYSCS_UPDATE_STATISTICS procedure on the FILECHANGES and DIRCHANGES tables.

The function comment says:

```
906     * This is a workaround for the problems described in
907     * <a href="https://issues.apache.org/jira/browse/DERBY-269">DERBY-269</a> and
908     * <a href="https://issues.apache.org/jira/browse/DERBY-3788">DERBY-3788</a>.
909     * When automatic update of index cardinality statistics has been
910     * implemented in Derby, the workaround may be removed.
```

These 2 bugs should be fixed in JavaDB 10.5.1.1 and 10.8.1.2, respectively. JavaDB  shipped with Solaris 11u1 SRU is 10.6.2.1.

We should get rid of the function and state minimal supported version of JavaDB in `README`.

**Comment by tulinkry** [comment]
JDBC is unsupported in 1.0
