### ISSUE TITLE
Declutter the UI

### ISSUE THREAD

**Issue by sk-** [OpenGrok/OpenGrok#790]
The nav bar is already very cluttered. To simplify it a little I propose to remove the home link, as the logo is already pointing to home.

**Comment by vladak** [comment]
Another alternative would be to get rid of the header altogether, i.e. remove the whole top bar with OpenGrok logo. This way there would be more space for the view itself, be it code, directory listing or history.

**Comment by tulinkry** [comment]
Implemented with #1145 and #1330
