### ISSUE TITLE
Solaris IPS package should deliver to /var/share

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#817]
Comment from Jens about IPS Solaris package:

> /var/opengrok is a bad choice. Should be /var/share/opengrok/src [or as
> long as lazy installer people haven't fixed their stuff and you wanna
> make it 100% "bad workaround" compliant /var/.migrate/opengrok/src =8-( ].
> Otherwise you may loose data when switching the BE.

Hence, we should switch from `/var/opengrok` to `/var/share/opengrok`

**Comment by jelmd** [comment]
NOTE: currently IPS does not support this directly, i.e. having a startup/setup script, which populates datadir, etc. below /var/share/ is ok, but the package itself is not allowed to deliver anything below /var/share/ or /var/.migrate/! See also SUNBT7081759 .

**Comment by vladak** [comment]
According to the IPS documentation [*] it is necessary to perform the migration of data in script run by a temporary SMF service. Such a script exist (`/lib/svc/share/migrate_shared_files.py`, run by `fs-minimal` service if `is_self_assembly_boot()` i.e. if `/.SELF-ASSEMBLY-REQUIRED` file exists which seems does not unless special circumstances are met) and although it is not a public interface, we can use it quite safely until better way is possibly delivered in Solaris 11.x updates.

[*] https://docs.oracle.com/cd/E53394_01/html/E54820/gnxft.html#PKDEVglyrx
