### ISSUE TITLE
optimize sorting - comparator can be static

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#827]
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/IndexDatabase.java#L823

the comparator could be made static ...

**Comment by vladak** [comment]
I think @tarzanek meant this piece of code in indexDown(), correct ?

```
 Arrays.sort(files, new Comparator<File>() {
@Override
public int compare(File p1, File p2) {
return p1.getName().compareTo(p2.getName());
}
});
```
