### ISSUE TITLE
Scala Definition search is not supported?

### ISSUE THREAD

**Issue by ilyapes** [OpenGrok/OpenGrok#830]
When I am searching is scala code for Definition it doesn't work even for the simplest definitions like:
 def saveTestFunc(taps: Long) = { /* some code */ } 
or even when the return type is know like :
 def saveTestFunc(taps: Long): String  = { /* some code */ } 

Thanks

**Comment by tarzanek** [comment]
this is fixed in 0.13 rcs already, closing
