### ISSUE TITLE
allow sorting according to Date/Size/Name in file list view

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#831]
Some JavaScript stanza can be added which would allow to click on the 'Name', 'Date', 'Size' column headers which would in turn change the sorting scheme (and ordering direction) on the fly (i.e. without refreshing the page).

This is handy in case the file listing is long/incomprehensible and the user wants to see the newest (most recently modified) files or biggest files in current directory.

**Comment by vladak** [comment]
There are 2 possible ways how to implement this:
  1. using JavaScript such as jQuery tablesorter plugin (http://tablesorter.com)
  2. make the JSP do the sorting based on some parameter, i.e. change web/DirectoryListing.java#listTo() method to accept sorting argument

Each option has its advantages and disadvantages. It is important that the URL is kept as is, i.e. no parameters are appended.

jQuery positives:
  - no changes needed in JSPs, the URL will stay intact
  - client side will do the work, saving server resources
jQuery negatives:
  - will have to write custom parser for the Size column (to parse abbreviations such as `KiB`)
  - has to be maintained, i.e. kept up to date

JSP positives:
  - relatively easy maintenance
JSP negatives:
  - server side processing
  - will have to find a way how to pass the parameter (i.e. whether to sort according to Name, Date or Size) to the JSP somehow without disturbing the URL
  - will have to rewhack listTo() code to do the sorting

I guess the first thing is to find out how hard would it be to write a custom parser for the tablesorter plugin.

**Comment by tarzanek** [comment]
jquery also needs serious update, I've been trying to kick myself to do it and I think it has to be done before 0.13 ...

**Comment by vladak** [comment]
That would speak for JSP then. Not sure how to do the trick of passing the sorting criteria.

**Comment by tarzanek** [comment]
well jquery has to be updated no matter what, so it just means that I have to do it
I think sending query to server just for sorting is crap,
the data is already on client, it should sort it imho

**Comment by vladak** [comment]
Okay, sounds reasonable. Let me try with current jQuery we have (1.4.4) as tablesorter says it requires jQuery 1.2.

**Comment by vladak** [comment]
I got this working however we will need custom parser for both the Date and Size columns.

**Comment by tarzanek** [comment]
for latest jquery there are no better libraries/components?

**Comment by vladak** [comment]
I have completed the date parser already, it was quite easy.

**Comment by vladak** [comment]
size parser works now, almost as easy as the date parser.

The only thing which is escaping me is how to make the first column (i.e. file names) to be reversed. If I click on Date and then Name the sorting works but if I click on it again nothing happens.

**Comment by vladak** [comment]
got the Name column backward sorting by explicitly specifying the sorter for that column.
