### ISSUE TITLE
Clojure support

### ISSUE THREAD

**Issue by sanel** [OpenGrok/OpenGrok#859]
Hi,

I've added Clojure support in my fork and I would love you check it and do review. Modifications includes additional regexes for Clojure definitions, Clojure specific analyzer which is based on Lisp analyzer and added item to UI language dropdown box.

The only thing I was not able to solve is searching definitions like *my-magic-var* or *is-true?*; these are valid Clojure names, but OpenGrok would search request split in form *+defs: my +defs: magic +defs: var*; also, tokens like '?' '*', which can be part of Clojure variable or function name, are used by search engine. Any idea how to solve this?

Thanks.
Sanel

**Comment by tarzanek** [comment]
hmm, I am wondering if there was a pull request opened for this bug?
Can you open one?
Or should I just pull from your branch? ;)
(I'd be happier if you could open the pull request)

**Comment by sanel** [comment]
Hi,

Totally forgot about this :S Are there any significant changes in this branch, so I can do merge first if necessary?

Also what wanted to discuss with you about is that Lisp nature: I marked Clojure common functions as keywords, highlighting is working perfectly, but if you want to index Clojure source code, those references to those functions will not be created.

Any idea how to solve this one?

**Comment by tarzanek** [comment]
you need to make ctags recognize clojure
so either fix upstream
or define language as we do with scala ...

**Comment by tarzanek** [comment]
and merge with upstream
it should be straightforward
if not let me know

**Comment by sanel** [comment]
Ctags is recognizing clojure, but the language is different than Scala. In Scala keywords (e.g. `for`) which can't be a function, but in Clojure the keywords are functions. With the current state, they will be painted as keywords, which is fine, but when you index source code of Clojure compiler, there will be no reference to `for` function, but will only be highlighted as keyword.

Confusing?

Or, I can push as is and later we can improve the thing. What do you think about that?

**Comment by tarzanek** [comment]
no
not confusing at all

so if ctags will recognize "for" as a symbol
then don't put it into keywords
and xref should show them properly as defs/refs

but feel free to ask for pull as is and we can improve later on ...

tia
L

**Comment by tarzanek** [comment]
btw. with merge - I started using a macro for jflex calls, instead direct target call, other than that I don't see any obvious probs with the push ... 
maybe another comment - make sure the ctags additions are ok. with regards to escaping \ (see discuss - https://java.net/projects/opengrok/lists/discuss/archive/2015-02/message/16 )

**Comment by tarzanek** [comment]
@sanel try to open a pull request so we can get stuff moving ;)

tia
L

**Comment by tarzanek** [comment]
@sanel still interested in this?
I have all your OCAs, I just need the pull request and can accept your code ...

**Comment by sanel** [comment]
Hi,

Yes; sorry for taking it too long. Give me couple of days to wrap up the project I'm currently working on, and I will push the changes with updated code.

**Comment by tarzanek** [comment]
and after pushing ask for pull request
if you add later changesets they will be automatically added to the branch of pull request so don't worry about merging with existing pull requests, it's done automagically :)

**Comment by sanel** [comment]
Just created PR. I think I forget to create tests for it; would you like me to check that one?

Also, regarding to this PR, would you like we continue discussion here or at PR page?

**Comment by tarzanek** [comment]
Tests would be great
If you can work on them it'd be cool
We can accept them as next PR worst case

**Comment by giorgio-v** [comment]
Any progress on this?

**Comment by tarzanek** [comment]
I think this is merged.
I need to close the bug, I think it's open because of missing tests

**Comment by giorgio-v** [comment]
I'm completely new to OpenGrok, but let me if I can help in some way. 

--
Giorgio Valoti

**Comment by tarzanek** [comment]
@giorgio-v feel free to look at how junit testing is done and add example clojure sources
other than that I think the analyzer should work properly, so with a build from trunk you should be able to index any clojure file.

**Comment by tarzanek** [comment]
closing, open a new bug for junits please
