### ISSUE TITLE
Add scope context to search results

### ISSUE THREAD

**Issue by mrate** [OpenGrok/OpenGrok#875]
It would be nice to display scope context on page with search results - i.e. apart from matched line display also a function name inside which the symbol was found.

I have a functional prototype for C/C++ which I'm willing to pull after some tidying is done.

**Comment by tarzanek** [comment]
I left you comments on https://github.com/mrate/OpenGrok/commit/55cf33bed98b1ae48e842ed61648c2d0b623168c
good work! (and thank you for this feature, if it won't increase index too much it is definitely useful feature)

**Comment by mrate** [comment]
Thanks!

And thanks for the exhaustive code review, I'll work it all up and make another commit. We also talked with vladak, that it would be good to have some unit testing of this. But that would be another step I suppose. First I'll measure size differences of some big projects (currently I tested it on linux kernel 3.16 and onnv gate) - with and without this feature and we'll see.

**Comment by tarzanek** [comment]
yes, unit tests would be really cool and needed, check on helius.cz.oracle.com jenkins or sonar service on stats how it looks like with code coverage and pmd/checkstyle/findbugs bugs

**Comment by vladak** [comment]
In general, would it be possible to have a tunable which would disable the extra tag processing ?

**Comment by tarzanek** [comment]
btw. you can register your github on https://travis-ci.org/
and it will build your repos
alt. is that if you create a pull request, it will automatically be shown and tested here:
https://travis-ci.org/OpenGrok/OpenGrok/pull_requests

**Comment by tarzanek** [comment]
(build + test on travis ... not 100% tests are run there though, so helius will be in the end the final test)

**Comment by mrate** [comment]
So, I've ran some tests regarding index sizes with and without scopes. I used two repos for test - linux kernel 3.16 and on12 gate. Results are:

linux+on12:
with scopes:            849M
without scopes:       863M (~ 0.016% size increase)

Just on12 gate:
with scopes:            364M
without scopes:       396M (~ 0.014% size increase)

And I believe it can go even lower as I realized that scopes are now serialized in index even if they are empty for given document.

Another question would be how to add scopes to existing indexes that are generated incrementally :-)

**Comment by tarzanek** [comment]
so the size of the index actually decreased? :-D wtf?

don't worry about incremental index - it just works(tm) out of box

**Comment by mrate** [comment]
D'oh! I swapped "with" and "without" in previous post :-)

**Comment by tarzanek** [comment]
:-D ok ... I think this is still doable
if possible get rid of empty scopes to be indexed (lucene will probably optimize, but give it a try what difference it will make)

**Comment by mrate** [comment]
The difference on ON12 gate with and without serialization of empty scopes saves exactly 264 bytes on 369MB index :-)

Do we want the "enable scopes" option on or off by default?

**Comment by vladak** [comment]
Given the low impact I think it should be on.
