### ISSUE TITLE
do not let invalidateRepositories() run wild when doing partial indexing

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#880]
When doing partial indexing (related to #876) the code path is needlessly going through the `setConfiguration() -> invalidateRepositories()` path where all the projects are traversed while only the projects being reindexed require such treatment. This is inflating the time needed to index as getRepository() runs all sorts of commands.

**Comment by tulinkry** [comment]
This is not closed as long as the indexer sends always the `projectsEnabled` property which performs the refresh for all repositories. (there is some optimalization, see #2571)
