### ISSUE TITLE
add unit tests for Haskell

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#913]
Haskell support was added (pull req #912), it needs some unit tests.

**Comment by harryxp** [comment]
I'm happy to do it.  I'm not familiar with your process though.  Do I need to assign it to myself (I haven't figure out how) or I can just go ahead working on it and make another pull request when I'm done?  Thanks.

**Comment by tarzanek** [comment]
yeah
just work on it
I will assign you to it
then in pull req say it will fix this bug and upon push justice will be done :)

tia
L

**Comment by tarzanek** [comment]
aha, I cannot assign you to it this bug :) 
OK, so just open a pull req, but has to be owned by someone with commiter rights, so whomever will pickup the pull req will close the bug

thank you
L

**Comment by vladak** [comment]
just use 'fixes #913' in commit comments and the bug will be closed automatically upon integration.
