### ISSUE TITLE
Failed to create index when there are long lines with 700000+ chars in one line in a file

### ISSUE THREAD

**Issue by doris2012** [OpenGrok/OpenGrok#922]
we have a file with two line which have 7000000+ chars in one line, and when we run ./OpenGrok index , it have been pending. 

I tried to deleted the two lines, it quickly to generate index.

I wonder if there is any settings to fix the problem?

**Comment by tarzanek** [comment]
this smells like ctags problem
what is the head -3 of the file and its file name (extension?) ?

**Comment by vladak** [comment]
Also see #1170

**Comment by tarzanek** [comment]
well ... I think I can safely close this as as duplicate of #1170 
@doris2012 please reopen if it's something else
