### ISSUE TITLE
How can I limit the number of history logs that are shown in the page? 

### ISSUE THREAD

**Issue by verascone** [OpenGrok/OpenGrok#924]
Hello.

I am using OpenGrok with git repositories.
When I view history logs, all logs appear in one page. It makes loading time longer and sometimes it fails. Is there a way(or option) to limit the number of history logs that are shown in the page? 
If not now, do you have any plan to include this function?

Thank you.

**Comment by vladak** [comment]
This is currently not possible, there is issue #404 filed to track this.
