### ISSUE TITLE
Access control needed on OpenGrok

### ISSUE THREAD

**Issue by doris2012** [OpenGrok/OpenGrok#925]
Currently any guys who can open our opengrok web page, he can download codes and view code, which is not security.

so access to opengrok is needed, such as integrated LDAP authority.

**Comment by tarzanek** [comment]
out of scope - we implement this based on tomcat auth (see tomcat auth services)
and we also have an implementation based on Oracle SSO

HOWEVER there is a bug for fine grained authentication, which would enable per project auth (forgot the number, search issues - #503 ? )

**Comment by tarzanek** [comment]
yes, it is #503 , fwiw there might be some sponsored work on it to get to fine grain (or if you interested in it, patches are always welcomed, ev. you might pair up with whomever will work on #503 - @vladak do we have someone internal on it? or some student/intern?)
if you don't care about fine grained, see docs of tomcat or some SSO solution on how to provide login/password access to your webapp

hth
L

**Comment by vladak** [comment]
The recommended way how to implement basic access check is to place the container behind proxy which provides authentication and authorization, e.g. Apache with `mod_authnz_ldap`.

#503 will be worked by someone rather soon.
