### ISSUE TITLE
Feature request: Support Pascal

### ISSUE THREAD

**Issue by claunia** [OpenGrok/OpenGrok#929]
Add support to Pascal language. Interesting to have classic Pascal, Apple Clascal and Object Pascal (Delphi) dialects.

**Comment by tarzanek** [comment]
this would be very easy to do ... just write lex grammar parsers for symbols and xrefs ... see recent pushes for haskell, or older for scala/python/...
ctags even support this out of box!

**Comment by tarzanek** [comment]
e.g. erlang:
https://github.com/OpenGrok/OpenGrok/commit/901a436889cb2a6b2921b09f601b43c2cea360c8

but see haskell for nice unit tests, too

**Comment by claunia** [comment]
Interesting.

Seems easy if you know the language.
But my Pascal is very very dirty.

I could give a try. Unfortunately the only big Pascal project I have is Apple Clascal and under NDA.

Let's see...

**Comment by tarzanek** [comment]
you might be able to find pascal lexical grammars online ...
and jflex has nice manuals and samples
also pascal grammar is easy itself ...

**Comment by tarzanek** [comment]
@claunia give it a shot! :)
it's easy and funny exercise
you can test it on any free pascal source on web, worst case I can send you some of my old samples I used at high school
some inspiration on how to write an analyzer is in #998

**Comment by claunia** [comment]
@tarzanek I have not forgotten about this. Unfortunately it's not on top of my priority list.

If the time comes when I need to deploy OpenGrok and no one has gotten here first, don' worry, I have a lot of code in Turbo Pascal, Apple Clascal, Apple Object Pascal and Delphi to test with.

**Comment by alexanthony** [comment]
I got started on this. I used the lazarus source code (http://www.lazarus-ide.org/) as a codebase to test this on.

**Comment by claunia** [comment]
@alexanthony great! have you tested with other dialects? (Clascal, Turbo, Delphi, etc)

**Comment by alexanthony** [comment]
@claunia not been able to yet, but i'll give it a go if you can point me at some source code I can try it out on (the object pascal in lazarus looks pretty similar to the delphi I'm actually used to though).

I've had a fiddle with improving support for classes in object pascal/delphi above what ctags gives though using regex, with some success.

**Comment by alexanthony** [comment]
@tarzanek I've been having a play with some junit tests and trying to get the class handling better, I'll try to get another patch in at some point.
Do you have a rough idea when you're intending to release 0.13?

**Comment by tarzanek** [comment]
well I think it should be any time now, I think there is only one stopper (new mercurial problem) and one improvement (multireader reuse) pending, 
so my guess is 1-3 weeks?
@vladak ?

**Comment by vladak** [comment]
Bunch of weeks, although if you look at bugs with milestone 0.13 we have a lot of work to do still :)
