### ISSUE TITLE
lastModified value not updated in Configuration.getDateForLastIndexRun()

### ISSUE THREAD

**Issue by fregienj** [OpenGrok/OpenGrok#948]
The home page shows the date for the last index run, but this date is not being updated on a re-index. It is only updated on a app server restart.

 It appears that the Configuration.getDateForLastIndexRun() method has a null check on 'lastModified' and only updates the 'lastModified' date if the previous value was null.  It looks like this null check should not be there.  I'm not sure what it buys you. You always should be getting the last modified date of the file, and not cache the original value.

**Comment by tarzanek** [comment]
I suppose configuration being sent to webapp should make sure this is updated too
(upon reindex this config is sent to webapp)
and I would stay with caching, you don't need to poll this for every web request

**Comment by scottk** [comment]
I have this issue as well, I created a pull request to allow users to manually update the referenced date without changing the original functionality

**Comment by tarzanek** [comment]
@scottk @fregienj 
I updated the indexer that upon sending the configuration.xml if the index is refreshed, the timestamp will also be updated, also all "caching" stays
will that work for you?
Or @scottk how does your jenkins reindex job runs? Do you use sending of config back to webapp?

**Comment by tarzanek** [comment]
(I will push soon, with 5.5.0 lucene update, but just wanted to figure out if it will fix your use case)

**Comment by tarzanek** [comment]
this got fixed with  #1192
