### ISSUE TITLE
Add 'ph' files to the list of supported Perl files

### ISSUE THREAD

**Issue by ymnick** [OpenGrok/OpenGrok#954]
Currently OpenGrok recognizes "pl", "perl" and "pm" files as Perl files, what would it take to add "ph" to the list? It finds content in "ph" files when "Any" type is selected but not when "Perl" is selected as a type.

https://github.com/OpenGrok/OpenGrok/wiki/Supported-Languages-and-Formats

Thanks,
ymnick

**Comment by vladak** [comment]
Source code wise, `PerlAnalyzerFactory.java` is the file which defines the suffixes. I am not sure if ctags also needs some treatment in the form of `--langmap=Perl:+.ph`.

**Comment by tarzanek** [comment]
https://github.com/universal-ctags/ctags/blob/master/parsers/perl.c#L530
so it would need to be added to langmap, too, perhaps we can copy the rest of extensions from above to our parser too

**Comment by ymnick** [comment]
Added 'ph' to PerlAnalyzerFactory.java (waiting for merge) and to perl.c (merged to master). What should be the next steps - wait for the new opengrok release and create my own ctags build?

**Comment by tarzanek** [comment]
I guess you can create your own opengrok build now too (I just merged)
make sure you index from scratch, dev trunk uses latest lucene which dropped old index compatibility
I am closing this request since #967 is integrated

**Comment by ymnick** [comment]
OpenGrok now finds content in *.ph files using full search but not definition search, as it does for *.pl files, I wonder if it's because I didn't update ctags after the change - https://github.com/universal-ctags/ctags/pull/457
