### ISSUE TITLE
Add swift syntax highlighting

### ISSUE THREAD

**Issue by sjaensch** [OpenGrok/OpenGrok#956]
Currently, OpenGrok does almost no syntax highlighting for source code written in Apple's Swift language (file extension: .swift). It would be awesome if it did.

**Comment by tarzanek** [comment]
if you know the language, please have a look at git history on how other analyzers were written, it's not that hard, give it a try!
I am not sure though if ctags support the language, alt. you will have to write its support using regexps (see e.g. scala)

**Comment by idodeclare** [comment]
Ahh, this was added in 14bce55023b2d6b9 on Fri, 2017 Jun 16.

**Comment by tarzanek** [comment]
target is release 1.1
