### ISSUE TITLE
add Ruby analyzer

### ISSUE THREAD

**Issue by potashj** [OpenGrok/OpenGrok#958]
The shanalyzer appears capable of finding ruby files. Editing the html to submit "Ruby" in the "Type" field yields results consisting largely of .rb, .erb, and Gemfiles in addition to some other unexpected types, but mostly what you'd expect. It'd be great to have this as select-able option by default!

**Comment by tarzanek** [comment]
Why not adding a ruby analyzer?

Lookup history of commits, find perl or python analyzer, or any recent commit for analyzers
exuberant ctags supports ruby out of box, so all should be easy as far as writing a jflex gramar for it (which should be easy too)

xing the fingers
L

**Comment by tarzanek** [comment]
(I guess if you have or learn lexical analysis (it's enough to read other analyzers, find closest one and copy it for your purposes and fix its lex files, read jflex docs on what and how to do it) , then this task for ruby analyzer should be a matter of few hours, it's a nice java/OpenGrok/jflex learning exercise too! :) )

**Comment by tarzanek** [comment]
@potashj care to add the analyzer?
look at golang pull req, or scala, etc.  
have a look at pull req  #998

**Comment by vladak** [comment]
fixed in 414fc60
