### ISSUE TITLE
OpenGrok perfomance loss after a few minutes

### ISSUE THREAD

**Issue by kreutziger** [OpenGrok/OpenGrok#968]
OpenGrok version 0.12.1
size of repositories 26G
2 vCPU
9 GB ram (-Xmx 8G)

If I add new repositories to the src directory and index them, the java process loses cpu usage after a few minutes (from ~90% to ~3%). We use a big list of ignore_patterns, to exclude binary data from the indexing process. There is no message in the logs. How can I improve this?

**Comment by tarzanek** [comment]
opengrok indexes by projects so I'd say you have one big project and few small ones
They finish and the big project goes on, but only with one thread
OpenGrok parallelizes per project ... (I know, not ideal, not optimal, we should improve this)

**Comment by tarzanek** [comment]
certainly, you can fetch jstack to see what is going on, but I think my above assumption is close to truth
the other option (jstack will tell) is that OpenGrok is "stuck" somewhere ...

**Comment by kreutziger** [comment]
Thanks for the tip, I will research it further, if I have to deal with it again.
