### ISSUE TITLE
Universal Ctags not supported

### ISSUE THREAD

**Issue by ymnick** [OpenGrok/OpenGrok#971]
OpenGrok indexer fails with the new ctags built locally from universal-ctags/ctags, I believe the reason is in the output of '--version' command between the older and the newer version of ctags:

older - 'Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert'
newer - 'Universal Ctags Development, Copyright (C) 1996-2009 Darren Hiebert'

If that's the case I'll create a pull request for org.opensolaris.opengrok.configuration.RuntimeEnvironment to support the newer ctags version.

c:\opengrok\lib>java -jar opengrok.jar -W C:\opengrok\configuration.xml -c C:\ctags\ctags.exe -P -S -v -s C:\p4_all -d C:\opengrok\grokdata
Logging filehandler pattern: %h/java%u.log
Jul 28, 2015 2:56:27 PM org.opensolaris.opengrok.configuration.RuntimeEnvironment validateExuberantCtags
SEVERE: Error: No Exuberant Ctags found in PATH !
(tried running C:\ctags\ctags.exe)
Please use option -c to specify path to a good Exuberant Ctags program.
Or set it in java property org.opensolaris.opengrok.analysis.Ctags
Jul 28, 2015 2:56:27 PM org.opensolaris.opengrok.index.Indexer main
SEVERE: Exception running indexer
org.opensolaris.opengrok.index.IndexerException: Didn't find Exuberant Ctags
        at org.opensolaris.opengrok.index.Indexer.prepareIndexer(Indexer.java:650)
        at org.opensolaris.opengrok.index.Indexer.main(Indexer.java:587)

**Comment by tarzanek** [comment]
I tested this ctags fork before the rename, let me check, I have a copy of them so will update and fix this asap since I use them too.
Darrens original code seems dead :(

**Comment by ymnick** [comment]
Thanks
