### ISSUE TITLE
Single quoted string rendering issue

### ISSUE THREAD

**Issue by caipre** [OpenGrok/OpenGrok#973]
I'm using the OpenGrok 0.12.5 binary from https://java.net/projects/opengrok/downloads/ and seeing some strange behavior around quoted strings in PHP sources. All single quoted strings are rendered with a single quote opener and a double quote closer, eg:

![capture](https://cloud.githubusercontent.com/assets/295094/9063630/78fe5a9e-3a96-11e5-943b-e84a348ec6ee.png)

In the source, that's a single quoted string. Double quoted strings are unaffected, as are single quoted strings in other languages (checked Python and C++).

I don't know what would cause this; any thoughts?

**Comment by tarzanek** [comment]
there might be a bug in generating xrefs : 
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/php/PhpXref.lex#L242

can you try debugging this ?
jflex knowledge is needed, the rest info is on opengrok wiki (how to debug, setup env, etc.)
https://github.com/OpenGrok/OpenGrok/wiki

it seems like recursion and inner loops might be confused, try to isolate the code, or share the file so other people , perhaps @cataphract  can have a look, too
