### ISSUE TITLE
indexpart parameter of OpenGrok's script 

### ISSUE THREAD

**Issue by sogartar** [OpenGrok/OpenGrok#975]
Hi,
I am running OpenGrok on Linux. What is the indexpart parameter in the OpenGrok script?
Does it specify to index only some part of the source? How should one use it? The documentation is very lacking.

**Comment by vladak** [comment]
Yes, `indexpart` provides support for partial reindex, e.g. if you want to index single project only. Pretty good explanation can be found in  issue #876. I will update the README file with this information so that is it readily available.

**Comment by vladak** [comment]
Pls see the related pull req and lemme know if there are some things which need further clarification.

**Comment by tarzanek** [comment]
clear as ice to me :) thank you @vladak !

**Comment by sogartar** [comment]
It is unclear what indexpart is. Is it a directory relative to the source root? Or is it some element from the configuration.xml?

**Comment by sogartar** [comment]
I suspect that the indexpart option is broken. Because in this case opengrok.jar is called without SRC_ROOT and DATA_ROOT being specified. This results in an errors in opengrok.jar, complaining about the missing options.

**Comment by vladak** [comment]
It works just fine - we have been using it every day for couple of months. It is necessary to run the indexpart with readonly config which contains both src and data root.

**Comment by vladak** [comment]
Yes, the argument to the `indexpart` is relative to `SRC_ROOT`.

**Comment by PawanKulkarniS** [comment]
Dear Vladimir,
 
 Thank you for the inputs above & great contribution to Opengrok release.
 With 0.12.1.5 (stable) is there a heuristic indicator/Dashboard that shows following - 
  1.  How much time it may take to complete the indexing ?
  2.  If It is is getting re-indexed how much time it would take to complete ? 
  3.  At any point of time say while index is running, How much index/re-index is completed ? in percentage ?
  4. So far how much of individual meta data is built   - % of historycache , % of index, % of xref, % of spell index

 This  would largely benefit to track & report large repo indexing jobs.
 would you please mail me your comments/know how  which i may use to predict indexing rates.
 pawankulkarnis@rediffmail.com.

Best Regards - Pawan Kulkarni. S

**Comment by tarzanek** [comment]
there is an option -C which prints progress
it's I/O intensive
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/CommandLineOptions.java#L78
