### ISSUE TITLE
document json

### ISSUE THREAD

**Issue by vladak** [OpenGrok/OpenGrok#978]
This is placeholder for documenting json API as delivered in #50 . Not sure where the best place would be - ideally in both source code, wiki and README.

**Comment by slayoo** [comment]
Quick question related with the topic - is there any action needed to enable the json API after installation? We've just upgraded to 0.12.1.5 (d305482d0acf552ccd290d6133a52547b8da16be) but /source/json gives a "Error: File not found!". Thanks for help

**Comment by vladak** [comment]
json should be available by default, no config needed. json changesets are not present in 0.12-stable, however.

**Comment by slayoo** [comment]
thanks

**Comment by tarzanek** [comment]
https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-web-services

**Comment by vladak** [comment]
Given the above wiki page contains basic info about JSON, I am closing this now.
