### ISSUE TITLE
html pages rendering

### ISSUE THREAD

**Issue by sumkincpp** [OpenGrok/OpenGrok#979]
Is it possible to force rendering of html pages in opengrok?
Currently only xml formatted code is shown as well as whole `raw` code.

**Comment by tarzanek** [comment]
?
Rendering where?
OpenGrok webapp renders valid xhtml pages which most browsers show properly ...

**Comment by vladak** [comment]
I think what is meant here is the effect on clicking on HTML file e.g. in the list view.

**Comment by vladak** [comment]
I am not sure if it makes sense to let it be displayed in the browser. Firstly, it would be an exception to how we handle textual files. Secondly, only very simple HTML files would be rendered correctly given all the references to CSS, scripts, libraries etc.

**Comment by sumkincpp** [comment]
Sorry for confusion, rendering of html pages in browser.

Currently html files are formated like xml documents and it's possible only to get Raw file(Content-Type	
text/plain;charset=UTF-8) or Download it. But not to show html file in browser by sending html content and specifying correct headers.

Given an assumption that all resources in html files are relative to the folder where html is located(i.e. without opengrok, html pages are rendered correctly) is it possible to be able to add functional to render html resources with certain extensions like ordinary html-pages?

**Comment by vladak** [comment]
I have the suspicion that the assumption does not stand for a number of pages. In general, seeing the source of the html page is more beneficial than the rendering, on the basis that OpenGrok is source code browser. Adding a special case just for HTML (or for any other type) would complicate both the code and the experience. 

Maybe you can expand on your use case a bit however I don't think this would fit the overall design.

**Comment by vladak** [comment]
No response for more than a year, closing.
