### ISSUE TITLE
Error reading from a git log

### ISSUE THREAD

**Issue by bond-** [OpenGrok/OpenGrok#985]
git version 1.9.1

The command error given in below stacktrace works properly if I execute manually from command line and opens it in a "less" command view. Now sure why it throwed a exit status -1 error.

Please check

```
11:18:03 WARNING: Non-zero exit status -1 from command [/usr/bin/git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller] in directory /path/to/project
11:18:03 WARNING: An error occured while creating cache for /path/to/project (GitRepository)
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "/path/to/project" Exit code: -1
	at org.opensolaris.opengrok.history.GitHistoryParser.parse(GitHistoryParser.java:156)
	at org.opensolaris.opengrok.history.GitRepository.getHistory(GitRepository.java:406)
	at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:296)
	at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:495)
	at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:53)
	at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:545)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by harryxp** [comment]
For this and #984, it looks like the path to the project isn't real (/path/to/project).  What arguments did you issue to OpenGrok script?

**Comment by bond-** [comment]
./OpenGrok index /path/to/root-of-project

For ex: I have the following structure:
-UserHome
-|-all-projects \#root-of-project
--|-project1 \#project
--|-project2

**Comment by bond-** [comment]
What I did was
1. Created a index around 3 months ago on git repos
2. Ran the command `./OpenGrok index /path/to/old/root-of-project`
3. Today I pulled the latest from git from all projects
4. Moved the repos to a different directory
5. Ran the command `./OpenGrok index /path/to/new/root-of-project`

And the errors are popping up. Do I need to follow a different procedure for reindexing?

**Comment by harryxp** [comment]
Not sure, but I'd delete old index files (under opengrok_instance_base/data) and try again

**Comment by bond-** [comment]
I still see the same logs

**Comment by gsarode** [comment]
I see the same issue but my path is not simlink. It is the actual path.

08:59:03 WARNING: Non-zero exit status -1 from command [/usr/bin/git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller] in directory /home/gsarode/opengrok/src/android/frameworks/base
08:59:03 WARNING: An error occured while creating cache for /home/gsarode/opengrok/src/android_xml/frameworks/base (GitRepository)
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "/home/gsarode/opengrok/src/android_xml/frameworks/base" Exit code: -1

**Comment by tarzanek** [comment]
@gsarode 
auth issues? permission issues?

**Comment by gsarode** [comment]
Looks like issue was, very long history of git .When I limit the git
history using "--depth" option, all work fine.


--
Gaurav

**Comment by vladak** [comment]
By default the timeout for Executor is 10 minutes. This is tunable in configuration (number of seconds). After the changes for #1095 the timeout for initial `git log` is infinite so closing for now. Feel free to reopen if this is still an issue.
