### ISSUE TITLE
Opengrok ignoring a directory

### ISSUE THREAD

**Issue by conuil** [OpenGrok/OpenGrok#992]
Hi,

I have 2 cvs systems (one in acceptance and one production). In acceptance this particular directory (called notes) is being processed by opengrok. I can see from the Opengrok update log.

16:45:57 INFO: Add: /SCM/common/pub/sbu/inp/sbu_all.inp (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/explnote5-1.tex (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/explnote5-2.tex (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/explnote5-3.tex (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/explnote8-1.tex (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/explnote9-1.tex (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/gennotes.tex (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/sbustyle.sty (PlainAnalyzer)
16:45:57 INFO: Add: /SCM/common/pub/sbu/notes/technotes.tex (PlainAnalyzer)

But when I run the same update in production it just completely ignores the directory. 

16:52:04 INFO: Add: /SCM/common/pub/orb/tag/orb_toc.tag (PlainAnalyzer)
16:52:04 INFO: Add: /SCM/common/pub/sbu/inp/sbu_all.inp (PlainAnalyzer)
16:52:04 INFO: Add: /SCM/common/src/fame/rtf_tools_common.pro (PlainAnalyzer)
16:52:04 INFO: Add: /SCM/common/src/fame/test.pro (PlainAnalyzer)

I've tried deleting the indexes and re running the whole thing, I've checked the files in the directory and they seem to be valid CVS files. Is there any reason why opengrok would skip a directory? Maybe if someone could point me in the direction of the code that figures out which directories to process.

I'm using solaris with opengrok-0.11.1. 

Thanks

Emmet

**Comment by tarzanek** [comment]
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/IgnoredFiles.java#L35

and

https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/index/IgnoredDirs.java#L35

are your dirs falling into one of those categories?
Also I noticed you're on 0.11.1 - we (actually @vladak did  ) improved ignored files handling a lot in latest releases go for latest please

(but I noticed above is only in to be released 0.13 :( , 0.12 is still doing old bad thing: https://github.com/OpenGrok/OpenGrok/blob/0.12-stable/src/org/opensolaris/opengrok/index/IgnoredNames.java#L34 )

though I cannot explain how come it is working in test and failing in prod ... perhaps some SCM magic that gets the files ignored if they are outside of source root?
symlinks in play?

**Comment by conuil** [comment]
Thanks for getting back to me so quickly. 
No its not any of those names. I looked in opengrok/source and saw the directory wasn't there so I forced a checkout with CVS. 

cd $SDPE_TOOLS/sis/opengrok/source
cvs -d $SDPE_TOOLS/cvsroot checkout SCM/common/pub/sbu/notes

then I reran the whole thing again

rm /global/proddatadg/sdpe/tools/sis/opengrok/data/index/SCM/*
$SDPE_TOOLS/sis/opengrok/bin/run.sh > /sis-home/ryanemm/tmp/rundotsh.log

run.sh does a cvs update and an OpenGrok update. And now it seems to be working!

**Comment by tarzanek** [comment]
Yes you need a checkout from SCM
You cannot work just on top of CVS or .hg or .git dirs ...

**Comment by vladak** [comment]
Seems to be resolved by doing checkout, closing.
