### ISSUE TITLE
Scala function definitions

### ISSUE THREAD

**Issue by hseuming** [OpenGrok/OpenGrok#993]
Hi, 
i have been running several instances of {OpenGrok for C++ (> 100,000 files), C, Java, Python, Perl, etc. over the past few years.   i kicked off a new instance last week to index some Git repos containing mostly Scala and Java programs.    For Java programs, all is well.   However, for Scala programs, i can't seem to find function definitions.    i mean for "Full Search", things look good but not for "Definition".    Is that expected?

Thanks.

**Comment by tarzanek** [comment]
Which version do you run?
I did some fixes there in current dev build ...
Can you try a build from source?

Thnx
L

**Comment by hseuming** [comment]
Hi Lubos,
Thank you for your prompt response.   The version i use is 0.12.1.5 

> Can you try a build from source?
you mean building directly from the head of master?

**Comment by tarzanek** [comment]
Yes, master head has fixes for regexps we use for definitions since exuberant ctags lack support by default

**Comment by hseuming** [comment]
Did you make the needed change after i created Issue #993?   If so, maybe i'm missing something here: the last commit to master is on 2015/8/27 with SHA-1 6035ddd0d ...

If the fix was in an earlier commit, could you please tell me which commit was that?   Thanks.

**Comment by tarzanek** [comment]
Nono like 2-3 months ago, try searching for it or look at history of the ctags file ...

**Comment by tarzanek** [comment]
I mean ctags java file. Not on PC so hard for me to dig up link :(

**Comment by tarzanek** [comment]
https://github.com/OpenGrok/OpenGrok/commits/master/src/org/opensolaris/opengrok/analysis/Ctags.java
I added fixes for regexp to be posix compliant on 7. April 2015

**Comment by hseuming** [comment]
We've decided to wait for the release of 0.13.

In the meantime, i created the local file 
   ~/.ctags
with the --langdef=scala from
   https://github.com/ceedubs/sbt-ctags
to overwrite the Scala language definition and all is well.

Thanks for all the input.

**Comment by tarzanek** [comment]
@hseuming  thnx, we'll try to get out 0.13 before Christmas :)

**Comment by tarzanek** [comment]
ok, so next attempt on 0.13 RC is in few days, we're down to one stopper :)

**Comment by tarzanek** [comment]
closing
