### ISSUE TITLE
Render README.md files in place when browsing directories

### ISSUE THREAD

**Issue by m-renaud** [OpenGrok/OpenGrok#995]
When browsing directories in xref/ the README.md file will be displayed under the directory listing and it would be nice if the markdown was actually rendered.

**Comment by tarzanek** [comment]
@m-renaud  is there some easy to bundle (java) library to render the file?
ideally if that lib would be supported (so not abandoned) and it's size would be reasonable
I plan to integrate tika, I'll have a look if tika can do something like this already ... (but please shoot alternatives)

**Comment by tulinkry** [comment]
I've found two:
- https://github.com/rjeschke/txtmark
- https://code.google.com/p/markdown4j/ (which is fork of the previous one)

**Comment by tulinkry** [comment]
However like I did it in other project recently, it is possible with javascript. So it could be easy to embed a javascript (which would load only when the file is *.md) and to display that file in the browser.

**Comment by tulinkry** [comment]
closed with #1253
